### ISSUE TITLE
Styleguide layouts need to be rebuilt with flexbox grid

### ISSUE THREAD

**Issue by glynnis** [rackerlabs/encore-ui#1004]
After adding the deprecation warning to pure grids (#1003), I realized that we still need to convert our styleguide layout examples (http://rackerlabs.github.io/encore-ui/#/styleguide/layouts) to use the new grid, especially before we deprecate pure altogether.

**Comment by anur2213** [comment]
Related Jira story:
https://jira.rax.io/browse/FRMW-443
Sub-task of Jira story:
https://jira.rax.io/browse/FRMW-341
