### ISSUE TITLE
Responsive CSS file includes base layout module twice

### ISSUE THREAD

**Issue by TheNando** [rackerlabs/encore-ui#1016]
When I added this, I didn't think through that all the less files were being concatenated together automatically. Including the explicit base layout import in the responsive less causes the layout module to be duplicated in the compiled responsive css file.

**Comment by megalord** [comment]
@TheNando has this been resolved?

**Comment by CITguy** [comment]
@TheNando, has this been resolved?

**Comment by CITguy** [comment]
Closed via #1017
