### ISSUE TITLE
Check for `console.error` in the browser during Protractor tests.

### ISSUE THREAD

**Issue by Droogans** [rackerlabs/encore-ui#1019]
Right now we're opening up PhantomJS, loading each component, and then checking the console for javascript errors.

I love the idea, however, Protractor has a way to natively do the same thing, which could happen during the end to end tests.

https://github.com/angular/protractor/blob/master/docs/faq.md#how-can-i-get-hold-of-the-browsers-console

a better link

https://github.com/juliemr/protractor-demo/blob/master/howtos/browserlog/spec.js

**Comment by Droogans** [comment]
I think this would work best inside of rx-page-objects so that I could use this in other PR builders.

**Comment by CITguy** [comment]
I was able to do something a bit more straightforward in #1032:

```javascript
describe('deprecated directive', function () {
    var sandbox;
    var template = '<rx-deprecated-directive></rx-deprecated-directive>';

    beforeEach(function () {
        sandbox = sinon.sandbox.create();
        sandbox.stub(window.console, 'warn');
        helpers.createDirective(template, compile, scope);
    });

    afterEach(function () {
        // restore the environment as it was before
        sandbox.restore();
    });

    it('should emit a deprecation warning in the console', function () {
        expect(console.warn).to.be.calledOnce;
        expect(console.warn).to.be.calledWithMatch('DEPRECATION WARNING');
    });
});
```

**Comment by CITguy** [comment]
Closing. Captured in JIRA https://jira.rax.io/browse/FRMW-84
