### ISSUE TITLE
Add See More/See Less collapsable component for meta-data

### ISSUE THREAD

**Issue by ElementE** [rackerlabs/encore-ui#1022]
JIRA Story here:
https://jira.rax.io/browse/EOD-614

To show and hide meta-data in areas where space is limited, we need a component in the framework that styles the see more/see less functionality.

This also needs to be added to the styleguide documentation in the meta-data section.

![collapse-expand](https://cloud.githubusercontent.com/assets/7989545/8010722/1a0c2888-0b78-11e5-8e36-9c0635c581f1.png)

**Comment by megalord** [comment]
@ElementE how is this related to #989?

**Comment by ElementE** [comment]
@megalord This is just to create "official" process for getting this style implemented into the framework. 
More specifically to the design in #989 - this style is for the meta-data content area.

**Comment by CITguy** [comment]
Closing. Already available. See http://rackerlabs.github.io/encore-ui/#/components/rxCollapse
