### ISSUE TITLE
Responsive layout has inconsistencies

### ISSUE THREAD

**Issue by TheNando** [rackerlabs/encore-ui#1027]
All of the layout attributes have responsive versions of their tags (ex. [flex] / [flex-sm]). In addition to '-sm', '-md', and '-lg', there are attributes that act as greater than x and less than x. For example, 'flex-gt-sm' means element will flex on any size greater than small. These attributes work consistently, but with a couple exceptions.

* While there are both 'greater than' and 'less than' attributes defined for layout margin and layout padding, only the 'greater than's have @media queries defined for them, so none of the 'less than's work
* There is no 'less than small' defined, but 'small' acts as 'small' & 'less than small'. However, 'large' only applies between the 'medium' and 'large' widths. It would be more consistent for 'large' to also include 'greater than large', complimenting how 'small' works.

**Comment by CITguy** [comment]
Closing. Captured in JIRA https://jira.rax.io/browse/FRMW-86
