### ISSUE TITLE
BUG: z-index for rxSelectFilter is behind rxFloatingHeader

### ISSUE THREAD

**Issue by CITguy** [rackerlabs/encore-ui#1037]
![screen shot 2015-06-11 at 7 21 59 pm](https://cloud.githubusercontent.com/assets/545605/8121278/39b5ee52-106f-11e5-8e00-04d3514a032f.png)

**Comment by CITguy** [comment]
Bug found at http://rackerlabs.github.io/encore-ui/#/component/rxPaginate

**Comment by parlarjb** [comment]
If you check the latest rxFloatingHeader demo at http://rackerlabs.github.io/encore-ui/#/component/rxFloatingHeader you'll see that it's broken too. Something change when we moved to the rxSearchBox

**Comment by CITguy** [comment]
@parlarjb, the issue in the rxFloatingHeader is because the `rxSearchBox` is in a `td` instead of a `th.filter-header`.  It's not related to this bug.

**Comment by CITguy** [comment]
@parlarjb, I've corrected the rxFloatingHeader issue in #1039

**Comment by CITguy** [comment]
FYI: `rxFloatingHeader` + `rxSearchBox` bug is different from this one.

**Comment by CITguy** [comment]
Closing. Captured in JIRA https://jira.rax.io/browse/FRMW-66
