### ISSUE TITLE
rxMisc is missing a stability badge in its README.md

### ISSUE THREAD

**Issue by TheNando** [rackerlabs/encore-ui#1040]
Each component contains an image file representing its stability status as the first line in its README.md, except for rxMisc.

**Comment by CITguy** [comment]
Yeah, this was my bad when I created `rxMisc`. I'm making changes to that component anyway, so I'll put it in.

**Comment by CITguy** [comment]
Closing. Added with [rxForm 2.0](https://github.com/rackerlabs/encore-ui/commit/03d86aa990d8a875dcf228951ff256f3bec94d9e)
