### ISSUE TITLE
Update rxStatus Demo

### ISSUE THREAD

**Issue by CITguy** [rackerlabs/encore-ui#1061]
With the addition of the new `<code>` and `<pre>` styles in the demo, the `rxStatus` demo page now has some ambiguous controls.

![screen shot 2015-06-22 at 1 25 14 pm](https://cloud.githubusercontent.com/assets/545605/8289509/7b0d7278-18e2-11e5-822f-207c441143a7.png)

Please update `rxStatus` demo to use `rx-button` in order to differentiate buttons from code blocks.

**Comment by glynnis** [comment]
Oh man, good catch! We definitely need to be using rx-button here as you suggested.

@kobowley Can we pull this one over to JIRA as a bug for the next sprint? I think LOE should be relatively low.
