### ISSUE TITLE
rxFloatingHeaders end-to-end tests are brittle

### ISSUE THREAD

**Issue by TheNando** [rackerlabs/encore-ui#1072]
The end-to-end specs for rxFloatingHeader will fail if the page height is tall enough to fit the entire page. If the entire table fits into view, there will be no option to scroll and no way for the header to scroll out of view, thus the header will not float.

A possible work around is the set the window height smaller in the protractor config, though this seems hacky. Another solution is to encapsulate the tables into another container whose height can be programmatically changed. I am not positive that will produce the effect, though. It is just an idea.

Either way, this test seems brittle and will commonly break when ran locally. We should research an alternative.

**Comment by CITguy** [comment]
Closing. Captured in JIRA https://jira.rax.io/browse/FRMW-70
