### ISSUE TITLE
CSS: update button styles

### ISSUE THREAD

**Issue by CITguy** [rackerlabs/encore-ui#1084]
Per [this conversation](https://github.com/rackerlabs/encore-ui/pull/1081/files#r33693788), using the `.button` class on a `<button>` element, seems redundant as a CSS selector (`button.button`).  We should apply the styles to both `button` and `.button` instead to eliminate the redundancy and to simplify the amount of markup needed to implement at an app level.

```LESS
button, .button { ... }
```

@glynnis mentioned that this could potentially break styling in dependent apps if they use the `<button>` element for purposes other than what was intended by the framework.  We'll have to provide ample communication to our stakeholders about the change.

**Comment by glynnis** [comment]
@CITguy Looks like this had a PR associated with it, so I'm closing. Please re-open if this hasn't been addressed.

**Comment by CITguy** [comment]
Associated issue was to remove ambiguity in rxStatus demo. Issue still relevant and very similar to `.title` class deprecation.

**Comment by anur2213** [comment]
Related Jira story:
https://jira.rax.io/browse/FRMW-439

**Comment by CITguy** [comment]
Closing. Captured in JIRA
