### ISSUE TITLE
Bring in a fork of Angular Style guide

### ISSUE THREAD

**Issue by TheNando** [rackerlabs/encore-ui#1090]
We currently have a general JS style guide that covers some basics. However, majority of the inconsistencies in the framework relate to specific implementation of Angular patterns. It would be very useful to have an Angular style guide for to increase consistency within the framework and speed up onboarding. A good existing guide to start with (fork) would be https://github.com/johnpapa/angular-styleguide.

**Comment by anur2213** [comment]
Associated Jira story: https://jira.rax.io/browse/FRMW-523
