### ISSUE TITLE
"View Source" and "Improve this doc" links are broken in generated API docs

### ISSUE THREAD

**Issue by parlarjb** [rackerlabs/encore-ui#1100]
@CITguy The links at pages like this http://rackerlabs.github.io/encore-ui/ngdocs/index.html#/api/rxForm.directive:rxInlineError are currently broken

**Comment by CITguy** [comment]
It appears that even the navigation link to "JS Docs" is broken. Was there a recent change that would prevent the ngdocs from being created/served?

**Comment by parlarjb** [comment]
We did a release on Friday, but the ngdocs links were broken before that. The "JS Docs" break might be new, and possibly related to the changes @TheNando made to the build process to create the "All Components" page

**Comment by CITguy** [comment]
@parlarjb, I'm closing this. I think it was a result of the strange deploy issues we had last friday. Everything looks good now.

**Comment by megalord** [comment]
This is still broken as best I can tell.

**Comment by CITguy** [comment]
Where at?

**Comment by parlarjb** [comment]
This was related to the weird deploys happening on my machine, closing.
