### ISSUE TITLE
rxBulkSelect-rxTableFilter does not allow any other element to be added to table head

### ISSUE THREAD

**Issue by cmartinez1499** [rackerlabs/encore-ui#1104]
**issue:** There is no straight forward way to add any elements between the injected table filter and bulk select elements. Any element added to <th rx-table-header> will be over written by the directive.
**my usecase:** adding an rxSelectFilter element into a table head that is using rxBulkSelect-rxTableFilter
<img width="455" alt="screen shot 2015-07-16 at 11 09 25 am" src="https://cloud.githubusercontent.com/assets/1155834/8728526/359e0992-2bab-11e5-9824-146da5540b49.png">
*Example code is from encore-cloud-ui/.../servers/ListServers.html*
```html
<div class="table-filters">
        <table rx-floating-header rx-bulk-select bulk-source="servers" selected-key="rowIsSelected" rx-floating-header class="table-striped servers-list">
            <thead>
                <tr>
                    <th rx-table-filter colspan="10">
                        <li class="actions-item">
                            <rx-modal-action
                                template-url="views/servers/templates/bulk-suspend-modal.html"
                                controller="rxSuspendServersCtrl"
                                classes="msg-info"
                                disable-esc>
                                <i class="fa fa-fw fa-power-off msg-info"></i>
                                Suspend Selected Servers
                            </rx-modal-action>
                        </li>
                        <li class="actions-item">
                            <rx-modal-action
                                template-url="views/servers/templates/bulk-suspend-modal.html"
                                controller="rxUnSuspendServersCtrl"
                                classes="msg-info"
                                disable-esc>
                                <i class="fa fa-fw fa-power-off msg-info"></i>
                                Unsuspend Selected Servers
                            </rx-modal-action>
                        </li>
                    </th>
                </tr>
                ...
         </head>
         ...
</div>
```

**Comment by megalord** [comment]
@cmartinez1499 and I spoke offline.  `rxBulkSelect` was originally written for Encore Cloud, and later brought into the framework.  While that was being done, some parts of the code changed, and one such change fixed this exact issue.  Once Cloud removes their old implementation of bulk select and starts using the framework version, this issue will not be relevant.

Carlos, are we ok to close the issue?

**Comment by cmartinez1499** [comment]
@megalord Yep should be good to close.
