### ISSUE TITLE
rxInput + rxButton Support

### ISSUE THREAD

**Issue by CITguy** [rackerlabs/encore-ui#1106]
rxButton applies a 10px bottom margin which causes the form input to stretch accordingly.

please update `rxForm.less` to remove the margin from `.button` within `rx-input`

**Comment by CITguy** [comment]
With Margin:
![screen shot 2015-07-16 at 3 05 35 pm](https://cloud.githubusercontent.com/assets/545605/8734015/c1f27ccc-2bcc-11e5-8892-caa949db4fbf.png)

Without Margin:
![screen shot 2015-07-16 at 3 10 46 pm](https://cloud.githubusercontent.com/assets/545605/8734026/d34314a0-2bcc-11e5-84d4-c1a7aa716b58.png)

**Comment by anur2213** [comment]
Related Jira story:
https://jira.rax.io/browse/FRMW-436
