### ISSUE TITLE
Update rxAccountUsers to use rxSelect

### ISSUE THREAD

**Issue by CITguy** [rackerlabs/encore-ui#1108]
The `rxAccountUsers` directive is still relying on legacy `<select>` [styling](https://github.com/rackerlabs/encore-ui/blob/7aaec6855af11009ef29193de0c1df85e53aaece/src/rxApp/templates/rxAccountUsers.html), which is has display issues in Firefox.

<img width="557" alt="screen shot 2015-07-17 at 11 25 41 am" src="https://cloud.githubusercontent.com/assets/545605/8752490/f4a7fbee-2c79-11e5-81c3-3e08d590f051.png">

Please update to use `rxSelect` instead.

**Comment by CITguy** [comment]
First look at fixing this, I noticed that the `z-index` for the rxNotification messages may need tweaked to be placed in front of the styled select box generated by `rxSelect`.

![screen shot 2015-07-17 at 11 52 22 am](https://cloud.githubusercontent.com/assets/545605/8752545/483f89e8-2c7a-11e5-8ac3-15f7b817db02.png)

**Comment by anur2213** [comment]
Related Jirs story:
https://jira.rax.io/browse/FRMW-435
