### ISSUE TITLE
rxCharacterCount and required directive interaction

### ISSUE THREAD

**Issue by megalord** [rackerlabs/encore-ui#1115]
Occurs when using these two directives together, e.g.
```html
<textarea ng-model="xxx" rx-character-count required></textarea>
```

To reproduce, type some text and delete it.  The counter does not reset, but is stuck at whatever value it had before the input became empty.  This is because the parser created by the required directive (on `ngModel` controller) returns `undefined` for empty inputs.  The handler in `rxCharacterCount` does not handle a model value of `undefined`.

**Comment by anur2213** [comment]
Related Jira story:
https://jira.rax.io/browse/FRMW-434
