### ISSUE TITLE
Spin up encore-ui-rax private repo for shared internal directives.

### ISSUE THREAD

**Issue by CITguy** [rackerlabs/encore-ui#1123]
There have been more and more questions on where to share common directives that don't really belong in the public framework (Rackspace-specific). This functionality will be crucial for when we get around to splitting up large applications.

I propose setting up an internal `encore-ui-rax` repo to be deployed to our private bower registry?

It would:

* (potentially) house the navigation directives mentioned in this issue
* house any other Rackspace-specific directives that do not belong in the public framework
* directives defined under encore.rax module
* directives prefixed with rax- to differentiate from public framework directives

**Comment by parlarjb** [comment]
This is a topic that's come up over and over. It's generally been viewed as a good idea, with the startup costs being seen as the major blocker.

Namely, getting the build environment configured, midway tests running, etc. Nothing that hasn't been done before for our other projects, but a lot of work when we don't have a solid initial use case.

**Comment by glynnis** [comment]
@CITguy Can we move this over to JIRA as a SPIKE? I think this warrants some research or a written proposal or some kind that could be presented to the Framework team so that everyone is adequately informed and can participate in making a decision about the direction needed here.

**Comment by anur2213** [comment]
Related Jira story:
https://jira.rax.io/browse/FRMW-433
