### ISSUE TITLE
rxFloatingHeader prevents page scroll

### ISSUE THREAD

**Issue by megalord** [rackerlabs/encore-ui#1140]
@KameshAnandan encountered a strange bug where the bottom of a table was cut off (in other words, unable to scroll to the bottom).  This only occurs when using `rxFloatingHeader` and for certain window sizes.  I wasn't able to reproduce this part, but I do see a strange bouncing effect when scrolling to the bottom of the page on the `rxPaginate` demo (which uses `rxFloatingHeader`), and I have an inkling these are related.  Try setting your window height to 800px to reproduce that.

Here are some screenshots provided by Kamesh:
### Working
![screen_shot_2015-08-13_at_9 22 25_pm](https://cloud.githubusercontent.com/assets/5414922/9267401/f2067b5e-4213-11e5-9fc2-4b6c68173a14.png)
### Broken
![screen_shot_2015-08-13_at_9 24 47_pm](https://cloud.githubusercontent.com/assets/5414922/9267402/f6563596-4213-11e5-9561-7e4006e51645.png)

**Comment by CITguy** [comment]
@KameshAnandan, are you still experiencing this issue?

**Comment by anur2213** [comment]
Associated Jira story: https://jira.rax.io/browse/FRMW-522
