### ISSUE TITLE
rxMetaData too close to the title 

### ISSUE THREAD

**Issue by jonkruse00** [rackerlabs/encore-ui#1143]
Got some comments that the `rxMetaData` is too close to `accountinfobanner`'s generated title. 
<img width="488" alt="screen shot 2015-08-14 at 10 22 22 am" src="https://cloud.githubusercontent.com/assets/5339195/9277236/5fa397b4-426e-11e5-9246-b6a229f5dfcf.png">

So what I did for a temporary fix was add a class to the common.less file
``` .metaData-top {
   padding-top: 18px;
}```

<img width="463" alt="screen shot 2015-08-14 at 10 23 38 am" src="https://cloud.githubusercontent.com/assets/5339195/9277263/8ce0019a-426e-11e5-8dcc-797d1b0e78c9.png">

**Comment by CITguy** [comment]
Closing. Captured in JIRA  https://jira.rax.io/browse/FRMW-132
