### ISSUE TITLE
Need a filter for converting from bytes

### ISSUE THREAD

**Issue by rogerza** [rackerlabs/encore-ui#1161]
We have `rxDiskSize` for converting GBs to a more readable format; we need one that does something similar for bytes.

**Comment by Droogans** [comment]
You could borrow the source from the page objects, but you'd need to do it in the reverse.

https://github.com/rackerlabs/encore-ui/blob/master/src/rxDiskSize/rxDiskSize.page.js

I'm sure a similar approach could be used to be more inclusive [of measurements below `'GB'`](https://github.com/rackerlabs/encore-ui/blob/b2b2ca638aebd0e99731e634e8080e25868e20cd/src/rxDiskSize/rxDiskSize.js#L4).

**Comment by anur2213** [comment]
Related Jira story:
https://jira.rax.io/browse/FRMW-432

**Comment by kevincareer427** [comment]
@rogerza  could you give an example for more readable format?

**Comment by rogerza** [comment]
Ideally the filter would be able to convert from more than just gigabytes. So if I put in 1,000,000 bytes, it should say 1 MB, or 1GB for 1,000,000,000 bytes. Maybe it could accept from/to attributes?

**Comment by kevincareer427** [comment]
@rogerza  so you mean you want input two parameters, first is 1,000,000(in bytes) and second is MB(whatever the data size you want to convert to)?

**Comment by rogerza** [comment]
Yes, I think that would be good, since data sizes are usually given in terms of bytes.
