### ISSUE TITLE
Notify.setLoading() should return an object to help manage the 'prop' state.

### ISSUE THREAD

**Issue by thrawn01** [rackerlabs/encore-ui#1177]
It should allow the user todo something like this. 
```javascript
Status.setScope($scope);
doAsync = Status.setLoading('Doing Async thing', 'doAsync');
doAsyncThing()
     .then(function (regions) {
         doAsync.complete();
     }, function (error) {
         doAsync.setError('Error During Async thing: ${message}', error);
     });
```

Encapsulating state like this simplifies state management for much more complex use cases.

**Comment by halkon** [comment]
That's an interesting concept, however in a way that's what `rxPromiseNotification` does itself.

```javascript
rxPromiseNotifications.add(promise, {
            loading: 'Loading Message',
            success: 'Success Message',
            error: 'Error Message'
}, 'demo');
```
https://github.com/rackerlabs/encore-ui/tree/master/src/rxNotify/#rxpromisenotifications

Probably one of the most undocumented services, so I apologize for that.  

You can also omit `success` or `error` if you do not wish to show either of those, `loading` is marked as required.

**Comment by halkon** [comment]
Also in: http://rackerlabs.github.io/encore-ui/#/components/rxNotify you can see a demo of it

**Comment by halkon** [comment]
Btw, I am also not saying that your idea is not valid, I do like the concept of being able to control a specific `Status` notification.

**Comment by thrawn01** [comment]
I think I understand the use case of ```rxPromiseNotification``` but what I'm proposing is slightly different. Mostly in that, you are not aware of what the complete or error message will be before the promise is created. Looks like ```rxPromiseNotification``` assumes you know that the error message will be before the promise is resolved.

**Comment by halkon** [comment]
Indeed it does, plus it also let's you `$interpolate` values in the message, so if your error response is 


You can do:
```javascript
{
    error: {
        message: 'Unauthorized Access'
    }
}
```
will be added as:
```javascript
rxPromiseNotifications.add(deleteSnapshot.$promise, {
    loading: 'Deleting Snapshot',
    error: 'Error deleting snapshot: {{data.error.message}}'
});
```

**Comment by glynnis** [comment]
@thrawn01 @halkon Is this issue resolved? If so, please close.

**Comment by halkon** [comment]
I don't think @thrawn01 has made any updates to https://github.com/rackerlabs/encore-ui/pull/1184 so I would say for now I'll close it, it's not resolved but perhaps it's a non-issue.  @thrawn01 please re-open if you find relevant still
