### ISSUE TITLE
Link on Basics page does not work 

### ISSUE THREAD

**Issue by kyleondata** [rackerlabs/encore-ui#1183]
In the "No Data to Display" section there is a link that points to the wells documentation.  This like does not work.  

I would also point out that the wording is not as user friendly as it could be.  For example, it requires a user to click on the link in order to know what we are suppose to use. In this case its wells.  I as a user may already know how to use wells (give a div a class called ".wells"). If it simply stated such, while also providing a link if needed, it might save users a little time.

http://rackerlabs.github.io/encore-ui/#/styleguide/basics#no-data

**Comment by TheNando** [comment]
Looks like this line:

https://github.com/rackerlabs/encore-ui/blob/master/demo/styleguide/basics.html#L98

Just needs to be updated to point here:

http://rackerlabs.github.io/encore-ui/#/styles/wells
