### ISSUE TITLE
Deprecate all `.main` properties on page objects

### ISSUE THREAD

**Issue by Droogans** [rackerlabs/encore-ui#1206]
Change this

```js
expect(encore.rxBreadcrumbs.main.names).to.eventually.eql(['Some', 'Breadcrumbs']);
```

to this

```js
expect(encore.rxBreadcrumbs.initialize().names).to.eventually.eql(['Some', 'Breadcrumbs']);
```

It's confusing to see `main` being used over `initialize`, and has caused folks to use `main` inappropriately. It's smarter to always force users to `initialize` everywhere.

### Encore 1.x 
- [ ] Move all `main` functionality to `initialize(undefined)`.
- [ ] Mark all `main` functions as deprecated in jsdoc. Also, `console.warn` users about using it.

### Encore 2.0
- [ ] Delete all `main` functions.

**Comment by CITguy** [comment]
Move to JIRA under "Deprecation" epic.

**Comment by anur2213** [comment]
Related Jira story:
https://jira.rax.io/browse/FRMW-431

**Comment by CITguy** [comment]
Closing, Captured in JIRA
