### ISSUE TITLE
Nav is broken on Safari without flexbox.less

### ISSUE THREAD

**Issue by parlarjb** [rackerlabs/encore-ui#1211]
We recently stopped using our `flexbox.less` in our `mixins.less` (https://github.com/rackerlabs/encore-ui/pull/1181) assuming that browsers didn't need it any more.

Unfortunately, as of the latest release of Safari, this is still necessary. Without it, the nav takes the full width of the screen.

We don't officially support Safari, so we won't do anything _for now_. Let's check back in October, after the next major release of Safari has happened. I suspect that it'll work just fine with that. If not, we can look at putting our `flexbox.less` back in.

**Comment by CITguy** [comment]
Sad :panda_face:

**Comment by bry4n** [comment]
![](https://media.giphy.com/media/OFMqbjX1udkJO/giphy.gif)

**Comment by CITguy** [comment]
FYI: Safari 9.0 works beautifully.

<img width="1265" alt="screen shot 2015-10-14 at 1 41 54 pm" src="https://cloud.githubusercontent.com/assets/545605/10493936/4b2dd958-7279-11e5-817e-3e12cc402c96.png">

**Comment by glynnis** [comment]
@CITguy @parlarjb So do we still need this issue? Seems resolved, so I'm closing, but reopen if needed.

**Comment by CITguy** [comment]
Yeah, nothing to fix, really.
