### ISSUE TITLE
Phone number formatting

### ISSUE THREAD

**Issue by julianbonilla** [rackerlabs/encore-ui#1217]
Has any work been done on phone number formatting in the framework?  Would be good to have something in the Styleguide like the date formatting section (http://rackerlabs.github.io/encore-ui/#/styleguide/basics#date-formatting).

We have filters for formatting phone numbers in at least two projects.

/cc @glynnis

**Comment by glynnis** [comment]
@julianbonilla We're actually coming up against that just now in PhoneUI, so I'm glad you brought it up.

@CITguy could we get this story moved over to JIRA for a future sprint?

@julianbonilla Once the JIRA gets created, could you add links to code/screenshots where the filters are used currently? I know on the design side the first thing we'll want to know is how many different formats (country codes, extensions, etc.) we'll need to account for visually, and then on the dev side which ones already exist as filters that could be adjusted for use at the Framework level.

**Comment by CITguy** [comment]
Closing Issue. Captured in https://jira.rax.io/browse/FRMW-223
