### ISSUE TITLE
rxMisc.currencyToPennies should accept ElementFinder, ElementArrayFinder types

### ISSUE THREAD

**Issue by ccarteronline** [rackerlabs/encore-ui#1234]
It should also accept arrays of text, too.

```js
encore.rxMisc.currencyToPennies(['$1,234', '$2,345.01']);
```

**Comment by Droogans** [comment]
Speaking with @jj4th we decided to drop the element finder params since we'd return promises for some types of calls and immediate values for others.

This should only support arrays of strings that look like currencies.

**Comment by tomreece** [comment]
@ccarteronline @Droogans What should `encore.rxMisc.currencyToPennies(['$1,234', '$2,345.01']);` return?

`[123400, 234501]`? Or should it sum them or something?

**Comment by tomreece** [comment]
We decided to make it return an array of penny values. Sum it yourself! :P

**Comment by CITguy** [comment]
Closed via associated PR.
