### ISSUE TITLE
rxCharacterCount highlighting when input lacks spaces

### ISSUE THREAD

**Issue by ericcarraway** [rackerlabs/encore-ui#1256]
I know this component is still experimental.  Nonetheless, I thought this might be worth documenting.  We are considering using this in `billing-ui`
### Long input with spaces (OK):
![words-ok](https://cloud.githubusercontent.com/assets/6632454/10204618/6c329b0e-6782-11e5-8562-85f0cf679e65.png)

### Long input without spaces:
![one-word](https://cloud.githubusercontent.com/assets/6632454/10204623/7300b13c-6782-11e5-83e2-1b17de110e6d.png)
CC: @kyleondata

**Comment by CITguy** [comment]
@ericcarraway, highlighting with rx-character-count is known to be extremely buggy. See [rxCharacterCount API Docs](http://rackerlabs.github.io/encore-ui/ngdocs/index.html#/api/rxCharacterCount.directive:rxCharacterCount) "Highlighting" section.

**Comment by ericcarraway** [comment]
:+1:

**Comment by anur2213** [comment]
Related Jira story:
https://jira.rax.io/browse/FRMW-430

**Comment by CITguy** [comment]
Closing, Captured in JIRA
