### ISSUE TITLE
rxTable page objects

### ISSUE THREAD

**Issue by jj4th** [rackerlabs/encore-ui#1270]
There is a need for a set of general page objects for accessing tables/table data.  I have created rxTable to fill this need.

I expect there will be a LOT of discussion on this, and it's fairly documented, so I will let the PR speak for itself for now.

**Comment by jj4th** [comment]
Oh yeah, I have not yet constructed demos or midways for this.  They will be forthcoming.

**Comment by glynnis** [comment]
@jj4th Is this still relevant? Looks like the PR was closed, so I'm closing this issue, but re-open if this is still needed.
