### ISSUE TITLE
rxMisc.unless should be renamed to rxMisc.unlessNull

### ISSUE THREAD

**Issue by Droogans** [rackerlabs/encore-ui#1273]
Another issue:

https://github.com/rackerlabs/encore-ui/blob/c333f185c64471b1d965d3fee0728f756230a3e0/src/rxMisc/rxMisc.page.js#L98 says

That line says that `innerFn` is executed on the element's text, which is no longer the case.

The `@example` in the jsdocs for this function provides an up to date example of how `innerFn` is called on the `elem` passed in, not `elem`'s text.

### Encore 1.x 
- [ ] Alias `rxMisc.unless` to point to `rxMisc.unlessNull`.
- [ ] Mark `rxMisc.unless` as deprecated.

### Encore 2.0
- [ ] Delete `rxMisc.unless`.

**Comment by Droogans** [comment]
Let it be known that @tomreece has inspired me to also consider naming this:

 - `rxMisc.parachute`
 - `rxMisc.bungeeCord`
 - `rxMisc.trainingWheels`
 - `rxMisc.lifeJacket`
 - `rxMisc.callThisFunctionOnThisThingIfThisThingIsPresentAndDisplayed`

To that point, I should use this joke as an opportunity to highlight why it returns `text` by default.

> im going to start calling unless() without an innerFn

> since it’s so safe

> `return innerFn === undefined ? text : innerFn(elem);`

> i’ll just use it as my getText

Although Tom was trolling, he makes a good point. You *could* use it that way, but you'd be signaling to others that the content that you're asking from the DOM is variable. It may or may not appear under certain conditions. Using it everywhere would make it impossible for others to know when variable content exists in your application.

The text part is just because 90% of the time I was just asking for the text anyway, with a couple of elements that needed further processing (typically to the text -- lowercasing/uppercasing it, etc.). It was purely to save a couple lines of code for the most common use case.

So, that should also be up to scrutiny during this time as well. Should it return text by default? Is it better to stay un-opinionated and ignore what was my most common use case at the time this was written?

**Comment by anur2213** [comment]
Associated Jira story: https://jira.rax.io/browse/FRMW-517
