### ISSUE TITLE
Prefer use of .click named methods on page objects that expose click functionality.

### ISSUE THREAD

**Issue by Droogans** [rackerlabs/encore-ui#1277]
Before:

```js
breadcrumbs.byPosition(2).visit()
```

After:

```js
breadcrumbs.byPosition(2).click()
```

Although users do "visit" the second breadcrumb, it's entirely too arbitrary to remember how each component names its "click" function. Most users refer to these functions as clicks anyway.

It doesn't provide enough clarity to justify naming it something different.

**Comment by jj4th** [comment]
+1, though I would like to see this implemented with a deprecation path.  Move visit to an alias of click() and put a deprecation notice in the release?  Does encore-ui have a deprecation policy?

**Comment by Droogans** [comment]
Sure. It's really informal but an example would be in https://github.com/rackerlabs/encore-ui/issues/978, which highlights the marking of stuff as going away soon, and later, deleting that stuff.

**Comment by CITguy** [comment]
+1 for standardization!

**Comment by anur2213** [comment]
Associated Jira story: https://jira.rax.io/browse/FRMW-516
