### ISSUE TITLE
Convert all page objects documentation to vanilla jsdoc3

### ISSUE THREAD

**Issue by Droogans** [rackerlabs/encore-ui#1311]
The standard output of jsdoc3 is much nicer than what we've got currently. Use that instead.

Also, stop using `@memberOf` for page object properties, use `@instance` instead. Use `@type` for page object properties.

Almost everything should be an `@instance`, as well.

**Comment by CITguy** [comment]
@Droogans, can you submit a PR to convert one or two existing page objects to give an example of this conversion?

**Comment by Droogans** [comment]
I've been messing around with Phone UI's documentation today and this is what the initial output is looking like.

<img width="1167" alt="screen shot 2015-10-14 at 16 50 30" src="https://cloud.githubusercontent.com/assets/1214609/10499051/b5c3635e-7293-11e5-8496-7aa12f441958.png">

**Comment by bry4n** [comment]
JSDoc3 looks good. I think it is weird to have right sidebar. :no_mouth:  I am pretty sure it can be configured to move sidebar to left.

**Comment by anur2213** [comment]
Associated Jira story: https://jira.rax.io/browse/FRMW-515
