### ISSUE TITLE
Explicitly state in the CSS styleguide that class names should use kebab case.

### ISSUE THREAD

**Issue by ericcarraway** [rackerlabs/encore-ui#1323]
This has come up a couple of times during our team's review process.  Our styleguide _implies_ that CSS class names should use `.kebab-case`, but I couldn't find a place where that is explicitly stated.

Is it worth adding a short sentence or bullet point here?
https://github.com/rackerlabs/encore-ui/blob/master/guides/css-styleguide.md

**Comment by CITguy** [comment]
At the bottom of the CSS Styleguide, there are clear guidelines of how to name CSS classes/selectors.

* If it is an element directive, use `kebab-element-name`
* If it is a class for a directive, use `.lowerCamelCaseElementName`
* If it is an attribute directive, use `[kebab-attribute-name]`

Does this clear up any confusion?

**Comment by CITguy** [comment]
Or are you referring to class naming conventions for items that are NOT directives?

**Comment by ericcarraway** [comment]
Makes sense.  With my limited knowledge of directives, I wouldn't have thought to look there.  Thanks!

**Comment by CITguy** [comment]
There are cases where we have kebab mixed with lowerCamelCase selectors (https://github.com/rackerlabs/encore-ui/blob/master/src/rxCheckbox/rxCheckbox.less#L13) so I believe your concern is still valid, and it would make sense to document **non-directive** class naming conventions.

**Comment by ericcarraway** [comment]
I didn't see your last comment before closing the issue.  Yes, this would be for *non-directive* class naming conventions.

**Comment by anur2213** [comment]
Related Jira story: 

https://jira.rax.io/browse/FRMW-429

**Comment by CITguy** [comment]
Closing, Captured in JIRA
