### ISSUE TITLE
rxCollapse click to expand limited to icon size

### ISSUE THREAD

**Issue by cmartinez1499** [rackerlabs/encore-ui#1387]
Only clicks that are directly on the chevron icon will expand an rxCollapse element.
I suggest expanding this area to fill the entire grey box containing the chevron icon
I have outlined the suggested area in red
![screen shot 2015-11-13 at 2 19 34 pm](https://cloud.githubusercontent.com/assets/1155834/11157200/d4ad31e8-8a15-11e5-8c07-eefa5c1cfb4c.png)

**Comment by glynnis** [comment]
@cmartinez1499 This was moved to our backlog in JIRA as a bug: https://jira.rax.io/browse/FRMW-508

Closing github issue.
