### ISSUE TITLE
FireFox tooltip no show error

### ISSUE THREAD

**Issue by jonkruse00** [rackerlabs/encore-ui#1465]
Currently only on Firefox the tool tips are not showing on hover. 
Expected: 
```
<rx-sortable-column
  sort-method="alarmSortCol(property)"
  sort-property="last_checked_date_raw"
  predicate="alarmSort.predicate"
  reverse="alarmSort.reverse">
  Last Checked
     <span tooltip="Indicates the last time a check ran. It does not necessarily correspond to the time    when the alarm changed state." tooltip-placement="top">
      <i class="fa fa-exclamation-circle"></i>
    </span>
</rx-sortable-column>
```
![original](https://cloud.githubusercontent.com/assets/5339195/11932863/f73643c4-a7bd-11e5-8237-aae65a8e92cf.png)

After some investigation I found that the tooltip attribute if placed higher in the dom will fire on hover in Firefox but when this happens it is no longer centered around the "!" icon. 
```
<rx-sortable-column
  sort-method="alarmSortCol(property)"
  sort-property="last_checked_date_raw"
  predicate="alarmSort.predicate"
  reverse="alarmSort.reverse"
  tooltip="Indicates the last time a check ran. It does not necessarily correspond to the time when the  alarm changed state." tooltip-placement="top">
  Last Checked
      <i class="fa fa-exclamation-circle"></i>
</rx-sortable-column>
```
![screen shot 2015-12-14 at 4 04 39 pm](https://cloud.githubusercontent.com/assets/5339195/11932986/b49c5ffc-a7be-11e5-8977-5ea2a7c350ff.png)

I understand why the tooltip is not centered on the "!" but is the original problem of it not showing because of Firefox or the framework ? And if it is something to do with the Browser is there anything the framework can do ?

**Comment by glynnis** [comment]
JIRA story for this here: https://jira.rax.io/browse/FRMW-561

**Comment by 100stacks** [comment]
@glynnis thanks! :100: 
@jonkruse00 we'll take a look :+1:

On initial review it appears to be a `z-index` issue.

**Comment by glynnis** [comment]
@jonkruse00 Where is this implemented currently? @100stacks and I were taking a look but can't find anything in the docs that's using this icon/tooltip pattern. 

Could you point us to where this has been implemented in staging? That might help us track down what's going on.

**Comment by 100stacks** [comment]
@jonkruse00, I dropped your code snippet into the `tooltips` demo to replicate your issue:
```
<rx-sortable-column
  sort-method="alarmSortCol(property)"
  sort-property="last_checked_date_raw"
  predicate="alarmSort.predicate"
  reverse="alarmSort.reverse">
  Last Checked
     <span tooltip="Indicates the last time a check ran. It does not necessarily correspond to the time    when the alarm changed state." tooltip-placement="top">
      <i class="fa fa-exclamation-circle"></i>
    </span>
</rx-sortable-column>
```

...and the tooltip appears above the `!`.  As @glynnis said, can you help us with a live example? Thanks! 

### FireFox Snapshot 

<img width="1435" alt="screen shot 2015-12-21 at 2 41 14 pm" src="https://cloud.githubusercontent.com/assets/10120600/11940897/34186c4e-a7f1-11e5-8ea2-10fbb95cbd59.png">

### Chrome Snapshot

<img width="1381" alt="screen shot 2015-12-21 at 2 42 19 pm" src="https://cloud.githubusercontent.com/assets/10120600/11940904/442a6f10-a7f1-11e5-8c60-90c754a850d4.png">

**Comment by 100stacks** [comment]
@jonkruse00, this issue may be resolved with the recent `EncoreUI Framework v1.42.0` release.  With https://github.com/rackerlabs/encore-ui/pull/1435, @CITguy @ssalinas24 and I discovered a bug in the original `rxSortableColumn` template, where it extended the `<button>` tag.  FireFox handles events fired from `<button>` conservatively.  

After updating to the current Framework release, please let me know if you continue have this issue.

**Comment by jonkruse00** [comment]
@100stacks Thanks. I will check this out and let you know.

**Comment by 100stacks** [comment]
@jonkruse00 sounds good. Thanks.

**Comment by jonkruse00** [comment]
@100stacks Encore Updated and Bug Fixed. Thanks for the help.

**Comment by 100stacks** [comment]
@jonkruse00, no problem...glad it worked for you. :ok_hand:
