### ISSUE TITLE
typeahead transparency with rx-select

### ISSUE THREAD

**Issue by scadams** [rackerlabs/encore-ui#1492]
As of Encore UI v 1.42.2, I'm getting the following issue with typeahead when rx-selects are below it on a form page:

![image](https://cloud.githubusercontent.com/assets/753260/12251668/53cf595c-b896-11e5-9d14-dfc92f2c62b2.png)

The typeahead dropdown is transparent when it extends over rx-select inputs (but not regular text inputs).

**Comment by glynnis** [comment]
@scadams I've put this in the Framework backlog on JIRA: https://jira.rax.io/browse/FRMW-637.

Leaving this github issue open until resolved.

**Comment by CITguy** [comment]
Closed via #1503

**Comment by scadams** [comment]
Guess this was already closed - but regardless, I confirmed this did fix my issue. Thanks!
