### ISSUE TITLE
Update documentation on unit test methodologies

### ISSUE THREAD

**Issue by klamping** [rackerlabs/encore-ui#150]
Pulling from these discussions with @chriscantu :
https://github.com/rackerlabs/encore-ui/pull/132#discussion_r11314421
https://rackspace.hipchat.com/history/room/459546#13:29:02

We need to document dependency injection vs. mocking in the testing readme. Goals being:
Understand pros/cons of each
Have reference for future discussion/feedback
Have a starting point for unit test improvements in the future.

**Comment by glynnis** [comment]
@Droogans says: Switch to ng-describe and that's goot enough. Closing.
