### ISSUE TITLE
rxDatePicker molecule needs additional functionality

### ISSUE THREAD

**Issue by jj4th** [rackerlabs/encore-ui#1506]
The inability to enter a specific date, either via text or by selecting month and year, negatively impacts the Racker experience and increases the complexity of functional testing on pages that use the date picker.

If I want to select a date some time in the past (say several months) the only option is to repeatedly click the previous month button.  In testing, the process requires repeatedly clicking the previous month button and then checking the text to see if the month and year are correct.  Neither of these are particularly desirable.

Allowing a month and year selection would significantly decrease the number of clicks necessary to access dates in previous months/years.  Allowing masked date entry directly would be ideal from a testing standpoint, but I do not know if the rackers would use it as much.  Simply providing a method for the date-picker to be used with existing date input boxes would help.

@lfielder I was told to tag you on this request.

**Comment by anur2213** [comment]
Related Jira story: https://jira.rax.io/browse/UXENCORE-517

**Comment by 100stacks** [comment]
PR #1619 - `FRMW-681: Add 10-year range to rxDatePicker` captures this issue.

**Comment by 100stacks** [comment]
@jj4th, https://github.com/rackerlabs/encore-ui/pull/1619 updates `rxDatePicker` with a 21-year time span (10 years prior, current year, 10 years after).  Selecting a year other than current year will shift the 21-year time span.  

[`encore-ui v1.47.0`](https://github.com/rackerlabs/encore-ui/releases/tag/v1.47.0) provides the update to `rxDatePicker`.
