### ISSUE TITLE
multi-select transparency with checkbox

### ISSUE THREAD

**Issue by scadams** [rackerlabs/encore-ui#1508]
I found another minor transparency issue with multi-select drop-downs in front of checkboxes:

![image](https://cloud.githubusercontent.com/assets/753260/12487834/8b8c964e-c02e-11e5-954c-97617acbde85.png)

![image](https://cloud.githubusercontent.com/assets/753260/12487805/71f88b0c-c02e-11e5-90da-21d904bfd9bf.png)

**Comment by CITguy** [comment]
Related JIRA story: https://jira.rax.io/browse/FRMW-641

**Comment by 100stacks** [comment]
@scadams, we resolved the `rxMultiSelect` `z-index` issue with https://github.com/rackerlabs/encore-ui/pull/1594 by removing `rxSelect` strict dependencies from `rxMultiSelect`.

[`encore-ui v1.46.1`](https://github.com/rackerlabs/encore-ui/releases/tag/v1.46.1) release contains the fix.
