### ISSUE TITLE
Remove Angular UI Bootstrap dependency

### ISSUE THREAD

**Issue by TheNando** [rackerlabs/encore-ui#1600]
The version of Angular UI Bootstrap the framework depends on is 23 versions behind. The few components that we use in this version are primitive compared to modern libraries' features. We should come up with a plan to locate which of the components we use from this library and bring in replacements (either from updated versions of this lib, from other libs, or home grown if we have the need/time) using our framework conventions. Once we have framework based components, we can deprecate and remove this dependency. This should help reduce the number of Encore apps pulling in 3rd party deps to compensate for lacking features.
- [x] Identity Angular UI Bootstrap components in use by the framework
- [ ] Identify 3rd part components used in other apps
- [ ] Create issues for each of the components to add directly to the framework (pulled from other OS projects or home grown)
- [ ] Remove the dependency

JIRA: https://jira.rax.io/browse/FRMW-741

**Comment by Droogans** [comment]
`typeahead` is going to be intensive.

**Comment by CITguy** [comment]
Bootstrap Components Used:

* modals (Components > rxModalAction)
* progressbar (Molecules > Progress Bars)
* tabs (Components > tabs)
* tooltips (Components > tooltips)
* typeahead (Components > typeahead)

**Comment by 100stacks** [comment]
Possible addition to our current deprecation list - https://jira.rax.io/browse/FRMW-740.

**Comment by CITguy** [comment]
@Droogans: I'm wondering if we can get away with using [`<datalist>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist).

@100stacks: These would likely be 3.0 removals, so I'd like to refrain from bundling with 2.0 release.

**Comment by CITguy** [comment]
JIRA: https://jira.rax.io/browse/FRMW-741

**Comment by Droogans** [comment]
Wait, doesn't [the MIT License](https://github.com/angular-ui/bootstrap/blob/master/LICENSE) say that we can copy/paste the codebase into ours, granted that we credit them using the MIT license?

I think it makes more sense to take the absolute latest version of all these bootstrap components, copy them in, and then begin modifying it as our own code from here on out.

Sounds a little strange, but it has to be better than us depending on bootstrap as a dependency, or re-writing it all from scratch.

**Comment by CITguy** [comment]
@Droogans: some items, I think we could do that, yes. Others are so simple (progressbars) that we can implement them with little effort.

**Comment by 100stacks** [comment]
@CITguy, one suggestion is that we still mark them for deprecation with the 2.0 release, and remove them in the 3.0 release.

**Comment by CITguy** [comment]
Let's continue the conversation in JIRA, though.

**Comment by CITguy** [comment]
Closing this issue. Angular UI Bootstap will be removed in the 5.0.0 release.
