### ISSUE TITLE
Update Modal page objects to utilize browser.wait

### ISSUE THREAD

**Issue by vlutton** [rackerlabs/encore-ui#1685]
Details:
- Framework Version: 2.0.0-6

Modals are creating a race condition when writing tests, causing the next assertion to fire before the modal animation is complete.  

After working on this with @Droogans , we have determined that we need to update the page objects to use a browser.wait when performing modal actions, here is an example of an implementation of this:

```js
    close: {
        value: function () {
            var EC = protractor.ExpectedConditions;
            this.rootElement.$('.modal-close').click();
            browser.wait(EC.stalenessOf(this.rootElement));
        }
    },

    cancel: {
        value: function () {
            var EC = protractor.ExpectedConditions;
            this.btnCancel.click();
            browser.wait(EC.stalenessOf(this.rootElement));
        }
    }
```

**Comment by Droogans** [comment]
https://jira.rax.io/browse/FRMW-899: "rx-page-objects -- Compensate for sleep timeouts when closing modals"

**Comment by Droogans** [comment]
This got merged into 2.x, so it won't show up as closed until 2.x is on master.

I'm closing this now because this was reported against a 2.x release.
