### ISSUE TITLE
RxPaginate should have isDisplayed method in its page object

### ISSUE THREAD

**Issue by vlutton** [rackerlabs/encore-ui#1720]
Encore Version: 2.0.0-8

@CITguy asked me if I could open this issue as this is a very common test that we do and would be nice to have in the page objects.

**Comment by CITguy** [comment]
FYI: We want to change this...

```
encore.rxPaginate.initialize($('.rx-paginate')).rootElement.isDisplayed()
```

to this...

```
encore.rxPaginate.initialize($('.rx-paginate')).isDisplayed()
```
