### ISSUE TITLE
rxSortUtil.sortCol not supporting multiple tables in one scope

### ISSUE THREAD

**Issue by halkon** [rackerlabs/encore-ui#175]
When implementing the payment options I had to list out two tables and implement sorting with it.  Due to the default behavior of rxSortUtil.sortCol I was unable to do this (one table essentially would sort the other).

My solution was to create my own sortCol function where I would pass some sort ID that would be specific to that table, and from it generate the sortCol function to be used for that table. 

```
function (sort) {
    return function (predicate) {
        var reverse = ($scope[sort].predicate === predicate) ? !$scope[sort].reverse : false;
        $scope[sort] = { reverse: reverse, predicate: predicate };
    };
}
```

May not be the best solution, or the right one, but just wanted to point this out

**Comment by glynnis** [comment]
@TheNando @halkon Is this still relevant?

**Comment by halkon** [comment]
@glynnis I think it's something that needs to be documented at this point, #1097 pinpoints the main issue, as it could use some TLC. 

We can close it, but can we add a story in JIRA to document it, it is of low importance but some other project could have the same issue that I had originally

**Comment by anur2213** [comment]
Related Jira story:
https://jira.rax.io/browse/FRMW-460
