### ISSUE TITLE
Page in Documents that reference the current Icon Set

### ISSUE THREAD

**Issue by jonkruse00** [rackerlabs/encore-ui#1751]
I believe we are using a subset of font-awesome icons. It would be nice to have a page in the docs that list all icons available in our sub-set.

**Comment by glynnis** [comment]
@jonkruse00 We have http://rackerlabs.github.io/encore-ui/#/elements/Links#action-link-icons

If that doesn't address what you'd like to see reflected, could you elaborate on what else you'd like to see there?

**Comment by jonkruse00** [comment]
I'm developing something for djinn and put a random icon in the project. The `fa-flask` worked but others failed to load. I guess in the end it doesn't have to be a new page of just icons but maybe the current font-awesome version for reference.

**Comment by 100stacks** [comment]
@glynnis, do you know if this story is still applicable https://jira.rax.io/browse/FRMW-686?

It is a story to move the list of icons and their usage under  `Styleguide` -> `Iconography` rather than `Elements` -> `Links`.

**Comment by glynnis** [comment]
@100stacks I think that story is still relevant, yes.

**Comment by 100stacks** [comment]
@glynnis @jonkruse00: Maybe this will help people find the icons and their usage once it's moved.  👍 💯

**Comment by CITguy** [comment]
Closing story. Will be addressed in 4.x documentation updates.
