### ISSUE TITLE
rxActionMenu doesn't have isPresent functionality

### ISSUE THREAD

**Issue by sharkySharks** [rackerlabs/encore-ui#1764]
`rxActionMenu` does not have a clean way of testing whether the action cog is present or not. 

In Billing UI we have a variety of cases where action cogs are displayed or not displayed depending on status (active/canceled) or permissions.

Right now we do something like: 
`expect(actionMenu.rootElement.isPresent()).to.eventually.be.true;`

It would be nice to not expose the private `rootElement` method, and instead do:
`expect(actionMenu.isPresent()).to.eventually.be.true;`

**Comment by CITguy** [comment]
This will be fixed in the 2.2.0 release on August 31.

**Comment by CITguy** [comment]
@sharkySharks: This has been released in `rx-page-objects 2.2.0` as verified by http://rackerlabs.github.io/encore-ui/rx-page-objects/rxActionMenu.html#isPresent
