### ISSUE TITLE
rxAge filter doesn't handle very small time differences properly.

### ISSUE THREAD

**Issue by jj4th** [rackerlabs/encore-ui#1767]
**Observed with:**
`Encore UI: 1.45.0` + `Moment: 2.5.1` AND
`Encore-UI: master` + `Moment: 1.13.0`

**Steps to recreate:**
- Invoke rxAge filter with `new Date();` or a date within a few milliseconds of the current date.

**Result:**
rxAge returns an improper date, typically `1 minute, -22 hours`

This happens because of the behavior of the line: https://github.com/rackerlabs/encore-ui/blob/master/src/utilities/rxAge/scripts/rxAge.js#L76

```javascript
var days = parseInt(duration.asDays(), 10);
```

Here is the example node console output using very small duration values with the current version of moment to demonstrate the behavior that causes this error:
![screen shot 2016-08-11 at 6 05 34 pm](https://cloud.githubusercontent.com/assets/1107895/17607977/fba83a22-5fee-11e6-8ca9-6ede1b116bb1.png)

**Comment by jj4th** [comment]
It is worth noting that `moment.duration` generates a float, not a string, so `parseInt` is probably wrong here.

**Comment by CITguy** [comment]
The issue is that `moment.duration(...).asDays()`, `.asHours()`, and `.asMinutes()` are returning an exponent for small values and `parseInt()` is interpreting the value incorrectly.

So consider the following:

```javascript
var d = moment.duration(1);
d.asDays(); // 1.1574074074074074e-8
parseInt(d.asDays()); // 1 (incorrect)
```

**Comment by CITguy** [comment]
Captured in JIRA: https://jira.rax.io/browse/FRMW-1000
