### ISSUE TITLE
In documentation, there is additional spacing after table entries

### ISSUE THREAD

**Issue by cgtaab** [rackerlabs/encore-ui#1816]
In the automatically generated documentation, there appears to be additional spacing after table entries, as seen in
<img width="424" alt="screenshot 2016-09-22 10 54 53" src="https://cloud.githubusercontent.com/assets/1242514/18754711/9dae616e-80b7-11e6-885f-579efa05bfff.png">

I'd expect to see equal spacing before and after table entries.

**Comment by CITguy** [comment]
For reference, we should be able to apply additional styles via https://github.com/m7r/grunt-ngdocs#styles  The spacing seen in the graphic is from the `<p>` element styling coming from bootstrap styles, so we'd need to have an override to remove the bottom padding for the last paragraph in a table cell.

**Comment by CITguy** [comment]
Closing. This is not a high value priority.
