### ISSUE TITLE
Documentation: Permissions-related design element for using invalid links and tool tips together

### ISSUE THREAD

**Issue by ErnieAtLYD** [rackerlabs/encore-ui#1818]
The developers who work on the billing component of encore are **introducing a design pattern** to show if a link is usually available, but can not be implemented because a user does not have permissions. Right now the design pattern is to make the link visible, and the team gets a minimum of one e-mail a link of people thinking the app has a bug, when they just do not having the permissions.

For inline functions, the link will be grayed out:
![eod-1710-000](https://cloud.githubusercontent.com/assets/33945/18758045/4e58eafa-80c4-11e6-90dc-4ef420f4c542.png)

With a tooltip:
![eod-1710-001](https://cloud.githubusercontent.com/assets/33945/18758051/524a3a7e-80c4-11e6-94f5-39d8ef060701.png)

Also note that this would [also apply to page action style links](http://rackerlabs.github.io/encore-ui/#/elements/Links). Provided that this is something that people won't freak out over, I'll go ahead and submit a pull request making note of this inside the documentation.

**Comment by CITguy** [comment]
Closing. This can be achieved with existing functionality.
