### ISSUE TITLE
Specify valid date range for rxDatePicker

### ISSUE THREAD

**Issue by megalord** [rackerlabs/encore-ui#1827]
The date picker always show +/- 10 years and all 12 months.  However, sometimes the user should be restricted on what dates they are allowed to select.  Two separate examples:
1) Time series data with a TTL of 13 months - users should not be able to select anything older or anything in the future.
2) Scheduling a job - any date in the past is invalid

It would be nice to specify a start and end day for the date picker so that the month and year dropdowns only show relevant months and years for the specified range.  Also, invalid days of a valid month should be un-clickable, just like "outOfMonth" days are currently.

**Comment by CITguy** [comment]
Moved to JIRA: https://jira.rax.io/browse/FRMW-1046

**Comment by CITguy** [comment]
Let's continue discussion in the JIRA story.

Closing.
