### ISSUE TITLE
rxModalAction ng-Disabled fails to disable 

### ISSUE THREAD

**Issue by jonkruse00** [rackerlabs/encore-ui#1842]
So 2 things: 
1.  `a .modal-link` does not inherit `disabled="disabled"`
2.  `modal-link` is not disabled

Current version: `"encore-ui": "1.50.2"`
My html: 

```
<rx-modal-action 
    classes="button sm djinn-prefab-btn"
    ng-disabled="true"
    pre-hook="preHookPrefabs()"
    controller="DjinnPrefabModalCtrl" 
    template-url="components/common/djinn/rxDjinnPrefab/djinnPrefabModal.html" 
    disable-esc>
        Djinn prefabs
</rx-modal-action>
```

On the Dom `disabled="disabled"` appears on `rx-moda-action` but not on `a.modal-link` 

And from what I see on [Disabled Modal Documentation](http://rackerlabs.github.io/encore-ui/#/elements/Modals) both are supposed to have this `disabled = "disabled"`. 

I went ahead and added this attribute via console and I get the correct css but the `a.modal-link` is still active. 
![screen shot 2016-10-10 at 3 26 35 pm](https://cloud.githubusercontent.com/assets/5339195/19250033/f83d3660-8efd-11e6-9e8b-e64e99d47582.png)

If you need anymore information from me just let me know.

**Comment by CITguy** [comment]
Version 1.50.x doesn't support ng-disabled on rxModalAction. Documentation is for latest version of the framework. Please check the table at https://github.com/rackerlabs/encore-ui/wiki/3.0-Migration-Guide#ngdisabled-for-disabling for which attribute to use.

**Comment by jonkruse00** [comment]
Oh ok. Thank you for you help. I don't know if i close this or you...
