### ISSUE TITLE
New Feature Searchable Dropdown 

### ISSUE THREAD

**Issue by jonkruse00** [rackerlabs/encore-ui#1844]
When handling large lists of data in a select dropdown then a built in search bar would be fantastic. 

Example: https://select2.github.io/examples.html

**Comment by CITguy** [comment]
@ElementE and @lfielder should be aware of this request to get their design on.

**Comment by Droogans** [comment]
Does the typeahead cover this use case?

**Comment by CITguy** [comment]
@Droogans: not quite, typeahead only works on plain text fields and doesn't provide a way to browse available values.

**Comment by CITguy** [comment]
Closing, due to inactivity.
