### ISSUE TITLE
White background appears on responsive screen widths

### ISSUE THREAD

**Issue by arc6789** [rackerlabs/encore-ui#1954]
<img width="646" alt="screen shot 2017-03-08 at 11 31 21 am" src="https://cloud.githubusercontent.com/assets/8885849/23725967/25ed5f2e-0418-11e7-969e-0527d7e8393d.png">

Billing UI Issue: 

When UI gets smaller to about 780 pixels or below a white background begins to appear behind the grey background.

This is because `.rx-app` parent class has a grey background set to it and the width does not expand 100% at smaller screen size.

<img width="1377" alt="screen shot 2017-03-08 at 4 07 12 pm" src="https://cloud.githubusercontent.com/assets/8885849/23726285/55f8d4f4-0419-11e7-9b6c-df28264e606b.png">
<img width="773" alt="screen shot 2017-03-08 at 4 07 44 pm" src="https://cloud.githubusercontent.com/assets/8885849/23726307/68ab55fe-0419-11e7-8740-20522f2c6a0f.png">

It would be a better idea to remove that grey and add it to the child element it directly applies to which is`.rx-app-content`. For ex. as shown below:

<img width="1353" alt="screen shot 2017-03-08 at 4 11 33 pm" src="https://cloud.githubusercontent.com/assets/8885849/23726440/f781ecf2-0419-11e7-8b74-79cc8c6b4929.png">
<img width="790" alt="screen shot 2017-03-08 at 4 12 39 pm" src="https://cloud.githubusercontent.com/assets/8885849/23726513/19affba2-041a-11e7-8cf4-eff53f8a98ad.png">

This is a change that can be done within Billing stylesheets to overide if it cannot be done on a framework level because it affects other UIs as well.

**Comment by CITguy** [comment]
This is totally correctable. Thanks for the suggestion!

**Comment by CITguy** [comment]
Captured in JIRA: https://jira.rax.io/browse/FRMW-1310
