### ISSUE TITLE
add performance testing for components

### ISSUE THREAD

**Issue by klamping** [rackerlabs/encore-ui#203]
Encore-UI has reached a point where some performance testing of the JS could be added to find potential bottlenecks. It would be nice to add monitoring to these performance tests, so we can track performance over time.

**Comment by glynnis** [comment]
@Droogans sez: Like the idea of testing this, maybe don't use Batarang. Adding hackday label.

**Comment by glynnis** [comment]
@CITguy is this still relevant?

**Comment by CITguy** [comment]
Maybe, but performance of framework items has not been an issue.

**Comment by CITguy** [comment]
We'll open a JIRA story if teams start complaining about performance.
