### ISSUE TITLE
Add table filtering directive

### ISSUE THREAD

**Issue by klamping** [rackerlabs/encore-ui#209]
![image](https://cloud.githubusercontent.com/assets/706039/2864809/1a186cee-d215-11e3-9197-b8c320c27d15.png)

**Comment by glynnis** [comment]
This is still relevant! But it looks different now, so pull me in for this and I can provide the newer design.

**Comment by glynnis** [comment]
@parlarjb is planning on doing this work as part of moving Batch Actions work from Cloud to the Framework.

**Comment by glynnis** [comment]
Closing this to open a fresh issue where I can attach a design.
