### ISSUE TITLE
Define a common font icon set

### ISSUE THREAD

**Issue by klamping** [rackerlabs/encore-ui#211]
Standardizing on a font icon set would make implementing icons a lot easier for apps. However, file size considerations need to be weighed, as some font icon sets can cost ~350kb to download.

**Comment by glynnis** [comment]
@parlarjb Didn't we ship Font Awesome recently with the Framework? Is that documented somehow in the demo/styleguide at all? If not, let's make a new issue and I'll try and work it in.

**Comment by glynnis** [comment]
Font Awesome is being shipped with the Framework, so closing this as it's already done.
