### ISSUE TITLE
Add divider style to rxModal

### ISSUE THREAD

**Issue by klamping** [rackerlabs/encore-ui#213]
![image](https://cloud.githubusercontent.com/assets/706039/2865400/45aa418c-d21c-11e3-8969-315dd4884ef9.png)

**Comment by glynnis** [comment]
@parlarjb Do you understand what this is about? I can't really tell just from the screenshot.

If you don't, let's close this.

**Comment by parlarjb** [comment]
I'm going to *guess* that we don't have a way to put horizontal dividers in? Let's just close it though, and do a new one if someone requests this
