### ISSUE TITLE
Add 'x' component to tables

### ISSUE THREAD

**Issue by klamping** [rackerlabs/encore-ui#214]
Create an 'x' style for tables so that there can be a common 'delete row' UX.

![image](https://cloud.githubusercontent.com/assets/706039/2865496/0c83695a-d21d-11e3-8c6c-2980e52d2bf5.png)

**Comment by glynnis** [comment]
See https://jira.rax.io/browse/UXENCORE-142 and https://jira.rax.io/browse/UXENCORE-78

**Comment by glynnis** [comment]
Also see https://github.com/rackerlabs/encore-cloud-ui/pull/445 -- X's are part of the "Create Load Balancer" parent/child table, and we should draw on them as source of truth for design/visual style.

**Comment by glynnis** [comment]
Closing: this should be set up as individual JIRAs for projects, not as a Framework concern.
