### ISSUE TITLE
Create 'tags' component

### ISSUE THREAD

**Issue by klamping** [rackerlabs/encore-ui#216]
![image](https://cloud.githubusercontent.com/assets/706039/2865516/5d216e16-d21d-11e3-926a-126abbcdbe4a.png)

**Comment by CITguy** [comment]
basic prototype at http://jsbin.com/kusuze/32

**Comment by glynnis** [comment]
@halkon @nickburns2006 We wanted your input on this, since there are some tags in TQ already.

**Comment by halkon** [comment]
@glynnis we have both tag and tag cloud.

```
<div class="rx-tag" ng-class="tagType">
    <span class="label" ng-class="{'no-close': !closeable}" ng-transclude>
    </span>
    <button ng-if="closeable" ng-click="closeTag()" class="tag-close">
        <i class="fa fa-times"></i>
    </button>
</div>
```

Closable button and types, @CITguy if you want I can create a PR and dump some code on encore ui and go from there? I'd love to at least get the `rx-tag` out there, the `rx-tag-cloud` can be a separate PR

**Comment by halkon** [comment]
and just totally saw the implementation you did @CITguy.  We could probably pick the best of both worlds and implementations (Though truthfully, look really similar):

https://github.com/rackerlabs/encore-tq-ui/blob/master/app/scripts/directives/rx-tag.js
https://github.com/rackerlabs/encore-tq-ui/blob/master/app/scripts/directives/rx-tagCloud.js

**Comment by glynnis** [comment]
Also see https://github.com/rackerlabs/encore-ui/issues/518 for more history/context.

**Comment by glynnis** [comment]
FYI this work is also being racked here: https://jira.rax.io/browse/UXENCORE-225

**Comment by glynnis** [comment]
Gonna close this and open a new issue for tags, since look/feel/requirements are a little different now. Don't want folks to get confused.
