### ISSUE TITLE
Create 'Expand/Collapse' component for sections of content

### ISSUE THREAD

**Issue by klamping** [rackerlabs/encore-ui#218]
![image](https://cloud.githubusercontent.com/assets/706039/2865548/b45227ac-d21d-11e3-92cc-cc76e499a5c8.png)

This is seen in the modal window, but it should be available outside of it as well.

**Comment by glynnis** [comment]
Some work on this has been done within a parent/child table context here, which may be handy in terms of referring to existing design/visual patterns for this:
https://github.com/rackerlabs/encore-cloud-ui/pull/445

**Comment by glynnis** [comment]
Closing this, see https://github.com/rackerlabs/encore-ui/issues/824
