### ISSUE TITLE
Begin documenting design decisions

### ISSUE THREAD

**Issue by klamping** [rackerlabs/encore-ui#235]
Encore-UI should have an open history of the design/architectural decisions made for the project. Some examples include things like:
- [x] Why we decided not to use Twitter Bootstrap
- [x] Why we haven't switched to Gulp
- [x] How tasks are prioritized
- [x] How it's decided to release a new version
- [x] What constitutes a 'breaking change' 

These decisions should be documented inside of Markdown files, for easy creation/consumption.

**Comment by glynnis** [comment]
@parlarjb I think this is still super relevant, as I don't think any of this made it into our recent changes/creation of the Style Guide (which is more visually oriented). Seems like some of this might be good to put on the homepage (http://rackerlabs.github.io/encore-ui/#/overview).

**Comment by parlarjb** [comment]
Agreed. We've been hearing these questions a lot recently

**Comment by chriscantu** [comment]
:+1:

**Comment by glynnis** [comment]
Got a branch going for this here: https://github.com/rackerlabs/encore-ui/tree/documenting-process

I'll need Jay + others' input before other areas in the task list above can be completed.
