### ISSUE TITLE
rxForm: Labels don't take up entire height w/ multiple lines

### ISSUE THREAD

**Issue by klamping** [rackerlabs/encore-ui#249]
![image](https://cloud.githubusercontent.com/assets/706039/2964305/e3757730-dae4-11e3-888b-1e1fcb61783d.png)

In the screenshot, the green background indicates what part of the row can be clicked by the label. As you can see, this label doesn't cover the entire row height. This needs to be fixed so that a user can click anywhere on the row and select it.

**Comment by glynnis** [comment]
@parlarjb Still relevant?

**Comment by parlarjb** [comment]
I think so
