### ISSUE TITLE
Improve documentation on how each component should be used

### ISSUE THREAD

**Issue by klamping** [rackerlabs/encore-ui#276]
Add some clarity on plumbing vs. fixture (what's meant to be used by an app vs. just used by other components)
  - Provide more clarity on what each component contains
  - Provide more definition on each sub-component

**Comment by glynnis** [comment]
@parlarjb Was this accomplished by any of the recent additions (like the Style Guide) to the Framework, or do you think this is still relevant?

**Comment by parlarjb** [comment]
Bits and pieces, but nothing consistent. Let's leave this as a reminder that we need to take time to look through the component docs.

**Comment by glynnis** [comment]
Closing. This is an ongoing maintenance issue.
