### ISSUE TITLE
Expose sub-components in documentation

### ISSUE THREAD

**Issue by klamping** [rackerlabs/encore-ui#282]
It would be helpful to get a better overall view of a component if the sub-components were exposed in the documentation. For example, including the sub-components in nav menu for specific components

Some examples:
rxApp
- Arrow styles
- rxPage
- rxAppNavItem
- etc
rxNotify
 - what parts are directives and what parts are services

**Comment by glynnis** [comment]
Ongoing maintenance issue. Closing this.
