### ISSUE TITLE
Create/document common url fragmentation solution for easier links

### ISSUE THREAD

**Issue by klamping** [rackerlabs/encore-ui#295]
via @chriscantu 
> Fragmention is the ability to link to certain part of a web page that contains the specified text.  This feature makes sense where the page is very content driven.  

> I thought our single ticket view and editing could benefit from a fragmention ability.  Techs could pass links to a specific section inside a very long comment.  

> http://indiewebcamp.com/fragmention

**Comment by glynnis** [comment]
@parlarjb says: not relevant on the whole, re-open if we run into a specific need for this.
