### ISSUE TITLE
Document the best way to test a new EncoreUI feature in an app

### ISSUE THREAD

**Issue by klamping** [rackerlabs/encore-ui#296]
There is some documentation on using bower to do this, but it's sparse (and not necessarily the easiest way). More documentation should be created to step through different ways to have a local app point to a local copy of encore-ui.

**Comment by glynnis** [comment]
@parlarjb @Droogans Get on this!

**Comment by glynnis** [comment]
@velveteer `bower link` should be part of this?

**Comment by anur2213** [comment]
Associated Jira story: https://jira.rax.io/browse/FRMW-532
