### ISSUE TITLE
Page Objects/Midways for rxFormItem

### ISSUE THREAD

**Issue by Droogans** [rackerlabs/encore-ui#324]
It should:

 - allow for a generic `setValue(value)` function that:
  - will auto-discover if it is a type text or select, and set the value accordingly.
 - support inspecting these properties:
  - `label`, `suffix`, `prefix`, and `description`
 - expose the elements themselves for each of the above properties

All users of the page object will be responsible for manipulating any special properties found in the `suffix`, etc. in their application.

**Comment by glynnis** [comment]
@Droogans DONE!
