### ISSUE TITLE
Page Objects/Midways for rxOptionTable

### ISSUE THREAD

**Issue by Droogans** [rackerlabs/encore-ui#327]
It should:

 - accept the entire table element as `rootElement`.
 - expose a table containing:
  - `columns` (all), `column(columnName)`
  - `rows` (all), `row(rowNumber)`
 - Columns contain:
  - `data()`, `name()`, `position()`, `elements()`
 - Rows contain:
  - a `key:element` pair for each column, where `key` is the column name
   - `key` is a verbatim match to the column's text heading
   - users of the table will be responsible for transforming `element` into useful data
  - the ability to `check()` themselves, and `uncheck()` themselves.
  - the ability to report a `isChecked()` status

**Comment by glynnis** [comment]
@Droogans done son!
