### ISSUE TITLE
Page Objects/Midways for typeahead

### ISSUE THREAD

**Issue by Droogans** [rackerlabs/encore-ui#332]
It should:

 - Be implemented inside of other page objects by users (plays nice with others)
 - Accept the element that implements typeahead
 - Expose `isDisplayed()`, `matches`
 - `matches` iterates, each `match` supports:
  -  `element()`, `position()`, `text()`, `hover()`, `isSelected()`, `select()`

The `match` object functionality is for internal testing purposes only.

**Comment by glynnis** [comment]
Only a few use cases exist for this. Closing until there's a specific need.
