### ISSUE TITLE
Implement Encore-UI Template for Styleguide

### ISSUE THREAD

**Issue by klamping** [rackerlabs/encore-ui#341]
The current styleguide doesn't look too great. The top nav bar can't handle this many components and the comments are messed up:

![image](https://cloud.githubusercontent.com/assets/706039/3275512/4e35a454-f33c-11e3-8d0c-c35b3a249189.png)

It would be nice to re-work the nav so you don't have to click twice to get to the various files, but still have the different components as various pages.

**Comment by glynnis** [comment]
The wicked styleguide is dead! :rainbow: :crystal_ball:
