### ISSUE TITLE
Styledocco should load images used by CSS

### ISSUE THREAD

**Issue by klamping** [rackerlabs/encore-ui#362]
Images are not being loaded properly in the styleguide:
![image](https://cloud.githubusercontent.com/assets/706039/3364650/3a0d6adc-fb22-11e3-8db9-f64ae163e568.png)
![image](https://cloud.githubusercontent.com/assets/706039/3364652/40c926b8-fb22-11e3-81aa-0ad51ed32b43.png)

https://github.com/rackerlabs/encore-ui/pull/361/files#r14101971

See https://github.com/indieisaconcept/grunt-styleguide/issues/23 for a starting point.

**Comment by glynnis** [comment]
Closing this since StyleDocco is DEAD \o/
