### ISSUE TITLE
New Modal Treatments

### ISSUE THREAD

**Issue by klamping** [rackerlabs/encore-ui#430]
Define and built out various modal form flows to incorporate into Encore-UI (in addition to rxModalAction). These include:

- One common behavior of modals (closing/display/etc) given status of functionality within it (API calls/actions/promises)
- Functionally be able to control the modal and when to close it (whether controlled by the resolution of a given promise, or controlled directly)
- Notifications for within the modal and the page. (Should the modal define it's own notifications, or should it be included in rxModalForm)
- Should we have the ability to control buttons? (modify rxModalForm)

https://github.com/rackerlabs/encore-ui/tree/rx-modal-action-util
https://github.com/rackerlabs/encore-ui/pull/419

**Comment by glynnis** [comment]
@parlarjb Do you think this issue is still relevant? I ask since this may fall under Nordquist's purview and/or there may be a big UI overhaul coming down the road at some point in 2015 that includes modals.

**Comment by parlarjb** [comment]
Let's close this one down. I think you're right, it sounds like something that will be overhauled anyway.
