### ISSUE TITLE
Store menu data in LocalStorage for quicker load times

### ISSUE THREAD

**Issue by klamping** [rackerlabs/encore-ui#515]
After the first download of the menu json, store the data so that it can be instantly retrieved on page load. The normal CDN retrieval happens behind the scenes and the nav will be updated after load. 

Benefits:
- Can dev locally w/o waiting on CDN
- Avoid blank menu while data is loading

**Comment by nickburns2006** [comment]
I've seen the menu not load for my local, but ticketing just had a report of a user experiencing a blank nav. So definitely :+1:

**Comment by glynnis** [comment]
@parlarjb Still relevant!
