### ISSUE TITLE
Tags and Tag Clouds support

### ISSUE THREAD

**Issue by hussamd** [rackerlabs/encore-ui#518]
It would be nice to have a tag and tag cloud component available that is not very heavy (i.e. if one has 100s of them per page the UI is not bogged down by the amount of bindings - perhaps we need to go to 1.3 for this already!)

The request stems from the need for showing tags at the bottom of a note that has been added to an account. The tags would be short words such as `unpaid` `billing` `delinquent` etc. The styles can be anything at this point since we do not have mock-ups for these (the styles from GitHub's `` tags can be used), or ones similar to what mint.com has as shown below.

It would also be necessary to allow clicking the tag (and perhaps showing a small 'x' to indicate that it is deletable) to delete/remove it which would result in a back-end callback.

![image](https://cloud.githubusercontent.com/assets/5025474/4188848/c4cba856-3776-11e4-90d8-4dd84a7a4f76.png)

**Comment by CITguy** [comment]
I'm not sure of the necessity of this new tag, but I've got a working prototype at http://jsbin.com/kusuze
