### ISSUE TITLE
Better documentation for our grunt system

### ISSUE THREAD

**Issue by parlarjb** [rackerlabs/encore-ui#577]
Let's put a lot more comments into our `build.js` and other "key" grunt tasks to help people understand what's going on. It's not immediately obvious unless you already have a strong understanding of grunt.

**Comment by glynnis** [comment]
Ongoing maintenance thing, but still relevant.

**Comment by glynnis** [comment]
@Droogans @CITguy @parlarjb Can confer on this. Needs more input.

**Comment by glynnis** [comment]
Since this is high effort, old, and "need more input", I'm closing. @parlarjb @CITguy @Droogans Feel free to create a new issue in the Framework JIRA if this is still relevant.
