### ISSUE TITLE
Notice: Angular 1.3.0 released

### ISSUE THREAD

**Issue by Droogans** [rackerlabs/encore-ui#580]
This is pretty much old news by now, but it shipped [4 days ago](https://github.com/angular/angular.js/releases/tag/v1.3.0).

This is here mainly to be a point of discussion about how to start doing this, and also to serve as a reminder that this milestone can be started.

**Comment by CITguy** [comment]
So, I've been playing around with updating to angular 1.3.3 (as a starting point).  Everything is going mostly well, but I thought I'd share my findings.

* (known) A 1.2.x workaround for rxFormOptionTable needs reworked to function properly in 1.3.x
* `chieffancypants/angular-hotkeys#~1.4.5` (latest) is updatable and can remove an [unnecessary production dependency](https://github.com/chieffancypants/angular-hotkeys/issues/72) (`mousetrap`)
* `sinon` needs added as a `devDependency` in `package.json` for tests to run properly
* The `angular-bootstrap` bower component only supports `1.2.x` and theres a sizeable [backlog](https://github.com/angular-ui/bootstrap/issues?q=is%3Aopen+is%3Aissue+label%3A%22AngularJS+1.3%22) of 1.3.x work on the project before they update the bower component.  

#### angular-bootstrap
We currently use this library for `rxModalAction`, `tabs`, `tooltips`, and `typeahead`.  Of these components, `rxModalAction` is the only one showing problems. 

It throws the following error in the console if you press <kbd>ESC</kbd> to close the modal.
```
Error: [$rootScope:inprog] $digest already in progress
http://errors.angularjs.org/1.3.3/$rootScope/inprog?p0=%24digest
    at REGEX_STRING_REGEXP (angular.js:63)
    at beginPhase (angular.js:14557)
    at Scope.$get.Scope.$apply (angular.js:14301)
    at HTMLInputElement.<anonymous> (angular.js:20918)
    at HTMLInputElement.eventHandler (angular.js:2990)
    at link.focusLink (encore-ui-tpls-1.6.3.js:2885)
    at processQueue (angular.js:12988)
    at angular.js:13004
    at Scope.$get.Scope.$eval (angular.js:14204)
    at Scope.$get.Scope.$digest (angular.js:14020)
```

... to be continued.

**Comment by CITguy** [comment]
Since my last comment, we've also added the `progressbar` directive from `angular-bootstrap`.

**Comment by CITguy** [comment]
As of three days ago (May 2, 2015) angular bootstrap 0.13.0 now has support for Angular 1.3. Per wording on their site:


> AngularJS (requires AngularJS 1.3.x, tested with 1.3.13). 0.12.0 is the last version of this library that supports AngularJS 1.2.x.
> Bootstrap CSS (tested with version 3.1.1). This version of the library (0.13.0) works only with Bootstrap CSS in version 3.x. 0.8.0 is the last version of this library that supports Bootstrap CSS in version 2.3.x.

**Comment by CITguy** [comment]
Closing. Captured in JIRA https://jira.rax.io/browse/FRMW-68
