### ISSUE TITLE
HeaderInterceptor

### ISSUE THREAD

**Issue by parlarjb** [rackerlabs/encore-ui#586]
Various apps have used things like `$http.defaults.headers.common['Accept'] = 'application/json';`

For `Accept`, that's fine. But for any "custom" headers, it breaks our calls to the CDN to get the nav menu. Per https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS, a custom header will cause a pre-flight OPTIONS request, which will always fail for a GET.

Instead we should have a `HeaderInterceptor`, which lets us register custom headers. But instead of it getting attached to every single outbound request, it will use an exclusion list like [`rxTokenInterceptor`](https://github.com/rackerlabs/encore-ui/blob/master/src/rxTokenInterceptor/rxTokenInterceptor.js#L28) 

That way we can ensure that custom headers don't get sent to the CDN

**Comment by glynnis** [comment]
Reopen if relevant again.
