### ISSUE TITLE
Create styles for required fields

### ISSUE THREAD

**Issue by glynnis** [rackerlabs/encore-ui#592]
We should give more info to the user about whether or not a field is required *before* the user submits a form. We need styles and documentation for this.

**Comment by glynnis** [comment]
There are several relatively standard ways of doing this in UIs. Here are a few:

### Use placeholders in the field followed by a star:
![screen shot 2015-02-16 at 9 34 19 am](https://cloud.githubusercontent.com/assets/1529366/6214598/50259bfc-b5bf-11e4-8fdb-ccdd279d4847.png)
I don't care for this much as once the user begins typing, they can no longer tell what the field should contain, nor that it is required. 

### Use an asterisk in proximity to the field label:
![screen shot 2015-02-16 at 9 35 44 am](https://cloud.githubusercontent.com/assets/1529366/6214600/502abaf6-b5bf-11e4-8335-d3e5e2d51dbc.png)
This is probably the most standard execution of "required field", and is pretty commonly understood by users without explanation.

### Use an asterisk flag on the field itself:
![screen shot 2015-02-16 at 9 35 55 am](https://cloud.githubusercontent.com/assets/1529366/6214599/502a1538-b5bf-11e4-8da7-a2e415c6150d.png)
Again, this is commonly understood by users, but I think the visual design is a bit nicer. It also could offer a greater screen area that could be used to display a tooltip that further explains that the asterisk indicates a required field, or even an explanation of why that field is a requirement.

The third implementation would be my preference, but requires a bit more expertise in implementation than a simple colored asterisk next to the label, and would need to be tested for browser compatibility.

**Comment by CITguy** [comment]
How would the asterisk flag (second option) work on drop downs?

**Comment by glynnis** [comment]
@CITguy I'd imagine it could be done with drop downs if we moved the little asterisk flag to the top-left corner of all fields, which again raises the question of difficulty of implementation if a simple "[label] + asterisk" might suffice. The main advantage the asterisk flag implementation has over "[label] + asterisk" is the possibility of tooltips and not needing to display a legend on every form.

This is a good reference article that may assist in making decisions about which direction to go when the time comes: http://alistapart.com/article/sensibleforms (in particular http://alistapart.com/article/sensibleforms#section4)

**Comment by CITguy** [comment]
Ultimately, if both solutions achieve the same goal, I'd be inclined to go with the simpler option of having "[label] + asterisk".  If we want to do something more graphically pleasing, we could use font awesome with a superscript similar to the following:

```html
<sup class="fa fa-asterisk required-symbol"></sup>
```
```css
.required-symbol {
  color: #f55;
  font-size: 0.8em;
}
```

**Comment by CITguy** [comment]
In fact, this wouldn't be too difficult to accomplish, with an attribute directive on the label (`<label rx-required>`).

**Comment by CITguy** [comment]
@glynnis, an example of using fa with a superscript -- http://codepen.io/CITguy/pen/VYMdgG

**Comment by CITguy** [comment]
My only concern with this is that our forms items are horizontal (with the label beside the field). Were we to implement the asterisk idea, we'd have to take into account the fixed width of the `<label>`.

**Comment by eric-dunham** [comment]
Or we could move to vertical form items! :D

**Comment by glynnis** [comment]
Working on design/UX for this now. Here's the direction we're going with layout/color.

![required-fields](https://cloud.githubusercontent.com/assets/1529366/7167264/48a1cd1e-e379-11e4-9229-302beca3923c.png)

![required-fields-with-notes](https://cloud.githubusercontent.com/assets/1529366/7167263/48a1a442-e379-11e4-9f6f-f6a73a80fe71.png)

However, this is still in progress -- I'm going to lay out some more complex form interactions (like multiple radio buttons, check boxes, etc.) so we can try to account for some of the use cases Encore runs into problems with. 

After speaking with @CITguy, it sounds like this work will be rolled up with #884, since both issues require an manual overhaul of form mark-up. Better to do it all at once than twice over :grin:

**Comment by glynnis** [comment]
@CITguy we should also ensure that any failures to complete required fields result in this style being applied: https://github.com/rackerlabs/encore-ui/blob/master/src/rxForm/rxForm.less#L82. Ideally we'll also have informative errors on those fields as well.

I realize that some of that (especially re: error messages) may be at the project level, not the Framework, but I'm making a note of it here so I don't forget, and we can follow up once this is in the Framework by creating JIRAs for that work if necessary.

**Comment by CITguy** [comment]
@glynnis: I'd also like to embiggen the borders for erroneous fields. The current errors with a 1px red border doesn't seem like enough contrast for my color blindness. Making the error border 2px helps make it obvious that there's an error.

**Valid Entry (1px border)**
![screen shot 2015-04-20 at 11 28 41 am](https://cloud.githubusercontent.com/assets/545605/7234940/8725bd72-e750-11e4-8856-700556e99b3a.png)

**Invalid Entry (2px border)**
![screen shot 2015-04-20 at 11 28 51 am](https://cloud.githubusercontent.com/assets/545605/7234950/95ffbe56-e750-11e4-8474-932ad7ab89d1.png)

**Invalid Entry (1px border)**
I feel like this doesn't bring as much attention to the user as the 2px border.
![screen shot 2015-04-20 at 11 31 10 am](https://cloud.githubusercontent.com/assets/545605/7234976/b9f7cc54-e750-11e4-8286-cd027819c3b8.png)

**Comment by glynnis** [comment]
@CITguy Noted :+1:  Thanks for bringing that to my attention! Hopefully the thicker border + asterisks and appropriate errors will all work together to eliminate this issue for folks who see color differently. Ideally if someone forgets a required field, we'd outline *and* display an error message.

I'll work to incorporate this into the design work I'm still doing on this.

**Comment by glynnis** [comment]
@CITguy is doing work on this as part of #884, so I'm closing this issue. He and I are communicating about any design/UX concerns for required fields as part of #884.
