### ISSUE TITLE
Note particular directives that are RackSpace specific in documentation

### ISSUE THREAD

**Issue by ErnieAtLYD** [rackerlabs/encore-ui#614]
Certain nav-related directives (`rxAccountUsers`, `rxTicketSearch`, `rxBillingSearch`) are RackSpace specific, and we should make a note of this in documentation and codebase as this is a project available to the public.

**Comment by glynnis** [comment]
@parlarjb Did this get done as part of the new style guide work?

**Comment by parlarjb** [comment]
Nope

**Comment by glynnis** [comment]
Included in style guide.
