### ISSUE TITLE
Remove excessive `li` from `rxPagination`

### ISSUE THREAD

**Issue by parlarjb** [rackerlabs/encore-ui#617]
Our old implementation of `rxPagination` made sense with all the pagination buttons being in a single `<ul>`. It doesn't make as much sense now. We should probably just put the page selector and itemsPerPage selectors into their own `<ul>`.

Easy enough, but will require reworking the CSS.

**Comment by glynnis** [comment]
Still relevant.

**Comment by glynnis** [comment]
Actually, closing this. Something like this can be addressed when we do a major component/tables design overhaul. Doesn't make much sense to address on its own as it would require an update in markup at the project level. Would rather wait to include this with some other major design work to tables.
