### ISSUE TITLE
Pagination shouldn't show items per page options unless table items exceed that limit.

### ISSUE THREAD

**Issue by Droogans** [rackerlabs/encore-ui#631]
For instance, this table only has four entries in it, but there are available options to expand the length of the table to 500 items.

![screen shot 2014-11-14 at 11 03 35](https://cloud.githubusercontent.com/assets/1214609/5049792/07c10b6e-6bee-11e4-86c0-55e6ec7ca9d0.png)

Incidentally, it also mangles the style in this case due to wrapping. That's not so much the issue, but it goes to show that this feature would streamline the appearance of the pagination widget.

**Comment by glynnis** [comment]
Still relevant.

**Comment by anur2213** [comment]
Related Jira story:
https://jira.rax.io/browse/FRMW-459

**Comment by CITguy** [comment]
Closing. Captured in JIRA
