### ISSUE TITLE
Escape hotkey should dismiss the oldest rxNotify message.

### ISSUE THREAD

**Issue by Droogans** [rackerlabs/encore-ui#632]
I went to create a new event today after creating and deleting a couple and had this happen to me.

![screen shot 2014-11-14 at 15 06 40](https://cloud.githubusercontent.com/assets/1214609/5053431/e9b7bbfa-6c0f-11e4-8bea-589b5ef55c4d.png)

I instinctually pressed the escape key to close these messages so I could click the underlying link. Perhaps this is a sane default for users who might feel they're getting spammed by notifications?

**Comment by CITguy** [comment]
My only concern with this idea is whether it will interfere with `rxModal` <kbd>esc</kbd> functionality.

**Comment by glynnis** [comment]
FWIW, UX has concerns about rxNotify covering links as well -- we've heard complaints from the support floor and seen specific cases where support Rackers can't find links they need, or they have to wait several seconds for notifications to disappear before they can click the links they need.

There isn't an immediate solution (this is kind of a far future thing), but it's relatively high on the list of "big Encore problems" that UX plans to address. Just something I wanted to mention here in case it has bearing on decisions we make today.

**Comment by glynnis** [comment]
Closing this as it won't be relevant once we shift to new notifications design.
