### ISSUE TITLE
Fix new select styles for FF

### ISSUE THREAD

**Issue by glynnis** [rackerlabs/encore-ui#664]
New select styles to prevent text overlap with the caret look pretty jank in FF right now :confused: 

For example:
![screen shot 2014-12-08 at 11 52 06 am](https://cloud.githubusercontent.com/assets/1529366/5344013/c882a5b6-7ed0-11e4-8a36-20789ea4ae14.png)
![screen shot 2014-12-08 at 11 50 20 am](https://cloud.githubusercontent.com/assets/1529366/5344012/c880e19a-7ed0-11e4-80dd-13cbe57dc5a9.png)

**Comment by velveteer** [comment]
@glynnis 

![image](https://cloud.githubusercontent.com/assets/3134804/5879445/08f59ba6-a2f5-11e4-9ec0-e1ac79eaa57e.png)

I don't exactly like this, but it works with Chrome and Firefox in Billing-UI. 

Chrome: 

![image](https://cloud.githubusercontent.com/assets/3134804/5879461/2e02916a-a2f5-11e4-8ad4-5ae6490fce35.png)

Firefox:

![image](https://cloud.githubusercontent.com/assets/3134804/5879464/34e64c06-a2f5-11e4-9da5-85137e359a36.png)

**Comment by CITguy** [comment]
Here's the culprit: 
https://github.com/rackerlabs/encore-ui/blob/master/src%2FrxForm%2FrxForm.less?ts=2#L299

We're not using `-moz-appearance: window;`, so this rule no longer applies.

**Chrome (with rule)** :+1: 
![screen shot 2015-01-24 at 10 08 01 pm](https://cloud.githubusercontent.com/assets/545605/5890189/98f4abb8-a415-11e4-9721-f495ac77d0b0.png)
![screen shot 2015-01-24 at 10 07 36 pm](https://cloud.githubusercontent.com/assets/545605/5890190/98f598e8-a415-11e4-85f1-2816cb3bb6ae.png)

**Chrome (without rule)** :+1: 
![screen shot 2015-01-24 at 10 10 05 pm](https://cloud.githubusercontent.com/assets/545605/5890198/db092f6a-a415-11e4-989d-18d68edb9f93.png)
![screen shot 2015-01-24 at 10 09 55 pm](https://cloud.githubusercontent.com/assets/545605/5890197/db0068ee-a415-11e4-8599-1e5869e75fe0.png)


**Firefox (with rule)** :-1: 
![screen shot 2015-01-24 at 10 08 34 pm](https://cloud.githubusercontent.com/assets/545605/5890191/a911c5b2-a415-11e4-98ee-59d97df11f9d.png)
![screen shot 2015-01-24 at 10 08 15 pm](https://cloud.githubusercontent.com/assets/545605/5890192/a9120d9c-a415-11e4-9c99-6df174abcd5d.png)


**Firefox (without rule)** :+1: 
![screen shot 2015-01-24 at 10 10 30 pm](https://cloud.githubusercontent.com/assets/545605/5890200/e0cd1844-a415-11e4-8156-106f06a3de72.png)
![screen shot 2015-01-24 at 10 10 22 pm](https://cloud.githubusercontent.com/assets/545605/5890199/e0ca337c-a415-11e4-8bdc-812d76a8e25d.png)
