### ISSUE TITLE
Store in-progress form/input data

### ISSUE THREAD

**Issue by parlarjb** [rackerlabs/encore-ui#679]
If a user is entering data in a text area, or other `input` elements, we should be able to temporarily save that data. This would allow them to navigate away and come back, and still have the content there.

Github and Stackoverflow both do this for their comment boxes, but they both send all data to their servers, and repopulate it on a return to the page.

I'd rather use a localstorage/sessionstorage solution, as described here http://stackoverflow.com/questions/14420624/how-to-keep-changed-form-content-when-leaving-and-going-back-to-https-page-wor

**Comment by glynnis** [comment]
@parlarjb says we should still do this. It's been requested a few times.

**Comment by glynnis** [comment]
This came up again on 3/31 during our Framework Stakeholders meeting. Casey brought up the fact that form data shouldn't be stored forever -- it should probably expire after a certain amount of time (24hrs?).
