### ISSUE TITLE
rxPaginate needs more midway examples

### ISSUE THREAD

**Issue by Droogans** [rackerlabs/encore-ui#69]
With the addition of creating the `opts` hash for over-riding default parameters in rxPaginate, there are now more edge cases that need to be tested for in the midway tests.

I'm not sure how we should go about adding additional examples. Perhaps we can link to different pages with more examples somewhere in the app, so that the main page can stay the way it is?

**Comment by glynnis** [comment]
Happy birthday this issue :cake: :birthday: :balloon:
