### ISSUE TITLE
Bundle Google Fonts with the framework

### ISSUE THREAD

**Issue by parlarjb** [rackerlabs/encore-ui#692]
See https://jira.rax.io/browse/UXENCORE-56

We're shipping pure grids and FontAwesome, so we might as well bring in our fonts too.

**Comment by CITguy** [comment]
Should we bundle the actual font files into the framework or just use an `@import url(http://fonts.googleapis.com/...)`?

**Comment by velveteer** [comment]
@CITguy :+1: 

On a related note, anything listed as a dependency in Bower, such as FontAwesome: https://github.com/rackerlabs/encore-ui/blob/master/bower.json#L19, should not be bundled. The latest template is designed to inject Bower dependencies into the compiled index. If we're going to bundle anything it should be listed as a dev dependency, like we do for Pure. For FontAwesome this would mean removing the font files from the bundle and opting to use CDN URL's instead.

**Comment by glynnis** [comment]
Still relevant.

**Comment by CITguy** [comment]
@glynnis, @parlarjb: still relevant?

**Comment by parlarjb** [comment]
Now that we no longer bundle FontAwesome, it's a good question. I'm fine with closing this, but I'd be interested in what @glynnis has to say
