### ISSUE TITLE
Provide a method to have rxAccountInfo update its details

### ISSUE THREAD

**Issue by parlarjb** [rackerlabs/encore-ui#696]
Right now rxAccountInfo grabs badges and account info on page load, and never again. We need a way to get it to refresh that data without reloading the page.

One method would be to pass a "registration" function to rxAccountInfo. rxAccountInfo could then call then immediately, providing it with a function of its own that should be called by the page controller when a refresh is required. 

Alternatively, we do a kind of "edge detection" with two-way binding. Pass a reference that's set to `false`, and have rxAccountInfo watch for when it goes to `true`. When it goes `true`, update the account details, and then set it `false` again.

**Comment by glynnis** [comment]
@parlarjb has this working. Coming soon.

**Comment by glynnis** [comment]
@parlarjb Is this still relevant? If not, please close.

**Comment by parlarjb** [comment]
Closing until someone asks for it again. Sorry @klamping
