### ISSUE TITLE
Investigate moving nav menu JSON file to an API

### ISSUE THREAD

**Issue by parlarjb** [rackerlabs/encore-ui#697]
For the most part, storing the nav JSON on the CDN has worked well. It's easy to deploy to the CDN, and it's simple to grab the file, but there are two issues:

1) We don't get a ton of control over deployment. We have to wait for Travis to pick up the merge task, start its work, and then send everything to Akamai. And once at Akamai, we have zero control, we just have to wait. Normally this takes 5-15 minutes.
2) We have now experienced a situation where Akamai said it was done updating the nav file on the CDN. But for whatever reason, it took over an hour before the new file was being served up. We were still seeing the old one.

It's time to move to an API for serving up the file. We should be able to do this seamlessly, wherein our deploys will *still* go out to the CDN, to support older versions of encore-ui, but they'll also update the API. Once all products are at a new enough version of encore-ui, we can turn off the CDN

**Comment by CITguy** [comment]
:+1:

**Comment by glynnis** [comment]
@parlarjb says we aren't going to do this until we have feedback on left nav from RED.
