### ISSUE TITLE
Try to use LESS mixins for status column icons

### ISSUE THREAD

**Issue by parlarjb** [rackerlabs/encore-ui#698]
See https://github.com/rackerlabs/encore-ui/pull/695/files#r22125628

**Comment by CITguy** [comment]
Is this issue still relevant?

**Comment by parlarjb** [comment]
It's a "nice to have". I did have a quick try at it last month, but it didn't work. Doesn't mean it can't work, just that I couldn't figure it out in the hour or so I gave to it.

**Comment by glynnis** [comment]
Closing for now. There may be changes to icon designs/how we use them for status column design in the near future.
