### ISSUE TITLE
rx-date-picker-simple needed

### ISSUE THREAD

**Issue by Droogans** [rackerlabs/encore-ui#714]
Everyone's doing date input their own way, and it makes my job harder than it should be.

@TheNando has a simple date picker that might be a good starting point, but it needs some UX work.

There's also https://github.com/angular-ui/bootstrap/tree/master/src/datepicker.

**Comment by glynnis** [comment]
This came up again as a need for Flashmob's Mass Ticketing tool today during a design review.

:+1: for prioritizing this -- as @Droogans indicated, this is something a lot of teams are using and that I feel we should prioritize in the near future.

cc/ @scadams

**Comment by scadams** [comment]
It should be rx-datetime-picker, since we need to choose time and date.

**Comment by jj4th** [comment]
We have a similar need in Encore Cloud UI LBaaS

**Comment by Droogans** [comment]
@jj4th I can show you some tips to make interacting with custom built date pickers (typically in the form of several form elements) much less of a pain. There's some work up front, but it saves time down the line.

I have an example from supportservice-ui I can link to you.

**Comment by glynnis** [comment]
@scadams @jj4th Could you both add more details about your team's need here? i.e. do you just need dd/mm/yyyy, or do you also need time? If you need time, do you also need time zone? Do you need recurring events, days of the week, etc.?

**Comment by glynnis** [comment]
Here's a screen shot of the date picker for Events (Billing):

![screen shot 2015-07-20 at 10 15 05 am](https://cloud.githubusercontent.com/assets/1529366/8779361/b690ca6a-2ec8-11e5-9294-b5a4256431cc.png)
- Start date (MMDDYYYY), with time (HH:MM, 24hr clock) + time zone
- End date in same format

@kobowley Are there any other existing date pickers in EOD or Billing that you're aware of besides Events?

**Comment by megalord** [comment]
For reference, here is what currently exists in Chrome:
![screen shot 2015-07-20 at 10 43 40 am](https://cloud.githubusercontent.com/assets/5414922/8780110/7226e900-2ecc-11e5-9832-05bb06db4474.png)
![screen shot 2015-07-20 at 10 46 34 am](https://cloud.githubusercontent.com/assets/5414922/8780130/9e8d1dde-2ecc-11e5-923f-ec3a0b8d811d.png)
The timezone is missing though, so even this would have to be adapted to meet our needs.

**Comment by glynnis** [comment]
Here's a screen shot from Ticketing Admin, which @scadams could probably say more about:
![screen shot 2015-07-20 at 10 28 37 am](https://cloud.githubusercontent.com/assets/1529366/8780217/27702b5a-2ecd-11e5-94bb-fba49478c660.png)

Looks like:
- Start time HH:MM (24hr clock) w/ Time Zone
- Duration in hours
- Description field (this is just an input field, likely doesn't need to be part of date picker but depending on how a date picker is built it could possibly be auto-generated?)

I think there may be other date pickers in Ticketing Admin, but I'm not totally sure about that.

**Comment by scadams** [comment]
This is the datetime picker we have in Flashmob:

![image](https://cloud.githubusercontent.com/assets/753260/8781054/8d17e736-2ed2-11e5-8afd-176fc43449a8.png)

**Comment by scadams** [comment]
To answer your other questions, we don't need recurring events or days of the week. We just need month, day, year, hour, minute, and timezone.

We also default the timezone to the browser timezone, so that would be a nice feature to keep.

**Comment by CITguy** [comment]
## Summary

So if I'm understanding correctly, we only need two components: 

* `rx-date` (Month + Date + Year)
* `rx-time` (24H Hour + Minute + Time Zone)


All of the interactions I see above would just require mixing and matching one or more `rx-date` or `rx-time` components in a form control.

### Billing Events
Needs Date + Time

* Start Date: `rx-date` (MM/DD/YYYY) + `rx-time` (HH:MM-Z)
* End Date: `rx-date` (MM/DD/YYYY) + `rx-time` (HH:MM-Z)


### Ticketing Admin

* Start Time: `rx-time` (HH:MM-Z)

### Cloud UI
Needs Date Range (i.e. 2 rx-date elements)

* beginDate: `rx-date` (MM/DD/YYYY)
* endDate: `rx-date` (MM/DD/YYYY)

-----

CC: @glynnis, @Droogans, @TheNando, @scadams, @jj4th, @megalord

**Comment by khaziwallis** [comment]
some of the cases we dont need time format, So time should be optional.

![usage section](https://cloud.githubusercontent.com/assets/3723469/9006532/d962f92e-37a5-11e5-94a9-c0bc3a96d07c.png)

**Comment by CITguy** [comment]
@khaziwallis Thank you. This is captured in the Cloud UI section in my comment above in regards to just date pickers.

**Comment by megalord** [comment]
I'll just say that I'm not sure splitting into two components is a good idea.  In cases where the api expects `2015-07-29T14:59:08Z` or `2015-07-29T14:59:08+00:00`, this split would burden the developer with joining the two models.  If we enforce that the models are moment dates, then it *would* be easy to add them together.

An alternative is to make a single component with a feature flag.  The developer would be responsible for adding a parser or formatter to meet there specific need, and we could provide a few standard ones.

**Comment by CITguy** [comment]
I'm not fond of having a single component because it would mean adding unnecessary complexity (need I remind you of `rxFormItem`).  It would be easier to create small components that do one job and one job well.  It then becomes easier to compose larger components from smaller ones down the road (it's much more difficult to go the other way around).

In regards to building proper date strings, what if we provide a service in `rxMisc` that joins the date + time into a moment date?  This would eliminate the need for the developer to do this manually.

**Comment by CITguy** [comment]
In addition, what if designs call for different arrangements of the date and time fields? This cannot be done easily with a single component.

**Comment by megalord** [comment]
Yeah, putting a helper method in `rxMisc` would be a good way of keeping it simple.  As far as different designs, that *starts* to deviate from the purpose of having a framework level component in the first place - making all date or time pickers appear and behave the same way.

**Comment by CITguy** [comment]
Well, the date and time pickers *would* behave the same way, just arranged differently.

**Comment by CITguy** [comment]
@halkon, @parlarjb, @TheNando, @Droogans Do any of you have a preference?

### Option 1
Single `rx-datetime` component with feature flags to show/hide date/time fields.

### Option 2
Split into `rx-date` and `rx-time` with a `rxMisc` service to join into a single date object.

**Comment by halkon** [comment]
I'm more inclined for **Option 2**, bringing the date and time in with a `rxMisc` service seems a bit overkill though. 

That being said it does make it "easy" but we become "responsible" for any issues that there may be.  

Either way, **Option 2** is my vote

**Comment by Droogans** [comment]
I like `rx-date` and `rx-time`. What's wrong with supporting `rx-datetime` alongside it? If you're going to put the logic to combine the two anyplace, it should be with the other date/time logic. Not in rxMisc.

I imagine developers might get upset if they found out that they had been composing dates and times together themselves manually, only because they didn't bother to look into rxMisc for a purpose built solution.

**Comment by CITguy** [comment]
Well if we have the components act on attributes of an object model, we could have a single model contain the information.

```html
<!-- Acts on `year`, `month`, and `day` keys on model object. -->
<rx-date ng-model="myDateTime"></rx-date>

<!-- acts on `hour`, `minute`, `zone` keys -->
<rx-time ng-model="myDateTime"></rx-time>
```

```javascript
// myDateTime after rx-date manipulation
{
  year: 2015,
  month: 7,
  day: 31
};

// myDateTime after rx-time manipulation
{
  year: 2015,
  month: 7,
  day: 31,
  hour: 17,
  minute: 0,
  zone: 'America/Chicago'
};
```

Then it'd be a simple matter of creating a single string from `foobar` values to parse with `moment`

```javascript
function toMomentString(obj) {
  return [
    obj.year,
    obj.month,
    obj.day,
    obj.hour,
    obj.minute
  ].join()
}

var datetime = moment(toMomentString(foobar), 'YYYYMMDDHHmm', foobar.zone);
```

**Comment by CITguy** [comment]
@Droogans: Yes, there's nothing stopping us from creating `rx-datetime` once `rx-date` and `rx-time` are functional.

**Comment by CITguy** [comment]
My concern was allowing developers to be able to compose custom date/time controls out of smaller components.

**Comment by CITguy** [comment]
So, three components...

* `rx-date-select`
  * date picker
* `rx-time-select`
  * time picker
  * timezone support
* `rx-datetime-select`
  * provides common usage layout of `rx-date-select` and `rx-time-select`
    * requires wireframe from Design team
  * feature flags to show/hide either date or time portion
    * *should not* allow hiding *both* date and time

All three components should use a Moment.js object for `ng-model`.

**Comment by Droogans** [comment]
@CITguy I think we can drop the flags from `rx-datetime-select` if we have both date-select and time-select available for individual use.

I think @megalord recommended that as a "one big directive" approach.

**Comment by CITguy** [comment]
@Droogans, good point. Removed feature flag requirement.

**Comment by lfielder** [comment]
@CITguy I am picking this up from a design perspective. From what I have read, we need 3 designs `rx-date-select`, `rx-time-select`, rx-datetime-select`.  

Would we actually want to create a fourth component for a date range for use in filtering? It seems that this is unique.

**Comment by Droogans** [comment]
I believe date ranges could be accomplished by applying two calendars side by side. One for start, one for end.

**Comment by Droogans** [comment]
As far as an existing date picker with time support: https://tarruda.github.io/bootstrap-datetimepicker/

Might be a good baseline to consider?

**Comment by lfielder** [comment]
`rx-date-select`

![screen shot 2015-09-17 at 10 44 56 am](https://cloud.githubusercontent.com/assets/1626241/9938076/3669b268-5d29-11e5-8534-c5b1c8727a28.png)

**Comment by CITguy** [comment]
@lfielder, `rx-date-select` :+1:

**Comment by halkon** [comment]
More like ![doggy-pat](https://cloud.githubusercontent.com/assets/1437154/9938243/0962a54e-5d2a-11e5-918f-86bde874176d.gif)

**Comment by lfielder** [comment]
I was also thinking something like this for date range.

![screen shot 2015-09-17 at 10 52 10 am](https://cloud.githubusercontent.com/assets/1626241/9938289/41941e66-5d2a-11e5-80e6-5c30c47f7efa.png)

**Comment by Droogans** [comment]
That'd need to be a fourth component. And that's just for dates! You'd need a fifth for just times, and a sixth for dates+times.

I think we're on the right track, but only if we can cut down the number of directives being exposed. Six components is a lot of overhead to maintain for something like this.

**Comment by CITguy** [comment]
If we add functionality that it is aware of it being a range, it would no longer be purely a date picker, but a date _range_ picker.  I'd rather  provide functionality to set a `min-date` and inversely a `max-date` that just disables dates for selection.

**Comment by Droogans** [comment]
Also, timezone selection is needed as well.

**Comment by CITguy** [comment]
For date selection, ISO 8601 doesn't require time zones.

**Comment by CITguy** [comment]
For the date range above, I'd expect to code something like the following:

```html
<rx-date-select ng-model="startDate"></rx-date-select>
-
<rx-date-select ng-model="endDate" min-date="startDate"></rx-date-select>
```

**Comment by Droogans** [comment]
@CITguy only time pickers should (at a minimum) should get one. 

You might even consider at least marking all date selections as UTC as to avoid confusion. Creating dates in CST would mean setting them to midnight two hours ahead of PST, so January 1st, 2016 00:00 CST would be December 31st, 2015 22:00 PST. Although it is rare to have that sort of overlap occur, it can and will happen unless folks are aware that timezones can cause events to fire/start "a day early" (according to users).

**Comment by CITguy** [comment]
@Droogans, that's a datetime. Date pickers shouldn't care about timezones, _datetime_ pickers would.

**Comment by glynnis** [comment]
@lfielder These look great! Totally fit in with Encore look/feel and I like how clean they are. I think it might be helpful to show some examples of different forms/field combos and how these components would look with those. My assumption looking at these screen shots is that clicking the blue icons within the input boxes would bring up the calendar/time views, is that correct? Might be worth showing a "before user interacts", "during user interaction", and "complete" states and calling those out explicitly in the mock-up or commenting in InVision, just so interaction implementation is clear.

You might also consider:
- Are there any hover/active state changes? For example, does icon color change at various states of the interaction? Does the icon always show (including when the calendar/time pickers are expanded), or do they only appear within the input when the pickers are not expanded?
- Does any appearance or interaction design change when the user goes back to change a prior selection?
- Are there any error states that would be relevant to design for? What if the form specifies choosing a time within a certain range (i.e. cannot select a date in the past, or a time in the past) -- what would that look like for each of these pieces?
- Do we need a treatment for when a user can leave a part blank? For example, a date is a required field, but adding the time is optional? Is that just communicated through our typical "required field" treatment in rxForm, certain copy, etc.?
- If several of these fields appear in the same form, is there a certain order or rules around how they appear together? For example, if a product needs a date and time in the same form, should they always used the combined component? Are there times where using the date/time combo is not appropriate?

Some of the answers to these may be obvious, but might be worth answering explicitly just to keep requirements and UX clear and eliminate assumptions for development. @ElementE Can you think of anything else state-wise that we might need to consider?

**Comment by CITguy** [comment]
Formats:

* **Date**: `YYYY-MM-DD`
* **Time**: `HH:mmZ`
* **Datetime**: `YYYY-MM-DD HH:mmZ`

**Comment by Droogans** [comment]
@CITguy if you drop something formatted like `YYYY-MM-DD` into `new Date` from San Antonio, and push that to an API, it's going to set it to 10PM the previous day to people who ask for that date in San Francisco. The `Z`, when left off, will default to the user's current timezone according to their browser.

I think this is going to be mostly something up to @glynnis and @ElementE. I would argue that as a technology company with customers all over the planet, it makes sense to present dates and times in a consistent format across the planet. Even though UTC is confusing at first, I'd think support teams who deal with technology all the time would be comfortable with it, and grateful for it!

I haven't done any research so this is all conjecture.

**Comment by CITguy** [comment]
@lfielder, @glynnis: Is this being designed with American display formats only (`September 17, 2015`), or would we need to provide support for other parts of the world (`17 September 2015`, `2015 September 17`)?

@Droogans: Unfortunately, the javascript `Date` object actually represents a logical _datetime_ data structure based on UTC, not a _date_ data structure.  This is a frustrating part of Javascript that we have no control over and it should be common knowledge to web developers.

The `rx-date-select` _can_ be used on its own, but within Rackspace, it's more than likely going to be used in conjunction with a `rx-time-select`.  If a developer chooses to use `rx-date-select` on its own, it is their responsibility to know how it behaves with their logic.  As a developer, if I code my interface to only accept a date input, I should know the limitations of Javascript and I would need to do one of the following:

0. hardcode my expected time zone when composing the ISO 8601 datetime string
  1. `new Date(formDate + 'T00:00-05:00')`
0. leave it as UTC
  1. `new Date(formDate)`

**Comment by Droogans** [comment]
@CITguy that's the beauty of publishing components that come ready out of the box. There are certain things that can come pre-configured, prescribed by default for UX reasons. Think form layouts, sort direction arrows, etc.

It's entirely possible to take all dates from users of `rx-date`, regardless of browser settings, and [save them as UTC@midnight](http://stackoverflow.com/a/11964609/881224). I think this should be the default.

This is more of a question for @glynnis. Presenting all date/time/datetime inputs as UTC is primarily a UX concern.

**Comment by lfielder** [comment]
I don't see presenting all times as UTC as an acceptable solution for users. I can definitely see us get some major push back from the support floor on that.

@CITguy  First step is US date formats. 

Is there not a way we can detect location and present date/time in the appropriate way? Would this be better served as a user specific setting in the future?

**Comment by lfielder** [comment]
@glynnis  I have solutions for your questions, but I will take some time to clean them up and articulate them correctly.

**Comment by glynnis** [comment]
@lfielder :+1:

**Comment by lfielder** [comment]
We should probably break out the date picker first. Here is an invision: https://invis.io/TG4B3YUD8

**Comment by glynnis** [comment]
@CITguy, @lfielder, Anu, and I met to discuss this. Anu will be creating stories in JIRA for this effort, so I'm closing here on github. I'll post the URLs for the JIRA stories when I have them.

**Comment by glynnis** [comment]
JIRA stories: https://jira.rax.io/browse/FRMW-316 and https://jira.rax.io/browse/FRMW-315
