### ISSUE TITLE
Centralize rxDOMHelper

### ISSUE THREAD

**Issue by CITguy** [rackerlabs/encore-ui#734]
`rxDOMHelper` is currently defined within `rxFloatingHeader` but its functionality is used across directives.  Please move `rxDOMHelper` to its own file in a centralized location for injection by any directive.  I'd suggest using a namespace such as `encore.ui.util`.

**Comment by Droogans** [comment]
I don't know how you feel about `rxjq`, but that's what I have seen it aliased as. Is that better than `util`? I always feel like util, common, and helpers are always a dumping ground for miscellaneous stuff.

Now that I think about it, `rxMisc` has a certain ring to it.

**Comment by CITguy** [comment]
`rxMisc` doesn't sound too bad. I'll put in a PR for this.
