### ISSUE TITLE
Have rxPaginate support "lazy pagination"

### ISSUE THREAD

**Issue by parlarjb** [rackerlabs/encore-ui#739]
We should be able to configure rxPaginate to work with paginated APIs, rather than requiring all objects are fetched at once.

rxPaginate makes a lot of assumptions right now around the fact that all the objects are available. This will need some discussion before we move to implementation.

@velveteer Is this something you've done work on for support service?

**Comment by parlarjb** [comment]
Github has a nice pagination API, and could be used as an example of what we need to support https://developer.github.com/guides/traversing-with-pagination/

**Comment by parlarjb** [comment]
The user experience of having to wait for a network request when they change pages might not be ideal. We could do that, but it would also be nice to support paging in the UI such that we start loading all the pages on after another, to try to have them already there before a user clicks to go to a given page.

**Comment by scadams** [comment]
Since REST APIs can have different pagination schemes, I think we would need a way to pass in custom functions that rxPaginate can use to parse the first page response and get the page size, total number of pages, and possibly the next page link.

**Comment by chriscantu** [comment]
@parlarjb @scadams 

First, we do not have a server side pagination solution for support service.  We leveraged Encore API to get the full data set.  

I am supposed to be meeting with @RackerHector tomorrow or next week to discuss solutions for pagination.  I am hoping that will be a first step towards standardization.

**Comment by chriscantu** [comment]
Additionally: If we leverage server side pagination, the API will also be responsible for sorting and filtering.

**Comment by chriscantu** [comment]
@parlarjb Finally, we also have documentation for how server side pagination should be done for Encore today. Remind me tomorrow and I will forward it to you.

**Comment by megalord** [comment]
@parlarjb can this be closed?

**Comment by parlarjb** [comment]
Oops, I must have forgotten to tag it in my PR. Yep, all done, thanks.
