### ISSUE TITLE
Bug with transcluded content with rxFormItem

### ISSUE THREAD

**Issue by CITguy** [rackerlabs/encore-ui#748]
When using rxFormItem on `<input>` fields that are displayed based on a `ng-switch`, the `<span class='form-input'>` is not applied to the transcluded content.

This source code
```html
<rx-form-item label="Foobar" ng-switch="'nothing'">
  <input ng-switch-when="nothing" value="I'm nothing" />
</rx-form-item>
```

should result in this expected output:
```html
<rx-form-item label="Foobar" ng-switch="'nothing'" class="ng-scope ng-isolate-scope">
  <div class="form-item" ng-class="{'text-area-label': isTextArea}">
    <label class="field-label ng-binding">Foobar:</label>
    <div class="field-content">
      <!-- ngIf: prefix -->
      <span class="field-input-wrapper" ng-transclude="">
        <span class="field-input">
          <!-- ngSwitchWhen: nothing -->
          <input ng-switch-when="nothing" value="I'm nothing" class="ng-scope">
        </span>
      </span>
      <!-- ngIf: description -->
    </div>
  </div>
</rx-form-item>
```

but it actually results in this output (missing `<span class="field-input">...</span>`):
```html
<rx-form-item label="Foobar" ng-switch="'nothing'" class="ng-scope ng-isolate-scope">
  <div class="form-item" ng-class="{'text-area-label': isTextArea}">
    <label class="field-label ng-binding">Foobar:</label>
    <div class="field-content">
      <!-- ngIf: prefix -->
      <span class="field-input-wrapper" ng-transclude="">
        <!-- ngSwitchWhen: nothing -->
        <input ng-switch-when="nothing" value="I'm nothing" class="ng-scope">
      </span>
      <!-- ngIf: description -->
    </div>
  </div>
</rx-form-item>
```

**Comment by CITguy** [comment]
So... unless somebody can determine how to get the directive `link` function to apply _AFTER_ the `rootscope.$digest()` call, I can't figure out how to fix this purely in the framework.  The best solution I can think of at the moment is to document using a `<span class="field-input">...</span>` around any angular-driven DOM manipulation. So the above would become:

```html
<rx-form-item label="Foobar" ng-switch="'nothing'">
  <span class="field-input">
    <input ng-switch-when="nothing" value="I'm nothing" />
  </span>
</rx-form-item>
```

Symptoms: 
1. DOM manipulation doesn't work on the `<input ng-switch-when="..." />` nodes because they aren't present in the DOM when the link function is executed.
2. `ngSwitch` functionality doesn't resolve until `rootscope.$digest()` is run (after directive `link` function has already returned).

Ideas? Thoughts?

**Comment by megalord** [comment]
@CITguy, perhaps I don't understand the problem, but I suggest assigning a watcher on the scope for the given attribute.
```javascript
// rxFormItem
link: function (scope, ed, attr) {
  scope.$watch(attr.ngSwitch, function () {
    // ...
  });
}
```
No, I'm not very certain this code will do what you're asking.

**Comment by CITguy** [comment]
The location of `ngSwitch` functionality doesn't seem to matter. The output of `ngSwitch` contributes to what I'm looking to wrap, so this wouldn't work for the following scenarios:

```html
<!-- ng-switch INSIDE rx-form-item -->
<rx-form-item label="Foobar">
  <div ng-switch="'nothing'">
    <input ng-switch-when="nothing" value="I'm nothing" />
    <div>Some other Content</div>
  </div>
</rx-form-item>

<!-- ng-switch OUTSIDE rx-form-item -->
<div ng-switch="'nothing'">
  <rx-form-item label="Foobar">
    <input ng-switch-when="nothing" value="I'm nothing" />
    <div>Some other Content</div>
  </rx-form-item>
</div>
```

The root of the problem is that I want to selectively wrap certain elements in the transcluded content (input, select, textarea, etc.) in a `<span class="field-input">...</span>` tag and leave everything else in place. But when the directive `link` function runs, the `ng-switch-when` elements do not exist in the DOM for manipulation. When the `link` function runs, the DOM looks like this:

```html
<!-- ng-switch INSIDE rx-form-item -->
<rx-form-item label="Foobar">
  <div ng-switch="'nothing'">
    <div>Some other Content</div>
  </div>
</rx-form-item>

<!-- ng-switch OUTSIDE rx-form-item -->
<div ng-switch="'nothing'">
  <rx-form-item label="Foobar">
    <div>Some other Content</div>
  </rx-form-item>
</div>
```

Make sense?

**Comment by megalord** [comment]
Yes, it makes sense.  I still think the easiest way is to setup a watch on the scope - it shouldn't matter where the `ng-switch` is (inside or outside), as long as the property for it is also passed to the `rx-form-item`.  But I can see why that solution isn't very clean.

**Comment by CITguy** [comment]
Considering that the only way to fix this is to not use `rx-form-item` and that `rx-form-item` is going away in a future release. I'm going to tag this as "won't fix" and close the issue.
