### ISSUE TITLE
rx-page-objects documentation.

### ISSUE THREAD

**Issue by Droogans** [rackerlabs/encore-ui#752]
First, change all the comments to [true multiline comments for jsdoc](http://usejsdoc.org/about-getting-started.html).

Next, export all of the comments to an auto-genned [markdown file](https://www.npmjs.com/package/jsdoc-to-markdown) that is created during the `grunt rxPageObjects` task.

Finally, iterate and make the docs part of the official demo site.

**Comment by Droogans** [comment]
See #764.

**Comment by CITguy** [comment]
@Droogans, where are we with this?

**Comment by Droogans** [comment]
There's some progress made. I need to discuss with @parlarjb about changing a few things up in the page objects, documenting them better, having a few breaking changes, and shipping 2.0 if possible.

I would like to see this part of it.

**Comment by Droogans** [comment]
I've done everything here except I still need to document at least 10 or 15 more page object files.

**Comment by anur2213** [comment]
Associated Jira story: https://jira.rax.io/browse/FRMW-520
