### ISSUE TITLE
Add styles/directive for parent-child tables

### ISSUE THREAD

**Issue by glynnis** [rackerlabs/encore-ui#761]
There are some existing styles for this present in Cloud and the Dedicated Load Balancer tool. There's also a separate (non-preferred) implementation in vCenters here: https://staging.encore.rackspace.com/virt/vcenters

We should consider bringing these styles and/or making a directive for this in the Framework, since it's a pattern being utilized across several projects. Note that we should also add an additional layout to the demo that features this pattern.

Existing implementation in Cloud: https://github.com/rackerlabs/encore-cloud-ui/pull/445
![screen shot 2015-01-29 at 3 35 27 pm](https://cloud.githubusercontent.com/assets/1529366/5967051/1dd366dc-a7cf-11e4-928b-8defae051075.png)

**Comment by megalord** [comment]
Progress started [here](https://github.com/megalord/encore-ui/tree/nested-table).
