### ISSUE TITLE
Sort Icon Overlap Column Title

### ISSUE THREAD

**Issue by CITguy** [rackerlabs/encore-ui#762]
Skinny column headers are overlapped by sort icon
![screen shot 2015-01-30 at 1 33 50 pm](https://cloud.githubusercontent.com/assets/545605/5983527/ac640676-a893-11e4-83e0-ae25285727d1.png)

**Comment by glynnis** [comment]
What browser/version/OS(s) are you seeing this in?

**Comment by CITguy** [comment]
Chrome (Version 40.0.2214.91 (64-bit))
Firefox (34.0.5)
Mac OS (10.8.5)

This happens when a table condenses for smaller screen widths.  An example can be seen by resizing the screen width at [hub_cap/servers](https://staging.encore.rackspace.com/cloud/323676/hub_cap/servers)).
This isn't much of a problem if the app is viewed full screen, but this would hold show up for tables used in a modal as well.

**Comment by CITguy** [comment]
I first noticed this directly on my laptop screen (smaller resolution width than my external screens).

**Comment by CITguy** [comment]
*bump* - This was just brought up again in https://jira.rax.io/browse/EO-165.

I believe this is an issue with using the CSS `float` property. It doesn't properly compact with smaller width screen sizes and no amount of margins will correct the issue.  I believe it may be corrected by switching to a flexbox layout.

**Comment by glynnis** [comment]
Move to JIRA

**Comment by anur2213** [comment]
Related Jira story:
https://jira.rax.io/browse/FRMW-457
