### ISSUE TITLE
Add "disabled" style for rxStatusColumn

### ISSUE THREAD

**Issue by glynnis** [rackerlabs/encore-ui#766]
This is something utilized heavily by the new dedicated Load Balancer tool coming into Encore.

**Comment by glynnis** [comment]
@megalord Is this still needed? If you all could submit a PR for this so it's available in the Framework that'd be awesome.

**Comment by megalord** [comment]
Yes, it's already in use.  I will submit a PR for it, but do you have any feedback on the color being used before I do?
![screen shot 2015-03-31 at 4 57 17 pm](https://cloud.githubusercontent.com/assets/5414922/6930245/06b42a0e-d7c7-11e4-8600-11a14c730cc6.png)

**Comment by glynnis** [comment]
@megalord That color looks fine for now. @ElementE and I have grand ideas about de-duping colors and cleaning up a bit, but it might be a while :grin: so go with what you have for now. If you can also update documentation in the styleguide that would be :ok_hand:
