### ISSUE TITLE
FontAwesome included multiple times with bad paths, creating browser issues

### ISSUE THREAD

**Issue by eric-dunham** [rackerlabs/encore-ui#774]
FontAwesome is currently included as a Bower dependency (`"font-awesome": "~4.1.0"`) and is also included in `src/rxApp/common.less` with:

    @import (less) 'demo/bower_components/font-awesome/less/font-awesome.less';
    @fa-font-path: 'font';

This is creating multiple declarations of FontAwesome, which is causing issues with rendering FontAwesome icons in certain browsers. As of this writing, I'm using Firefox Developer Edition 37.0a2 (2015-02-03) which isn't showing the issue, but "regular" versions of Firefox are still seeing the issue, and even versions that don't visually show the problem in the interface are still emitting errors in the console. The problem is that at least one of the paths isn't resolving in dependent applications, which appears to be causing Firefox's sanitizer to basically throw the whole thing out.

    downloadable font: rejected by sanitizer (font-family: "FontAwesome" style:normal weight:normal stretch:normal src index:1) source: <REDACTED_URL>/<REDACTED_APP_PATH>/styles/font/fontawesome-webfont.woff?v=4.1.0
    downloadable font: rejected by sanitizer (font-family: "FontAwesome" style:normal weight:normal stretch:normal src index:2) source: <REDACTED_URL>/<REDACTED_APP_PATH>/styles/font/fontawesome-webfont.ttf?v=4.1.0

After removing the `@import` from common.less, the issue appears to be resolved.

In order to combat the increasing number of versions of FontAwesome that are being included in dependent applications, I'm opening this issue so that a bulletproof top-level declaration of FontAwesome (e.g. using a CDN) can be included at the framework level, with application-level guidance being to depend on the framework, and not on FontAwesome.

**Comment by parlarjb** [comment]
@eric-dunham We already put a bunch of stuff on the CDN, as part deploying a new release of encore-ui, so it wouldn't be a big deal to also include FontAwesome in there, if that's what you mean.

**Comment by parlarjb** [comment]
And looking at our Cloud Files listing, we also have a `font` directory, which includes the FontAwesome fonts in it. It hasn't been updated since August though. I'm not sure if that means we changed the deploy process then, or maybe that that was the last time we changed our FontAwesome version number.

**Comment by eric-dunham** [comment]
@parlarjb I was hoping we could do something like http://fortawesome.github.io/Font-Awesome/get-started/ (check out the EASIEST section), but on our own CDN, as a LESS variable, so that we would get:

1. One customizable location for FontAwesome for any project using Encore UI (local, remote, relative, absolute, whatever)
2. Get it out from behind an authentication wall
3. One version, and the guideline would be for dependent application to remove explicit dependencies on FontAwesome

**Comment by parlarjb** [comment]
FontAwesome is no longer bundled with the framework.
