### ISSUE TITLE
Ship nav directives separately from Encore-UI

### ISSUE THREAD

**Issue by parlarjb** [rackerlabs/encore-ui#780]
Currently, any directive that will appear in the nav menu has to be part of encore-ui. This causes problems when we want to introduce a _new_ nav directive, as it means all encore-ui products have to update to a newer version of the framework to get it. While the nav itself is kept outside, the directives it needs aren't.

What if we move all these directives (`rxAppSearch`, `rxAccountUsers`, etc.) out of encore-ui, and deploy them all together into a single Javascript file. This file will be on a server somewhere, and loaded in by products at run time, *not* at package/build/deploy time. 

This means that all the products will "automatically" get the new nav directives when they load, much like how they automatically get the nav menu JSON when they load.

We'd have to be careful/strict about what dependencies these directives are allowed to use, as we'd have to know 100% that the dependency is available in all products.

cc @chriscantu @halkon @CITguy @velveteer

**Comment by halkon** [comment]
As an idea, totally :+1: :+1:  :+1: :+1: :cat: :cat2: :joy_cat: :smile_cat: :100: :1234: :8ball: :crown: 

Questions I have are mostly implementation curiosities: 

* Served by a server, like our production server, or a CDN?
* Would it be better as a bower component? (The answer should be no, to never deal with deployment issues)
* Would this replace the nav `.json` and instead just return angular modules (or even plain javascript objects)? 
* Should we start implementing rules as to what these directives do?  (I.e. should only change the `$location.path`) in order to limit the dependencies they could incur?  (Honestly I don't see these directives needing many dependencies, but, hey, I haven't messed with the nav in a while)

Granted, this is something that won't happen for a while, and I'm curious as to hear other ideas/thoughts/questions.  That was just what came to mind

**Comment by parlarjb** [comment]
* I *think* we could put it on the CDN without issue. As long as it's all encrypted, we don't have to worry about different domains for `<script>` loaded files, right? I'd be happy to have it go to our production servers instead though.
 * No as a bower component.
 * Replacing the nav `.json` isn't something I'd considered, but it could potentially work too.
 * I think we'd have to have a pretty strict set of rules as to what the directives could do. They all just tend to do stuff with `$window` and other core Angular dependencies

**Comment by halkon** [comment]
* You're right, `<script>` loaded files will be ok.  Though your point made me think of security, given that these directives are not really doing much right now is great, but what about in the future?
* :raised_hands: :raised_hands: :raised_hands: :raised_hands: 
* Using one file for both, the nav, and the directives might be beneficial in terms of what we do/don't load
* I imagine if anything, most of the directives that in a sense that are "global" (i.e. Support Service search directive is only available when in the App), only access `$routeParams` or anything like that. (`rxEnvironment` even?).  So as long as we keep it that way, it's fine, I am more or less uneasy about allowing hard application/project dependencies on a global nav.

On that last point, my main concern is mainly that given the `supportService` dependency of the account bar.  @velveteer & I discussed about a possible re-factor/rename of module/services names but stepped back as that would require all projects to update)

**Comment by eric-dunham** [comment]
I'm curious, architecturally, as to why we couldn't separate these out completely, and why every application needs to know about the navigation?

Every application already knows its routes, and the risk we run by having every application know about every other application (via the nav) is exactly this sort of issue. We seem to have run into coupling concerns that we can architect around.

If we view the information architecture as, effectively, as separate component, then it seems to me like that needs to be the only component aware of how to smash all the applications's routes together.

That is to say, if we have `rxEncoreNav` (or whatever) that inherits styles and behavior from `rxNav`, it means that it is the only component/application that needs to be aware of the entire application ecosystem and how to glue them together. This would isolate nav-based changes to the framework (at an abstract level), and to the specific navigation we use internally (at an implementation level).

This, of course, would mandate that our specific nav could only be used for navigation, and not injecting things like non-standard search boxes, form elements, etc... ;-)

Even though this approach isn't feasible with the current architecture, I was wondering what the team's collective thoughts were around the current coupling concerns and how we can alleviate them in the future, as opposed to sort of pandering to them.

**Comment by parlarjb** [comment]
Injecting search boxes is precisely the problem. Currently, applications do not know what other products are available, that's all pulled in from a separate JSON file. But unfortunately the nav needs lots of additional functionality, beyond simply listing the available products.

We have search boxes, we have drop down selectors, radio buttons, etc.

**Comment by eric-dunham** [comment]
Yeah, I think that's my problem with the nav. :)

It seems to currently provide an inconsistent way to access functionality across applications, and if its purpose were simplified down to that of IA, it seems like we'd have fewer headaches (and more consistent locations for form controls, e.g. search boxes!).

And I suppose that's sort of the reason I was asking the question. I find a lot of value in dumbing down the nav to just be a nav. :P

**Comment by parlarjb** [comment]
The UX team will be coming in with a different view on how the nav should behave, but until they do that, we're not going to do any major restructures. I try to minimize the amount of work I know will be thrown away :)

That said, the problem as is exists, and I'd like to find a way to reduce this interdependency. The separate Javascript file might be the answer.

**Comment by CITguy** [comment]
So, I've been getting more and more questions on where to share some common directives that don't really belong in the framework (Rackspace-specific).  This functionality will be crucial for Cloud UI when we begin splitting it into smaller apps.  

What about setting up an internal `encore-ui-rax` repo to be deployed to our private bower registry?  

It would:

* house the navigation directives mentioned in this issue
* house any other Rackspace-specific directives that do not belong in the public framework
* directives defined under `encore.rax` module
* directives prefixed with `rax-` to differentiate from public framework directives

Thoughts/Comments/Concerns?

**Comment by parlarjb** [comment]
That's a different issue than what's being discussed here, but it's also a valid issue that we had a lot of discussion on early this year. Feel free to fire up a separate issue and we can discuss there

**Comment by CITguy** [comment]
Captured related conversation in #1123

**Comment by anur2213** [comment]
Associated Jira story: https://jira.rax.io/browse/FRMW-530
