### ISSUE TITLE
rxBillingSearch button needs height adjustment 

### ISSUE THREAD

**Issue by velveteer** [rackerlabs/encore-ui#782]
Because of the added options to the `rxBillingSearch` template, the entire div is now vertically expanded, which means that the magnifying glass image is going to expand to fill it (`height: 100%`): https://github.com/rackerlabs/encore-ui/blob/master/src/rxApp/rxApp.less#L398

The issue as it shows in the framework currently: 
![issue](https://cloud.githubusercontent.com/assets/3134804/6110188/a3cf5448-b045-11e4-99a3-6c56e0b58758.png)

This was how I fixed it in Billing-UI, but we need a better solution in the framework:
```
fieldset > .search-action { 
    height: 40% !important;
}
```

@glynnis Any ideas?

**Comment by CITguy** [comment]
The `<button>` within the `<fieldset>` is set to `position: absolute;` which is attaching on the first ancestor up the tree with a `position: relative;`.  In this case, the `<div class="rx-app-search">` is where the button is attaching its positions, not the `<fieldset>` (where it should be attaching). This can be corrected by adding `position: relative;` for the `<fieldset>`.  I can get a PR in shortly.

**Comment by CITguy** [comment]
@velveteer, was the 1.6.3 release satisfactory in resolving this issue?

**Comment by velveteer** [comment]
@CITguy Yep.
