### ISSUE TITLE
Upgrade to Font Awesome 4.3

### ISSUE THREAD

**Issue by glynnis** [rackerlabs/encore-ui#788]
Looks like we're using 4.1 (https://github.com/rackerlabs/encore-ui/blob/7c3c4c58f13abbcb9df472dfabbdea3e39ab8c6f/bower.json#L19)

4.3 provides some new icons (including one for servers) which would be nice to have available for new projects coming in.

Perhaps an upgrade could assist with issues we've seen associated with https://github.com/rackerlabs/encore-ui/issues/774?

**Comment by CITguy** [comment]
:+1: for upgrading to 4.3
