### ISSUE TITLE
rxSpinner pushes right floated parent elements

### ISSUE THREAD

**Issue by TheNando** [rackerlabs/encore-ui#791]
rxSpinner, as currently implemented, uses jQlite's 'prepend' function to insert a new dom element when toggled to show. This expands the width of the parent element.

This presents an issue when used in conjunction with Page Actions (or other right floated elements). In this case, a parent container is floated right, with left aligned child elements. If the longest element uses an rxSpinner, then toggling the spinner on will shift all the elements to the left to accommodate the spinner, or the spinner will appear on the next line, pushing the other elements down, depending on the styling of the parent container.

**Comment by glynnis** [comment]
Related JIRAs:
https://jira.rax.io/browse/EOD-308
https://jira.rax.io/browse/EN-1483
https://jira.rax.io/browse/EOD-280

**Comment by glynnis** [comment]
Move to UX JIRA so we can investigate loading patterns/design. Some of this is already underway on the design side.

**Comment by anur2213** [comment]
Related Jira story:
https://jira.rax.io/browse/FRMW-456
