### ISSUE TITLE
Examine design issue of multiple greys and disabled grey color matching encore background

### ISSUE THREAD

**Issue by glynnis** [rackerlabs/encore-ui#792]
The case of many greys! Right now there are a lot of them, and in the case of our color for "disabled" grey, there is not enough contrast for it to be used successfully on the context of the grey background we use for the body of all content pages.

Investigate, document, and propose possible solutions.

**Comment by kobowley** [comment]
Will solving this issue help with a solution for 758

**Comment by glynnis** [comment]
@kobowley I see #758 as related, since it does use gray as a color, but I think this issue isn't a blocker for #758. Rather, this issue is a really high-level design question (how we use colors in Encore), whereas #758 is a request for a specific new directive.

**Comment by CITguy** [comment]
Closing. Captured in JIRA https://jira.rax.io/browse/FRMW-87
