### ISSUE TITLE
Create copy field style

### ISSUE THREAD

**Issue by glynnis** [rackerlabs/encore-ui#795]
This has come up recently (in Billing with the Gateway Transaction Ref #) -- that there are sometimes pieces of data that are too long to display easily/cleanly in metadata, but that Rackers need to easily copy/paste.

For this reason, I think we could use a pattern like this, which can accommodate longer data, but also reduces the number of clicks for Rackers to copy/paste -- something I think they do frequently within Encore while serving customers.

![screen shot 2015-02-16 at 9 45 50 am](https://cloud.githubusercontent.com/assets/1529366/6214806/f8d92416-b5c0-11e4-92e3-883bd27d923e.png)

**Comment by CITguy** [comment]
How would something like this work for large amounts of text (read-only `<textarea>`)?

**Comment by glynnis** [comment]
One thing to note: we would need to document this heavily re: when to use a copy box like this, and when data on the page would suffice. Likely would need research to support those cases, and a list of criteria to easily identify when to use this vs. something else.

@CITguy I hadn't thought about uses for something large like `<textarea>` -- I've never seen a pattern like this utilized for something like that in the wild, but that doesn't mean it couldn't be. Is there a case in Encore that you're aware of? It seems like large amounts of text like that (and the need to copy them) may be present in places like ticketing, perhaps for something kind of akin to block quotes, where a Racker needs to transfer some comment or discussion between one tool and another. Can you think of others?

My initial vision for something like this is for long single lines of text -- things like URLs, UUIDs, etc. that are always copy/pasted due to their length and propensity for introducing user error if not copied directly.

**Comment by chriscantu** [comment]
@glynnis FYI: I think most implementations of copying to the clipboard require 'Flash'.  The pattern I have seen in Google products is to present them with a prompt with the text highlighted.  The user is then required to press Ctrl+C or Command+C.

**Comment by glynnis** [comment]
@chriscantu Ah, good to know. Thanks for the heads up.

**Comment by chriscantu** [comment]
@glynnis I forgot to include an example of the pattern.  Here is a reference for posterity.  http://goo.gl

**Comment by CITguy** [comment]
@glynnis, I've not seen it in Encore, but I've seen it in use within DCX. There are places where the user needs to copy information from a sanitized device config (which can be many lines long).

**Comment by eric-dunham** [comment]
I know I'm late to the party because I was out last week, but we could consider using ZeroClipboard, a la GitHub: https://github.com/blog/1365-a-more-transparent-clipboard-button (which uses Flash). Or we could do the "safer" approach and just add a `this.select();` to a focus listener on an input element...?

**Comment by CITguy** [comment]
I'd like to avoid using flash if possible. Additionally, the clipboard API isn't fully supported yet ([caniuse clipboard](http://caniuse.com/#feat=clipboard)), so I'd feel better going with the selection approach and display a tooltip for the user to <kbd>CTRL</kbd>/<kbd>CMD</kbd>+<kbd>C</kbd>.  Once the clipboard API is better supported, we can then change the behavior to support the API.

**Comment by glynnis** [comment]
Relevant non-flash support for this: http://updates.html5rocks.com/2015/04/cut-and-copy-commands

Not sure of the best way to get around this:
> Firefox supports this but requires a preference change (See cut and copy commands here). Without 
> this Firefox throws an error.

...but I think it's worth getting creative about it since this is something we see requested frequently in feedback.

**Comment by CITguy** [comment]
Yeah, that looks promising. It's unfortunate that it's behind a preference flag on Firefox, but this looks like our best non-flash option.

**Comment by julianbonilla** [comment]
This is awesome, but might need some more work: http://tbranyen.com/post/clipboard-hijacking-with-html5

**Comment by CITguy** [comment]
According to release notes for [Firefox 41](https://developer.mozilla.org/en-US/Firefox/Releases/41) under "HTML Editing API", `Document.execCommand()` will be supported without enabling a flag.

Firefox 41 is due to release on Sept. 22, 2015

**Comment by glynnis** [comment]
Move to UX JIRA for design. Might need a dev SPIKE in Framework JIRA too to determine what is possible before design works on this? cc/ @CITguy

**Comment by anur2213** [comment]
Related Jira story:
https://jira.rax.io/browse/FRMW-455
