### ISSUE TITLE
rxModalAction hide submission buttons

### ISSUE THREAD

**Issue by megalord** [rackerlabs/encore-ui#799]
In [this PR](https://github.com/rackerlabs/encore-cloud-ui/pull/465) to Encore Cloud, there is a new UX pattern in which the footer buttons are hidden once the form is submitted.  This prevents a user from exiting the modal while the process is ongoing.  Once the process has completed, a blue return button is displayed, allowing the user to return to the application.

This pattern is useful any time an operation does not complete when the initial request returns, and its status must be polled instead.

Example:
![blue return button](https://cloud.githubusercontent.com/assets/9376/6113847/1dc6e92e-b068-11e4-826f-aaedef20e8ad.png)

**Comment by glynnis** [comment]
+1 getting this in the Framework

**Comment by megalord** [comment]
I'll give it a go.
