### ISSUE TITLE
Documentation Exposing Internal Routes

### ISSUE THREAD

**Issue by CITguy** [rackerlabs/encore-ui#802]
The `rxApp` demo in the [public docs](http://rackerlabs.github.io/encore-ui/#/component/rxApp) is exposing internal routes via the "Standard rxApp" navigation.

This is a security risk and should be removed from public documentation.

**Comment by CITguy** [comment]
This is probably related to  #697.

**Comment by anur2213** [comment]
Associated Jira story: https://jira.rax.io/browse/FRMW-529
