### ISSUE TITLE
Support for multi-screen modals

### ISSUE THREAD

**Issue by glynnis** [rackerlabs/encore-ui#814]
There are several use cases recently for multi-screen modals, i.e. modals that have several screens they progress through before a submit/close action is done. Think "wizard".

For an example of the kind of behavior I'm talking about: http://simpulton.github.io/angularjs-wizard/

There are three use cases for this in Encore currently:
- Batch actions in Cloud already does this (somewhat inelegantly according to @parlarjb :wink: )
- LBS has a similar implementation to Cloud's batch actions
- A use case has come up for making a payment/commenting on a payment in EOD

**Comment by parlarjb** [comment]
The demo comes from this blog post: http://onehungrymind.com/build-angularjs-wizard-redux/
