### ISSUE TITLE
Create UX/visual design for collapsible divs

### ISSUE THREAD

**Issue by glynnis** [rackerlabs/encore-ui#824]
This has come up specifically for filters, but we should design a pattern that allows any div to be collapsed (not just filters).

Look, feel, and interaction design for this is specified in:
https://projects.invisionapp.com/d/main#/console/2965787/66281327/comments/31724169
https://projects.invisionapp.com/d/main#/console/2965787/66342618/comments/31724257

When this gets added to the Framework @velveteer, let's make sure we update the filter box in Transaction Details (Billing Tabs design)

**Comment by glynnis** [comment]
See https://github.com/rackerlabs/encore-ui/issues/218

**Comment by CITguy** [comment]
@glynnis is this issue still valid considering the inclusion of `rxCollapse`?

**Comment by glynnis** [comment]
@CITguy ah, should've been closed on merge. Closing.
