### ISSUE TITLE
Add border to tabs element

### ISSUE THREAD

**Issue by glynnis** [rackerlabs/encore-ui#830]
This is something we discussed with Nordquist -- adding a small blue border around tabs will help provide context to the user that they're still within a tab content area even they're scrolling.

@ElementE will comment with a screen shot.

**Comment by ElementE** [comment]
![billing_tabs_border](https://cloud.githubusercontent.com/assets/7989545/6473790/4ebc720a-c1c1-11e4-99cd-522293a84dc2.png)

**Comment by glynnis** [comment]
Closed by #887
