### ISSUE TITLE
Provide a way to disable an rxModalAction

### ISSUE THREAD

**Issue by parlarjb** [rackerlabs/encore-ui#837]
Currently there's no built-in way to disable rxModalAction links. Some projects do it via CSS, like so:

```
rx-modal-action.link-disabled {
  pointer-events: none;
  a {
      color: #D5D3D3;
  }
  .rx-spinner {
    margin-left: 10px;
    border-bottom-color: #D5D3D3;
    border-right-color: #D5D3D3;
  }
}
```

with

```
<rx-modal-action
            ng-class="disableAction(server.task_state) ? 'link-disabled' : 'msg-info'"
```

but we should natively provide something. As it stands, `ng-disabled` is ignored by the directive.

**Comment by glynnis** [comment]
@CITguy Didn't some of this work go up recently for PR review? Wondering if this can be closed or if this is a separate issue.

**Comment by CITguy** [comment]
Yes, this can be closed. I'll reference this issue in the current JIRA story.
