### ISSUE TITLE
Add documentation for preferred time format

### ISSUE THREAD

**Issue by glynnis** [rackerlabs/encore-ui#840]
...to ensure consistency where possible. Date format should be:
> Mar 2, 2015 @ 15:40 (UTC-0600)

Three letter month, military time, with UTC in parens.

See https://jira.rax.io/browse/EN-1646 for context on this.

**Comment by chriscantu** [comment]
:+1: for standards!

**Comment by leonels** [comment]
:+1: yey conventions!

**Comment by chriscantu** [comment]
@glynnis Should there be a hover / tool tip like feature which displays the UTC date?  I think UTC-6 & military is also very engineering based.  We also have Billing Rackers who may want a more consumer friendly date.  What do you think about ? 

```
Mar 2, 2015 @ 03:40 PM (CST) 
```

**Comment by glynnis** [comment]
From an email from Omar:
> For consistency sake, we can move forward with this ("Mar 2, 2015 @ 15:40 (UTC-0600)"). Lane 
> created the following Jira to track where we need to update and provided the sections that need to be 
> updated. 

Related issue on the UX board, which documents all the places we use time in Encore (thank you @lfielder :clap: :clap: :clap: :clap:): https://jira.rax.io/browse/UXENCORE-216

@chriscantu Re: whether Billing Rackers might prefer "03:40 PM (CST)" over a format like "Mar 2, 2015 @ 15:40 (UTC-0600)", we've also gotten requests for time to be displayed in UTC. Especially once we throw international Rackers into the mix, I think the larger issue at hand here may be that we have a real need for the ability for a user to set preferences. See JIRA for prior discussion about this feature: https://jira.rax.io/browse/UXENCORE-178

I agree with Omar that we need to decide on something and be consistent until User Preferences can be developed, but the question is which is best. I'll include this comment in a reply to his email I quoted above and see if there's a chance we can do a little research before choosing The One True Format to use until User Preferences is a thing.

**Comment by chriscantu** [comment]
@glynnis I agree.  User preferences is ideal.  Can we start tagging issues that user preferences would solve?  This tagging would allow us to asses the ROI for the feature.

**Comment by glynnis** [comment]
I created a label in JIRA for user preferences stories: https://jira.rax.io/browse/UXENCORE-216?jql=labels%20%3D%20UserPreferences

So far I've only added two of them to the label, but I'll add others as I come across them.

**Comment by glynnis** [comment]
As of 4/8, Omar is going to follow up on this with some examples so we can properly document.

**Comment by omargonzalez** [comment]
In anticipation of user preferences, let's go ahead and create a standard across our properties.  

ISO 8601 (date and time values ordered from the largest to smallest unit of time):

2015-04-09T12:36:29-5:00

We'll be reaching out to customers for feedback and decided on a strategy going forward in the very near future.
