### ISSUE TITLE
Add styles for new loading overlay treatment

### ISSUE THREAD

**Issue by glynnis** [rackerlabs/encore-ui#843]
A new loading treatment has been implemented in the framework for server-side pagination (see https://github.com/rackerlabs/encore-ui/issues/739), but we also need styles to be flexible and adoptable on a more general level.

See design here:
https://projects.invisionapp.com/d/main#/console/2965787/66282398/comments/31976182

**Comment by glynnis** [comment]
Tagging @velveteer since he's done some custom implementation of this for Billing that we could draw on when bringing styles into the Framework.

**Comment by glynnis** [comment]
Here's the EOD JIRA for this work: https://jira.rax.io/browse/EOD-642

Moving out of "priority:soon" since nothing exists in the Framework yet to document.

**Comment by Gustavo-Arellano** [comment]
@glynnis Per meeting yesterday and as requested by Kerry, please close this. I don't seem to have security privileges to do so. Thank you
