### ISSUE TITLE
Add table filtering directive

### ISSUE THREAD

**Issue by glynnis** [rackerlabs/encore-ui#844]
Add table filtering directive to the framework that has functionality for clearing the filter within the input box (rather than as a separate button which can be mistaken as a submit button). This will make for a cleaner UI and eliminate the issue we're having with table filters currently where "clear" buttons aren't close to the filter box or are mistaken for submit buttons.

@ElementE and I will add mock-ups here soon.

**Comment by glynnis** [comment]
This is blocking https://jira.rax.io/browse/EN-1718

**Comment by glynnis** [comment]
Also part of this: unifying filter text (copy and size) across Encore. Once this is in the Framework, we need to document everywhere filters are used and create JIRAs to make sure they all get updated.

**Comment by glynnis** [comment]
Got a design for this:
![screen shot 2015-04-07 at 11 55 36 am](https://cloud.githubusercontent.com/assets/1529366/7028750/8f19ce52-dd1d-11e4-9a4e-8182638a57b3.png)

The above mock-up illustrates the various states of the filter box (and eliminate the need for a "clear filter" button altogether):
1) before user clicks in input and types something (on load)
2) user has begun entering text, X appears
3) user has entered really long text, letters move left as in current implementation, but text doesn't go far enough right to overlap X (that way the user always sees the letters they have most recently typed, as is the case by default with text inputs)

**Comment by glynnis** [comment]
Colors:
"Filter by any..." = #a9a9a9
User entered text = #555
X = `fa-times-circle` (http://fortawesome.github.io/Font-Awesome/icon/times-circle/) #a9a9a9

**Comment by CITguy** [comment]
@glynnis, should the border around it be the same as the "X" color?

**Comment by glynnis** [comment]
@CITguy Border should be whatever is the default for input fields within the Framework (i.e. it shouldn't be customized for just this directive).

Very aware that we still have a 50 shades of grey problem, which I'm working on slowly but surely :sweat_smile:  Plans are to normalize colors soon, there are just some other pieces that we need in place first.

**Comment by CITguy** [comment]
Should this be `rxSearchBox` so that it can be used in places other than table filtering?

**Comment by glynnis** [comment]
Sounds good to me! I'll let some other devs chime in, though.
