### ISSUE TITLE
Add documentation/demo for stacked progress bars

### ISSUE THREAD

**Issue by glynnis** [rackerlabs/encore-ui#857]
Angular Bootstrap has something like this:
![screen shot 2015-03-20 at 2 22 41 pm](https://cloud.githubusercontent.com/assets/1529366/6759254/a83e0886-cf0c-11e4-8086-8d22123290b4.png)

We should be able to add it easily to the framework, but @ElementE and I need to discuss color considerations and how we want to document logic/use cases for this.

**Comment by CITguy** [comment]
Considering the incompatibility found with `angular-bootstrap` and angular 1.3 (see [#580 comment](https://github.com/rackerlabs/encore-ui/issues/580#issuecomment-74161480)), I'm hesitant to keep adding things from that project if we want to upgrade to angular 1.3.  

I'd like to know of the applied use cases before we proceed much further in discussion.

**Comment by glynnis** [comment]
@CITguy There aren't currently use cases for stacked progress bars, but given that Angular Bootstrap is already being utilized for regular progress bars (which has already been released in the Framework), adding documentation around stacked bars seems like a no-brainer. After speaking with @parlarjb, I believe stacked bars are already supported by the Framework, we just haven't documented them properly yet.

If there is a question about whether or not we should upgrade/re-write progress bars because of the Angular 1.3 issue, I think you should file a separate issue for that, given that this one is primarily a design/documentation concern (and the functionality already exists). Does that work for you?

**Comment by CITguy** [comment]
Ok, I didn't know if this was to add additional functionality or document existing functionality. FWIW, it's super simple to create a progress bar from scratch: http://jsbin.com/sumemo (built in about 10 minutes).

**Comment by glynnis** [comment]
Gotcha. Changed the title so that this issue is a bit more clear. FWIW, I'm fine updating and switching to a different implementation for progress bars provided visual appearance and current functionality is preserved :+1:

**Comment by glynnis** [comment]
This duplicates #863, and #863 has a but more info about what's needed, so I'm closing this one.
