### ISSUE TITLE
Bring rxSwitch into the framework, add to docs

### ISSUE THREAD

**Issue by glynnis** [rackerlabs/encore-ui#860]
Currently the directive is in Billing.

![screen shot 2015-03-23 at 11 13 23 am](https://cloud.githubusercontent.com/assets/1529366/6784438/ab51b28c-d14d-11e4-8c44-89228a5baa7d.png)

**Comment by parlarjb** [comment]
Courtesy of @Droogans https://github.com/rackerlabs/encore-ui/tree/rx-switch
