### ISSUE TITLE
Improve flexibility of deployment system

### ISSUE THREAD

**Issue by parlarjb** [rackerlabs/encore-ui#861]
Currently when we want to deploy, we _have_ to deploy from `master`, and we are limited to `major`, `minor` and `patch` version updates.

The main issue we have with this is if, for example, our latest release is `1.10.0`, but some product X is on an older version, say `1.9.4`. A bug is found that X needs a fix for, but they're not in a situation where they could update to a potential `1.10.1` to pull in the fix (i.e. `1.10.0` added some breaking changes that they're not prepared to account for yet)

At a minimum, we need a way to do new releases based off of any arbitrary past release. Ideally we'll also support release candidates, and having Travis automatically build and ship sha releases for every pull request (i.e. a green PR will automatically ship `1.10.0-sha-3j2mn3` to npm)

cc @CITguy @Droogans

**Comment by Droogans** [comment]
https://www.npmjs.com/package/git-repo-version#usage

This handles the generation of sha releases quite easily.
