### ISSUE TITLE
Document colors and implementation for stacked progress bars

### ISSUE THREAD

**Issue by glynnis** [rackerlabs/encore-ui#863]
@scadams has a use case for stacked bars, which have the following look/feel and color logic:

![pasted_image_at_2015_03_23_03_18_pm](https://cloud.githubusercontent.com/assets/1529366/6790950/67db4cbc-d179-11e4-8a37-850de4dcf19c.png)

green for success
red for failure
grey for pending
orange for cancelled (like a "warning")

@scadams has a need for colors that represent: pending, success, failed, cancelled for tickets, and pending, delivered, rejected, failed for emails.

**Comment by scadams** [comment]
@glynnis, one additional status for emails is 'pending'

**Comment by scadams** [comment]
@glynnis, one additional status for emails is 'processing'

**Comment by scadams** [comment]
We found a colorblind-safe scheme for our colors. This is what we are now using:

![colorblind-safe-progressbars](https://cloud.githubusercontent.com/assets/753260/9341837/dd008738-45bd-11e5-93b5-2941974c3491.png)

**Comment by CITguy** [comment]
Aside from the FG/BG contrast, the color difference works for me (having strong deuteranomaly). I'd use white text foreground for the dark blue and red backgrounds.

**Comment by scadams** [comment]
Yeah, was thinking the same thing, thanks.
