### ISSUE TITLE
Correct highlighting rending when text overflows container

### ISSUE THREAD

**Issue by TheNando** [rackerlabs/encore-ui#865]
The rxCharacterCount directive highlights character which exceed the set limit. This works correctly unless the height of the content exceeds the height of the input/textarea container. When that happens, the highlighting misaligns and overflows past the contents of the container.

![highlight_overflow](https://cloud.githubusercontent.com/assets/6663710/6835019/e34fffae-d305-11e4-947d-bc61668af4ac.gif)

**Comment by anur2213** [comment]
Related Jira story:
https://jira.rax.io/browse/FRMW-454
