### ISSUE TITLE
rxAppRoutes: Add support for activating navigation item using base url

### ISSUE THREAD

**Issue by julianbonilla** [rackerlabs/encore-ui#866]
We have a use case where a single navigation item should be activated for many routes.  For example, these routes:

```
/billing
/billing/overview/123
/billing/search
/billing/trasactions
...
```

Should all fallback to activating the `billing` navigation item, if there is no exact match for the route.

/cc @velveteer @parlarjb

**Comment by parlarjb** [comment]
When you say "activated", what do you mean?

**Comment by julianbonilla** [comment]
@parlarjb I mean it should be highlighted

**Comment by julianbonilla** [comment]
Didn't realize this feature was already supported in `rxAppRoutes` :+1:
