### ISSUE TITLE
Support the concept of release candidates

### ISSUE THREAD

**Issue by parlarjb** [rackerlabs/encore-ui#876]
(Originally part of #861)

Ideally we'll support release candidates, and have Travis automatically build and ship sha releases for every pull request (i.e. a green PR will automatically ship 1.10.0-sha-3j2mn3 to npm). @Droogans noted https://www.npmjs.com/package/git-repo-version#usage for generating sha versions.

I'll note that I tried to do sha releases in the PR that closed #861, but `grunt bump` behaves quite oddly when generating sha version numbers.

**Comment by anur2213** [comment]
Related Jira story:
https://jira.rax.io/browse/FRMW-453
