### ISSUE TITLE
Create Metadata Directives

### ISSUE THREAD

**Issue by CITguy** [rackerlabs/encore-ui#885]
The current `metadata` CSS class on a definition list `<dl>` is no longer cutting the mustard.

* CSS hacks are required to correct the way that certain browsers select text on double-click (see #870 and #871)
* With the desire to move more toward flexbox-based layouts, a definition list does not contain enough markup to cleanly separate flex containers and flex items.
* Framework consumers have to update their markup to match framework recommendation (this should be handled by the framework via directives).

I propose we create `rxMeta` and `rxMetaItem` directives to be used as such:

```html
<rx-meta>
  <rx-meta-item label="foobar">
    out of working order; seriously, perhaps irreparably, damaged
  </rx-meta-item>
  ...
</rx-meta>
```

With the addition of these directives, we should deprecate the definition list styling (i.e. the `.metadata` CSS class) and steer developers to use the directives. The directives serve three purposes:

1. Simplify source markup for developers
2. Remove browser CSS hacks for proper functionality.
3. Framework has full control over layout. If we wanted to switch to a table-based layout, or back to a definition list, consumers wouldn't need to rework their markup once they're using the new directives.

This would initially be a MINOR level release as it would be adding the new directives, but won't break existing `dl.metadata` source code. It should be made very clear in the documentation, stakeholders mailing list, and the stakeholder meeting that the `.metadata` class **will be removed** on the *following* MAJOR-level release.

**Comment by glynnis** [comment]
:+1: Let's do this!

**Comment by CITguy** [comment]
We've already encountered a bug with Chrome regarding the CSS hacks.

Below, the *Nickname* and *Image* labels both contain blank values, but Chrome isn't honoring the CSS rules to properly align values to their label.
![screen shot 2015-05-05 at 4 35 24 pm](https://cloud.githubusercontent.com/assets/545605/7483468/d7e2b6ca-f344-11e4-8035-66217eab2308.png)

This happens infrequently and is difficult to replicate, but it goes to show that we need to look into creating proper markup for metadata lists via framework directives.

**Comment by CITguy** [comment]
FYI: The source code for the screenshot above is littered with `ng-if` attributes to show/hide certain attributes, which may be interfering with the CSS.

```html
<dl>
  <div ng-if="foobar">
    <dt>foobar</dt>
    <dd>out of working order; seriously, perhaps irreparably, damaged</dt>
  </div>
  <div ng-if="whizbang">
    <dt>whizbang</dt>
    <dd>blah blah blah</dd>
  </div>
</dl>
```
but the markup should better support `ng-if` so it can be simplified to the following:
```html
<rx-meta>
  <rx-meta-item label="foobar" ng-if="foobar">
    out of working order; seriously, perhaps irreparably, damaged
  </rx-meta-item>
  <rx-meta-item label="whizbang" ng-if="whizbang">
    blah blah blah
  </rx-meta>
</rx-meta>
```

**Comment by glynnis** [comment]
Marked this "Needs Design" and "on hold" to indicate that this is currently being worked on by design, so any dev work here should wait until we deliver mock-ups.

**Comment by CITguy** [comment]
See #964 for potential PR (can be tweaked based on design decisions).
