### ISSUE TITLE
rxBreadcrumbs / rxCharacterCount bug in V1.11.0+

### ISSUE THREAD

**Issue by scadams** [rackerlabs/encore-ui#895]
This issue is a little difficult to describe, and I can only reproduce it on one page in the Flashmob UI so far, and the bug occurs with V1.11.0 and V1.12.0 so far.

We are currently on V1.10.0 in our staging and production environments, where the bug does not occur, but we won't be able to upgrade until it's fixed.

On the Flashmob New Notification page, https://staging.encore.rackspace.com/mass-ticketing/notifications/new , if the "Notifications" bookmark is clicked, the page is supposed to navigate to /mass-ticketing/notifications. (Again, it currently works in staging because it's on V1.10.0).

![image](https://cloud.githubusercontent.com/assets/753260/7098443/0fdccb68-dfa6-11e4-954b-f3cc97cc0868.png)

When upgrading to V1.11.0, the page does not navigate back to the Notifications page, and instead shows this:

![image](https://cloud.githubusercontent.com/assets/753260/7098451/2b34721c-dfa6-11e4-8168-e17ad5d40ea7.png)

The following error is displayed in the console:
```
RangeError: Maximum call stack size exceeded
    at join (native)
    at formatError (http://localhost:9000/mass-ticketing/bower_components/angular/angular.js:10098:16)
    at http://localhost:9000/mass-ticketing/bower_components/angular/angular.js:10124:23
    at forEach (http://localhost:9000/mass-ticketing/bower_components/angular/angular.js:325:18)
    at Object.error (http://localhost:9000/mass-ticketing/bower_components/angular/angular.js:10123:11)
    at $get (http://localhost:9000/mass-ticketing/bower_components/angular/angular.js:7398:18)
    at Scope.$get.Scope.$broadcast (http://localhost:9000/mass-ticketing/bower_components/angular/angular.js:13095:15)
    at Scope.$get.Scope.$destroy (http://localhost:9000/mass-ticketing/bower_components/angular/angular.js:12748:14)
    at HTMLInputElement.<anonymous> (http://localhost:9000/mass-ticketing/bower_components/angular/angular.js:6168:62)
    at http://localhost:9000/mass-ticketing/bower_components/angular/angular.js:2853:10
angular.js:10126 TypeError: Cannot read property '$$nextSibling' of null
    at Scope.$get.Scope.$broadcast (angular.js:13105)
    at Scope.$get.Scope.$destroy (angular.js:12748)
    at cleanupLastView (angular-route.js:839)
    at angular-route.js:872
    at publicLinkFn (angular.js:6041)
    at $get.boundTranscludeFn (angular.js:6166)
    at controllersBoundTransclude (angular.js:6773)
    at update (angular-route.js:865)
    at Scope.$get.Scope.$broadcast (angular.js:13093)
    at angular-route.js:547
```

The breadcrumb code in the controller is pretty straight-forward:
```
rxBreadcrumbsSvc.set([{
    path: '/mass-ticketing/notifications',
    name: 'Notifications'
}, {
    name: 'New Notification'
}]);
```

If there's any other info I can provide, please let me know.

**Comment by megalord** [comment]
@scadams The only change to `rxBreadcrumbs` in the last four months was to test code, so the error has to be coming from somewhere else.  I see `HTMLInputElement` in the stack trace, and I noticed you're using `rxCharacterCount` on the page.  We've had some issues with that directive in the past, and I have an inkling that it isn't properly tearing down when you try to navigate away.  I'll see if I can mock up the page and reproduce the bug.

**Comment by megalord** [comment]
I created a super simple page locally and reproduced the error.
```javascript
<rx-page title="'Layout 4'" subtitle="'Sample Create Page'">
      <input type="text" rx-character-count ng-model="model" />
</rx-page>
```
I figured out that [this line](https://github.com/rackerlabs/encore-ui/commit/c70e340bf6571630ed784627927824f16fa720a1#diff-0f86ca87145fc3a8b627aa6632d6ac19R97) in `rxCharacterCount` is the cause of the issue.  For some reason, it's causing an infinite loop (as best I can tell) of `$destroy` events.  @parlarjb, do you remember why that was added? I know directives should clean up after themselves (DOM events, etc.), but removing the element seems overkill.

To make things even weirder, wrapping the `input` with a `<div />` (or anything that isn't a directive) will circumvent the issue.  @scadams, if you need to upgrade before waiting for the next release, I suggest that as a temporary fix.

**Comment by parlarjb** [comment]
The `wrapper.remove()` was added to remove the wrapper :) It only happens when the `scope` is destroyed, so it _should_ be the case that we only try to remove the wrapper whenever the original marked-up textarea/input is being destroyed (usually via an `ng-if`). I'll look into it.

**Comment by scadams** [comment]
Thanks for the temporary fix, @megalord, I'll do that for now.

**Comment by anur2213** [comment]
Related Jira story:
https://jira.rax.io/browse/FRMW-452
