### ISSUE TITLE
currencyToPennies negative values has a possible bug.

### ISSUE THREAD

**Issue by Droogans** [rackerlabs/encore-ui#898]
https://github.com/rackerlabs/encore-ui/blob/b2d27a3c20e0a192e6bc393d0efb5dd673efce9c/src/rxForm/rxForm.page.js#L170

This should be

```js
if (_.first(currencyString) === '(' && _.last(currencyString) === ')')
```

The current code accepts opening and closing parens in any place in the string. It should be more explicit.

**Comment by anur2213** [comment]
Related Jira story:
https://jira.rax.io/browse/FRMW-451
