### ISSUE TITLE
rxForm.create

### ISSUE THREAD

**Issue by Droogans** [rackerlabs/encore-ui#904]
I hate writing out forms....they look so ugly....

```js
txtName: {
    get: function () {
        return element(by.model('formData.name'));
    }
},

name: {
    get: function () {
        return this.txtName.getAttribute('value');
    },
    set: function (input) {
        this.txtName.clear();
        this.txtName.sendKeys(input);
    }
}
```

All of that boilerplate enables the use of `rxForm.fill`, a really useful function for auto-form filling via POJOs, but the amount of boilerplate needed to generate boring form getters and setters sort of prohibits its use for most people.

That would all change if instead I could replace the above code with

```js
name: rxForm.create.textField(element(by.model('formData.name')));
```

Whether or not this would include a side effect of adding a `txt{{PROPERTY_NAME}}` web element property to the page object is still up for debate.

The following web elements need to have their boilerplate supported:

text fields (`txt`-prefixed web elements)
checkbox fields (`chk`-prefixed web elements)
radio fields (`rad`-prefixed web elements)
dropdown fields (`sel`-prefixed web elements)

rxOptionFormTable would not be included.

**Comment by megalord** [comment]
I encountered the same frustration and wrote a utility that I've been using for awhile.  I got a little fancier than I should have by auto generating the page's properties, so my approach is not generic enough to put in the framework, but maybe it will be of some use.
```coffeescript
helpers =
  defineInput: (obj, type, name) ->
    setter = (type, eleName) ->
      switch type
        when "txt"
          (value) ->
            @[eleName].clear()
            @[eleName].sendKeys value
        when "sel"
          (option) -> encore.rxForm.dropdown.initialize(@[eleName]).select option
        when "chk"
          (enable) ->
            checkbox = encore.rxForm.checkbox.initialize @[eleName]
            if enable then checkbox.select() else checkbox.unselect()
        else
          -> throw new Error "Setter not defined for type #{type}."

    getter = (type, eleName) ->
      switch type
        when "sel"
          -> encore.rxForm.dropdown.initialize(@[eleName]).selectedOption.text
        else
          -> @[eleName].getAttribute "value"

    # type is optionally an array of [type, name] arrays
    if _.isArray type
      @defineInput obj, inputType, name for [inputType, name] in type
    else
      sanitizedName = name.replace /[^\w]/g, '_'
      eleName = _.str.camelize "#{type}_#{sanitizedName}"
      obj[eleName] =
        get: ->
          $("rx-form-item[label=\"#{name}\"]")
          .$(if type is "sel" then "select" else "input, textarea")
      obj[_.str.camelize sanitizedName] =
        get: getter type, eleName
        set: setter type, eleName

pageProto = {}
helpers.defineInput pageProto, [
  ['txt', 'Name']
]
page = Page.create pageProto

# page.txtName
# page.Name
```

**Comment by glynnis** [comment]
@Droogans @CITguy Does this relate to #884? Or are they orthogonal?

**Comment by Droogans** [comment]
Nope. All of it is page objects stuff for end to end testing.

**Comment by glynnis** [comment]
:+1: Thanks for clarifying.

**Comment by CITguy** [comment]
Agreed with @Droogans
