### ISSUE TITLE
Document Encore favicon usage and requirements

### ISSUE THREAD

**Issue by glynnis** [rackerlabs/encore-ui#905]
Right now we expect all areas of Encore to utilize the Encore logo as the favicon, but that expectation isn't properly documented for teams coming in to utilize the Framework.

@CITguy @parlarjb Is this also something that should be added to work you've been doing with templates and generators?

This came up in discussion with the Flashmob team. cc/ @scadams

**Comment by julianbonilla** [comment]
@glynnis Both projects have PRs for the favicon.
https://github.com/rackerlabs/encore-ui-template/pull/143
https://github.com/rackerlabs/generator-encore/pull/44

**Comment by CITguy** [comment]
Yeah, the generator has it as of version 0.3.3

**Comment by glynnis** [comment]
@CITguy @julianbonilla What! Of course. You guys are always two steps ahead of me :heart: :bow: 

I'll use this issue to get the favicon mentioned/documented properly in our style guide, then.

**Comment by CITguy** [comment]
Closing. Captured in JIRA https://jira.rax.io/browse/FRMW-62
