### ISSUE TITLE
Create a "save" feature

### ISSUE THREAD

**Issue by glynnis** [rackerlabs/encore-ui#907]
An emerging need in Encore applications is the ability to manually or auto-save progress while completing forms.

We need a visual/interactive pattern for this, including decisions around:
- visual treatment
- placement
- interactive design
- whether manual vs. auto is an option

Also needs to be added as a component or reusable style in the framework. @megalord has some work already put in on this in an application, but not at the Framework level.

cc @megalord @ElementE @parlarjb

**Comment by megalord** [comment]
Here's an example of our current usage:
![screen shot 2015-04-20 at 3 01 26 pm](https://cloud.githubusercontent.com/assets/5414922/7239272/2ffeaea0-e76e-11e4-99c9-643aabf89f24.png)

One of the big concerns is how this will be placed relative to page actions.

**Comment by glynnis** [comment]
@megalord I've added you to this InVision project, where you can see comments explaining interaction design for this: 
https://projects.invisionapp.com/d/main#/console/3423206/75013336/comments

I spoke with @parlarjb and he says we can follow an example from Cloud in the code/back end:
![screen_shot_2015-04-24_at_5 03 51_pm_720](https://cloud.githubusercontent.com/assets/1529366/7328982/afc19286-ea9f-11e4-9835-ee2926b0d0f9.png)

The above notification is not caused by some error/warning/success condition taking place. Instead, it’s “hard-coded” into the page, and only displayed at certain times. See documentation at the top here: http://rackerlabs.github.io/encore-ui/#/component/rxNotify. That should allow for the custom HTML needed to draw the button within the notification style.

Please let me know if you have questions! Assigning this to you since design is ready, so you can update "in progress" etc. depending on whether you're actively working.

**Comment by megalord** [comment]
@glynnis thanks! The Invision image and comments help a lot.  I know what to do for the app, but is this also something I should add to the framework's styleguide?

**Comment by glynnis** [comment]
@megalord I think exposing this pattern in the style guide would be good! I'd put it somewhere on http://rackerlabs.github.io/encore-ui/#/styleguide/forms

**Comment by megalord** [comment]
The pattern added to the styleguide only works because it is not being sent to a `rx-notifications` stack (such as page).  When notifications are added to a stack, the [html content is converted to a string](https://github.com/rackerlabs/encore-ui/blob/master/src/rxNotify/rxNotify.js#L46), meaning any bindings such as `ng-click` or `ng-disabled` will be lost.  I found I was able to manually reapply the click binding via the code below, but I feel this is too hacky to make a pattern out of.  Suggestions are welcome!

```coffeescript
angular.module 'infrastructure.common'
.directive 'manualSave', ($document, $timeout) ->
  restrict: 'A'
  link: (scope, element) ->
    if element.parent().hasClass 'notification-text'
      $timeout ->
        el = angular.element $document[0].querySelector('.manual-save')
        el.on 'click', ->
          scope.save()
```
```html
  <rx-notification stack="page">
    Changes made are not automatically saved.
    <span manual-save
      class="button submit xs manual-save"
      ng-click="save()"
      ng-disabled="anyErrors()">
      Save Now
    </span>
  </rx-notification>
```

**Comment by glynnis** [comment]
@megalord I've added some screens to InVision and granted you access. There are some comments on each screen to help explain interaction/functionality. Let me know if you have any questions: https://projects.invisionapp.com/d/main#/projects/3750442

I can also grant permission for other folks to view if there's anyone besides you who needs access to begin work on this.

**Comment by megalord** [comment]
@glynnis thanks!  It looks good to me.
