### ISSUE TITLE
Typeahead styles/component

### ISSUE THREAD

**Issue by glynnis** [rackerlabs/encore-ui#909]
An emerging need in Encore applications is the ability to provide type-ahead tools for a select box or field. We need to create visual/interactive design for this, and then get it added to the Framework in a way that is flexible and appropriate for use in multiple areas across Encore.

@megalord has some work already put in on this in an application, but not at the Framework level. He's currently using https://select2.github.io/, but we need to vet it for use at the Framework level.

cc @megalord @ElementE @parlarjb

**Comment by megalord** [comment]
My mistake, we are using https://github.com/angular-ui/ui-select2 which is based on select2.  However, that library is deprecated in favor of https://github.com/angular-ui/ui-select, which supposedly has the same functionality but without the dependency on the original select2 library.

![screen shot 2015-04-20 at 2 57 30 pm](https://cloud.githubusercontent.com/assets/5414922/7239207/9cdbd54e-e76d-11e4-8961-811c263a71fd.png)

While this is similar to the typeahead already in the framework, it retains the functionality of a normal select dropdown.

**Comment by glynnis** [comment]
@parlarjb very adeptly pointed out that we already have http://rackerlabs.github.io/encore-ui/#/component/typeahead, which I'm aware of. My hunch is it's not doing everything people need which is why we keep seeing other typeahead tools employed, so as part of this issue let's try to get to the bottom of why that is and see if we can update what we have to meet those needs.

**Comment by glynnis** [comment]
Just met with @megalord about this, commenting here so decisions are visible to other folks:

Jordan's interest in the type ahead tool he posted the screenshot of ^^ is that it allows you to see a dropdown of options *before* you start typing, rather than requiring you to have an idea of what to type. He felt this would be better for users in helping them see what options are available or that have already been created, and I agree.

He's going to look at the current typeahead tool that we have to see if he can match that kind of functionality with in the current set-up, that way we don't run into issues of having two separate typeaheads or introducing breaking changes by switching to a new typeahead tool all together.

He'll see where he can get with it and pull me in once he's gotten somewhere to skin and apply the Encore look and feel.

@megalord Feel free to update or correct if I got any of this wrong :smile:

**Comment by megalord** [comment]
@glynnis I found a way to modify the existing typeahead so that the list shows when the control is clicked (focused).  In this screenshot, the only style change I've made is giving it a max height and a scrollbar - other than that it looks just as it did before.
![screen shot 2015-05-15 at 9 54 54 am](https://cloud.githubusercontent.com/assets/5414922/7655364/8f0bd656-fae8-11e4-9a08-0ed53dcd980b.png)

**Comment by glynnis** [comment]
@megalord Awesome! I think this is great. Could you open a PR so we can get some other dev perspectives on it?
