### ISSUE TITLE
Create segmented control component

### ISSUE THREAD

**Issue by glynnis** [rackerlabs/encore-ui#910]
An emerging need in Encore applications for a control that allows choosing between options (like radios), but with more interactivity and visual feedback. I.e., something is needed that is like a radio, but for areas where there is no form being submitted and the user needs direct feedback.

Something kind of like this: 
![uisegmentedcontrol_button_ios7](https://cloud.githubusercontent.com/assets/1529366/7239189/78e629aa-e76d-11e4-9d98-6cea7188f554.jpg)

@megalord has something kind of like this already in a project, but it's not yet at a framework level.

cc @megalord @ElementE @parlarjb

**Comment by megalord** [comment]
@glynnis you're screenshot immediately reminded me of the new "Finish & Close" button added to the styleguide recently.  I think we can reuse our existing button styles to make this work, e.g.
![screen shot 2015-04-20 at 3 09 44 pm](https://cloud.githubusercontent.com/assets/5414922/7239406/55b9d2f4-e76f-11e4-814b-0f670905fddf.png)

**Comment by ElementE** [comment]
@megalord 
 Can we use button styles like those to toggle your data? Do you need to have "input-type=" functionality like what typically exists with standard radios? Im in agreement with your suggestion and @glynnis gave.

**Comment by ElementE** [comment]
![screen shot 2015-04-21 at 3 18 10 pm](https://cloud.githubusercontent.com/assets/7989545/7261738/a30c80fe-e839-11e4-8629-49afa6e79980.png)

**Comment by ElementE** [comment]
@megalord - Would this layout work for you? I steered away from bringing more blue into those selector-buttons. Thoughts?

**Comment by megalord** [comment]
Yeah, this looks good!  At first, I thought it wasn't obvious that the control affects the behavior of the dropdown, which was the advantage of positioning them vertically.  But I'm thinking this is fine too.

**Comment by ElementE** [comment]
Yeha i was concerned with eating anymore of your vertical space there. I can try it though and then let you see :)

**Comment by glynnis** [comment]
@megalord Looks like we've got design ready here for you, so I'm going to re-assign this to you and you can mark "soon"/"in progress" appropriately.

@ElementE Do you have color hexes for the switch backgrounds/text/outline? And a border radius measurement? Also one thing I just thought of: do we want to set a limit for how many segments can be used in a control? For instance, it would be pretty insane/pointless UX to have 10 segments. I'm thinking we should set a reasonable upper limit (or at least document it). @ElementE Do you think there's any additional design considerations we need to make for segmented controls that have more than two segments?

@megalord Feel free to bring me back in when it's time to get documentation written for this puppy.

**Comment by ElementE** [comment]
![segmented-control_doc](https://cloud.githubusercontent.com/assets/7989545/7378018/14fecec6-edb0-11e4-8353-cda28dca706e.png)
@megalord

**Comment by ElementE** [comment]
@megalord 
Let me know if this outlines all necessary specs. If you have any other questions or concerns - lemme know!

**Comment by megalord** [comment]
@ElementE My only concern is the colors.  I'm happy to add the ones you have specified, but that would contribute to the "50 shades of grey" problem.  Is that something we should consider?

**Comment by ElementE** [comment]
Understandable concern sir,
the grey usage here does steer in the direction of the controlled grey formula we're working on. So while it seems like we're introducing even more greys, these will be easier to change after standardization of the color palette. Including preview of that here (note-this is NOT final or approved yet, just wanna show for context to this problem): 
![encore-greys](https://cloud.githubusercontent.com/assets/7989545/7378399/b6606d86-edb2-11e4-9bc0-f880c7c424ca.png)

**Comment by megalord** [comment]
Awesome, I'll update the PR.  Thanks!

**Comment by CITguy** [comment]
We already have a `@inputBorderRadius` variable set to `0px` in `vars.less` for use by input controls. Does this segmented control component override that?

**Comment by megalord** [comment]
Yep, I wouldn't consider this a normal input.
