### ISSUE TITLE
Styles for inputs that look-up info

### ISSUE THREAD

**Issue by glynnis** [rackerlabs/encore-ui#911]
An emerging need in Encore applications for an input field that does a search/makes a call to look up something, then displays additional information about what it has looked up.

@megalord has something kind of like this already in a project, but it's not yet at a framework level. In the application he's working on, a user types in an account number, the account is looked up, and then the account username is displayed.

I think this kind of interaction could be valuable for many other apps, but we need to define the look/feel and interaction design and get it into the framework.

**Comment by megalord** [comment]
I like the way this looks with Bootstrap's input groups because it's clear that the information is tied to the input.
![screen shot 2015-04-20 at 3 12 41 pm](https://cloud.githubusercontent.com/assets/5414922/7239468/b7578fd8-e76f-11e4-8dfd-97d96903b753.png)

**Comment by glynnis** [comment]
This has a design story already: https://jira.rax.io/browse/UXENCORE-258

Closing

**Comment by ElementE** [comment]
@megalord - Jordan, can you provide any more context for this?
