### ISSUE TITLE
Session Expiration & Timezone Issue

### ISSUE THREAD

**Issue by halkon** [rackerlabs/encore-ui#913]
This might not be the right place but it's a start: 

In: https://github.com/rackerlabs/encore-ui/blob/a5bfe4e63b09540855cb098a1928fd2ddcb84f63/src/rxSession/rxSession.js#L72

We are comparing the token expiration date with `_.now`.   However, currently there's a racker with his timezone set to UK time, and as such after a certain period of time, his current time surpasses that of the token. 

Need to research how to better handle this situation if possible

**Comment by CITguy** [comment]
Can we convert the expiration date to UTC when saving to Session storage?  Then we compare the `now (as UTC)` to the expiration date.  I'm not sure if lodash `_.now` provides the functionality to do UTC date comparison.  We might look into using MomentJS for this functionality.

**Comment by CITguy** [comment]
This can move to JIRA

**Comment by halkon** [comment]
Thank you @CITguy I do believe this may be a non-issue so perhaps a spike could be done.  As it stands though it happened once, the most recent issue of timezones were upstream systems for our sessions.  

Nonetheless, when @julianbonilla looked at this, he found no issue as the dates were being checked correctly, if someone changes their timezone or moves their clock, we can't do much. 

#lastThoughts

**Comment by CITguy** [comment]
I'd like to move it to JIRA (if only for reference) considering that we're beginning to see more edge cases with regards to time zones. I feel like this may still be a relevant use case to reference when/if issues arise with rxDatePicker and rxTimePicker.

**Comment by anur2213** [comment]
Related Jira story:
https://jira.rax.io/browse/FRMW-450
