### ISSUE TITLE
Creating modals without rxModalAction requires "state" variable in scope

### ISSUE THREAD

**Issue by halkon** [rackerlabs/encore-ui#916]
https://github.com/rackerlabs/encore-tq-ui/blob/ETUI-652_upgrade-encore-ui-1.13.1/app/scripts/common/services/ModalUtil.js#L64-L66

When upgrading (from 1.6.1) to 1.13.1 of encore-ui we found a bug in where there's no default state on `rxModalFooter`, thus forcing us to set the state to `editing`. 

This won't happen if your modals are created by `rxModalAction` but when using `rxModalActionForm` separate from `rxModalAction`, it requires the variable to be set. 

PS.  It might also work if `rxModalActionForm` gets an attribute for the state of `editing` however that should still be a default `rxModalActionForm`.

https://github.com/rackerlabs/encore-ui/commit/603cafbcb09d67a801bd4c8e23938e1da359d6cc

**Comment by anur2213** [comment]
Associated Jira story: https://jira.rax.io/browse/FRMW-526
