### ISSUE TITLE
Create 'tags' component

### ISSUE THREAD

**Issue by glynnis** [rackerlabs/encore-ui#918]
Here's the look/feel for tags:

![tags](https://cloud.githubusercontent.com/assets/1529366/7307149/3b5f6e7e-e9d0-11e4-8ca0-5acce39865fa.png)

Interaction design for this is based on https://material.angularjs.org/#/demo/material.components.chips, which should be used as a base for building a tags component, since it provides good flexibility with read-only functionality, accommodates hierarchy through use of categories, etc. 

The main thing not provided by Material is a type-ahead drop down, but after consulting with @TheNando it sounds like that won't be too difficult to add and customize. See https://github.com/rackerlabs/encore-ui/issues/909, which should be used by default for this component.

**Comment by megalord** [comment]
@glynnis Here is an example of the current interaction:
![rx-tags](https://cloud.githubusercontent.com/assets/5414922/8935571/12c253bc-3513-11e5-88a2-012259464e7b.gif)
There are two things I'm aware of that are left:
1) backspace interaction: The first press highlights the last tag and another will remove it.  Is this a good idea from a design perspective?
2) disabled state: The example basically just removes the `X` button from the tags.  Is that how we want to communicate the disabled state?  Traditionally we would also change the background from white to grey.

**Comment by glynnis** [comment]
Good questions! Spoke with @ElementE about this for clarification.

1) Backspace interaction should work as you indicated (see example that works that way here: https://material.angularjs.org/latest/#/demo/material.components.chips). Highlight color should be #007bff.

2) Disabled state should: remove the X button from tags, remove the outline from the tag area (since it's no longer interactive), remove the "Enter a tag" text.

One option to consider (but that shouldn't hold up this work if it's complex) is that we may also need a version that reveals the list on click (like the second example on http://rackerlabs.github.io/encore-ui/#/components/typeahead). Requiring the user to type should be the default, but it would be nice to allow consumers of the framework an option to use the second example. If adding that is complex, please open a new issue and don't let it hold up the work you've already done.

Thanks for your patience! This is looking awesome so far.

**Comment by glynnis** [comment]
@parlarjb FWIW, this is something that's needed for PhoneUI (detail pages)
