### ISSUE TITLE
Add a callback for when a notification has been dismissed

### ISSUE THREAD

**Issue by halkon** [rackerlabs/encore-ui#927]
Allow to add a callback for when a notification has been dismissed (and even perhaps removed from the stack)

This will allow to create triggers on the application when certain notifications are dismissed, without having to watch the stack:

https://github.com/rackerlabs/encore-tq-ui/pull/304/files#r29440711

**Comment by parlarjb** [comment]
Completed with https://github.com/rackerlabs/encore-ui/pull/933
