### ISSUE TITLE
Add documentation for table actions

### ISSUE THREAD

**Issue by glynnis** [rackerlabs/encore-ui#931]
Looking through documentation today, I don't think we've documented anywhere the pattern we use when an action link pertains only to a table and not a full page.

For example:
![cell-details](https://cloud.githubusercontent.com/assets/1529366/7432297/867ac0da-efec-11e4-9115-ebf5d86b2740.png)

We need to get this in the Styleguide.

**Comment by megalord** [comment]
Good to know; I wasn't aware of this pattern.

**Comment by lfielder** [comment]
I agree, this needs to be in the styleguide.

**Comment by megalord** [comment]
I'm curious how this pattern will scale.  What happens when there are many actions (think six or more)?  That doesn't seem to fit well if they are oriented horizontally or vertically.  Would it make sense to use an action menu (cog) instead?

**Comment by CITguy** [comment]
This pattern is for single actions. If you have more than one action, yes, you would use an action menu.

**Comment by CITguy** [comment]
Closing. Captured in JIRA https://jira.rax.io/browse/FRMW-63
