### ISSUE TITLE
Create/document pattern for "help" tooltip

### ISSUE THREAD

**Issue by glynnis** [rackerlabs/encore-ui#932]
We need to document a pattern for showing "help" tooltips next to form fields and around Encore (table cells, etc.).

This is an emerging pattern that we've seen a few different implementations for. Here's a great example from Infrastructure Manager (blue question marks get a tooltip on hover):
![cell-details---modal](https://cloud.githubusercontent.com/assets/1529366/7435850/331c22fa-f00d-11e4-9a9b-fbafeb526436.png)

FWIW @megalord, I don't think this is something that needs to be addressed before the Infrastructure Manager is ready for prime time, just documenting as something to look into in the future.

@ElementE What do you think about using the Font Awesome info "i"? I recall that being in some early PSD/style guide docs that I think you worked on.

@parlarjb Would it make sense for something like this to be a directive, or just styles?

**Comment by kobowley** [comment]
@glynnis great call out we definitely need this documented as a style or a directive.

**Comment by parlarjb** [comment]
@glynnis This would go well with the work @CITguy is doing in https://github.com/rackerlabs/encore-ui/issues/884

**Comment by CITguy** [comment]
Work on #884 with field suffixes should still support this UI pattern. It would apply similar to what is seen in "Prefix/Suffix Combinations" at http://output.jsbin.com/bumibi (just replace "Million" with what's needed).

**Comment by CITguy** [comment]
Let's move to JIRA

**Comment by anur2213** [comment]
Related Jira story:
https://jira.rax.io/browse/FRMW-448
