### ISSUE TITLE
Callback for Nav collapse/expand

### ISSUE THREAD

**Issue by halkon** [rackerlabs/encore-ui#934]
Will allow applications to be notified when the nav has been expanded/collapsed for the purpose of tracking state of the nav locally (or externally, per app)

This will allow the following to not be done via a `$scope.$watch` but rather a callback function
https://github.com/rackerlabs/encore-tq-ui/pull/314/files#diff-685dfa901a119f6590e773891ffd6052R434

**Comment by parlarjb** [comment]
Can you think of any other use cases for this feature? To implement this, we'd need a new global `$watch`, as well as a registration service/factory to let arbitrary controllers/apps register callbacks for this event, and for `rxApp` to be able to call those callbacks. It seems like a lot for something that might only get used in once place.

**Comment by halkon** [comment]
Why would we need a global watch? mind you I ought to look into the code itself but I figured the collapsing of the nav would be a functional thing rather than a template variable setting?

If it is a global watch, then we might as well just let each application handle it if need be.  

I'll dive into the code and see, but that seems like more work than what I was expecting.

**Comment by halkon** [comment]
Not that I don't trust your judgement :grin: just need to :facepalm: for myself :grimacing:

**Comment by halkon** [comment]
And I see the issue: 

https://github.com/rackerlabs/encore-ui/blob/master/src/rxApp/templates/rxApp.html#L6
https://github.com/rackerlabs/encore-ui/blob/master/src/rxToggle/rxToggle.js#L11

Slightly disappointing, but obviously enough of a big deal to do a huge overhaul just to convert something from `rx-toggle` to `ng-click` and define the function internally to then do a callback. 

We'll keep our watch, I still don't like it but we got better battles to fight

**Comment by glynnis** [comment]
Adding "Move to JIRA" label. @ElementE and I have discussed functionality like this for new app bar/notifications treatment, so this s still relevant I think.

**Comment by anur2213** [comment]
Related Jira story:
https://jira.rax.io/browse/FRMW-447
