### ISSUE TITLE
Add deprecation warning to Pure grid

### ISSUE THREAD

**Issue by glynnis** [rackerlabs/encore-ui#947]
Now that we have the flexbox grid/layout component available (http://rackerlabs.github.io/encore-ui/#/component/layout), we need to add a warning to the Pure grid/style guide to indicate that the Pure grid will be deprecated in the near future.

**Comment by TheNando** [comment]
This is what I put in as part of the layouts module update:

![screen shot 2015-05-12 at 11 06 35 am](https://cloud.githubusercontent.com/assets/6663710/7592050/e7869a5e-f896-11e4-9bda-362350115a8f.png)

**Comment by glynnis** [comment]
@TheNando Oh, awesome. For some reason during today's Framework Stakeholders meeting we thought this hadn't been done yet. cc @kobowley 

Since you've got it covered already, I'll close this issue.

**Comment by megalord** [comment]
Actually @glynnis, this also needs to be addressed in the [styleguide](http://rackerlabs.github.io/encore-ui/#/styleguide/layouts), which has no indication that the old grid is being deprecated or that there is a new layout component.

**Comment by CITguy** [comment]
Additionally, the stability index for pure grids should be updated to `deprecated`.
