### ISSUE TITLE
Document Notes treatment in Framework

### ISSUE THREAD

**Issue by glynnis** [rackerlabs/encore-ui#949]
We need to document visual treatment for Notes in the Framework, as it's an emerging pattern but doesn't exist anywhere in our design documentation.

We should also determine where styles for Notes currently live, and if it's not in the Framework we need to discuss moving them there.

Here's an example of what Notes look like in Billing today:
![screen shot 2015-05-12 at 1 46 55 pm](https://cloud.githubusercontent.com/assets/1529366/7595567/73d5d3ec-f8ad-11e4-8294-5b95536d1aef.png)

**Comment by glynnis** [comment]
@lfielder @ElementE Were either of you able to resolve/reconcile what the "new notes treatment" is with Nordy, and whether we need to worry about shifting to that for now?

**Comment by glynnis** [comment]
@kobowley I think if we're adding this to the Framework, it's also time to get tags added to the Framework, which Eric and I have done design for but hasn't been developed/added to a sprint yet. Could we get that on the list for the next EOD sprint?

**Comment by kobowley** [comment]
@glynnis yes I think this goes to the top of the order notes and tags. 
@velveteer can you please send link to the notes work you did and got feedback from Nordy on.

**Comment by jschairb** [comment]
@glynnis another pattern that I think could possibly be related to a way to display notes is the idea of a 'timeline'/'newsfeed' for a customer, user, server, or other entity. Could we work the pattern to be a list of text displayed ordered by time stamp? Examples: http://www.mobilemozaic.com/timelines.html

**Comment by velveteer** [comment]
@kobowley This is where Nordy and I discussed the notes design: https://jira.rax.io/browse/EOD-372. The screenshots are outdated by now since I incorporated his feedback. The main takeaway was that the ability to create a note was integrated into the note table, instead of how it appears now where the form hovers above the table.
