### ISSUE TITLE
Figure out where to add rxFeedback to the styleguide

### ISSUE THREAD

**Issue by parlarjb** [rackerlabs/encore-ui#954]
When https://github.com/rackerlabs/encore-ui/pull/946 gets merged in, new Encore products will be able to request a custom feedback endpoint be created for them, which is managed by the Encore team. We need somewhere in the style guide to tell teams that they should be doing that (i.e. if we get a proper "Getting Started" in the style guide itself, not just a readme in github)

**Comment by CITguy** [comment]
Closing. Handled in tutorial.
