### ISSUE TITLE
Textarea descriptions with character count

### ISSUE THREAD

**Issue by TheNando** [rackerlabs/encore-ui#956]
A common design when using textareas with character count is to include some contextual info along the bottom of the textarea. See the mockup below as an example.

![image](https://cloud.githubusercontent.com/assets/6663710/7656642/6535efb6-faf1-11e4-9726-efe65a26040c.png)

A similar effect is achieved using rx-form-item with a 'description' attribute.

![image](https://cloud.githubusercontent.com/assets/6663710/7656667/93ec594e-faf1-11e4-8492-5a5ff8d1af9e.png)

However, placing the textarea within an rx-form-item does not place the description text in the desired location, overrides the textarea's width, and because the label is also mandatory, offsets the textarea.

```
<div class="comments">
  <h4 class="title sm subdued">Add comments for this payment:</h4>
  <rx-form-item description="Adding a comment to the payment is optional, not required.">
    <textarea ng-model="payment.comments" rows="6" rx-character-count></textarea>
  </rx-form-item>
</div>
```

![image](https://cloud.githubusercontent.com/assets/6663710/7656727/0b98381e-faf2-11e4-9547-ac20ab8b3837.png)

**Comment by CITguy** [comment]
What about something like this?
![screen shot 2015-05-19 at 2 10 56 pm](https://cloud.githubusercontent.com/assets/545605/7711668/91441fe0-fe31-11e4-9315-1ae33a9871cf.png)

**Comment by CITguy** [comment]
**NOTE:** This is based on upcoming form refactor work and is currently a prototype.

### Text Area with character count (prototype)
![screen shot 2015-05-19 at 4 09 02 pm](https://cloud.githubusercontent.com/assets/545605/7714072/685d07ee-fe41-11e4-8bef-e837cc547e3b.png)

### Text Input with character count (prototype)
After discovering that some apps are using `rxCharacterCount` on `<input>` fields. I came up with the idea in this screenshot to place the character count inline with the form input.

![screen shot 2015-05-19 at 4 09 06 pm](https://cloud.githubusercontent.com/assets/545605/7714074/6cd1a5d2-fe41-11e4-8e02-dcb3566c69dd.png)

**Comment by CITguy** [comment]
It just occurred to me that there's an HTML `maxlength` property that can be used to restrict the input length for both `<textarea>` and text `<input>` fields.  All browsers comply with this attribute, too.  

### Examples using `maxlength`
![screen shot 2015-05-28 at 10 26 12 am](https://cloud.githubusercontent.com/assets/545605/7863799/f9b6ac16-0523-11e5-97f7-96f6c3101d6f.png)

![screen shot 2015-05-28 at 10 30 57 am](https://cloud.githubusercontent.com/assets/545605/7863904/92ab8630-0524-11e5-9355-b56be2054fde.png)


## Questions

1. Is it absolutely necessary to allow the user to go over the limit?
2. Should we look into making `rxCharacterCount` work with `maxlength` to apply a warning style when the user has few characters remaining (and not allow the user to go over the `maxlength`)?

**Comment by CITguy** [comment]
This should be moved to JIRA to capture additional conversations.

**Comment by anur2213** [comment]
Related Jira story:
https://jira.rax.io/browse/FRMW-446
