### ISSUE TITLE
Upgrade Lodash to 3.x.x

### ISSUE THREAD

**Issue by megalord** [rackerlabs/encore-ui#969]
Aside from various improvements, newer versions of lodash have a set of string methods that would be nice to have. The [Changelog](https://github.com/lodash/lodash/wiki/Changelog) has a link to a cli that can help the migration path.

**Comment by CITguy** [comment]
Based on [3.0.0 Changelog](https://github.com/lodash/lodash/wiki/Changelog#v300)

### flatten
Data option now an argument to the returned function.

```javascript
var string = '<%= o.a %>',
    options = { 'variable': 'o' },
    data = { 'a': 'b' };

// in 2.4.1
_.template(string, data, options); // → 'b'

// in 3.0.0
_.template(string, options)(data); // → 'b'
```

Update:
- [ ] `src/rxAccountInfo/rxAccountInfo.js`
- [ ] `src/rxForm/rxForm.spec.js`
- [ ] `src/rxModalAction/rxModalAction.spec.js`
- [ ] `src/rxPaginate/rxPaginate.js`
- [ ] `src/rxStatus/rxStatus.js`

### lodash.compat.js
* Moved ./dist/lodash.compat.js to the lodash/lodash-compat repository
  - [ ] use `lodash-compat` npm package

### Others
* `_.first`, `_.last`, `_.initial`, and `_.rest` are ok considering we're using the simple form (advanced forms use new methods)
* Low risk compatibility warnings should be fine considering we're not using them in the way mentioned in the release notes.
*

**Comment by megalord** [comment]
I have a [branch](https://github.com/rackerlabs/encore-ui/tree/lodash) with much of this (if not all, I can't remember) already done.  This update could be considered a breaking change for many apps, as all consumers might have to do the same migration.  I think this might be part of Encore 2 for that reason.

**Comment by halkon** [comment]
don't make me :cry: @megalord, however I do not think a lot of apps really do have the same migration pain as this would.  I think in most cases people read the docs from version `3.x.x` without realizing they were different. 

The two big ones obviously are cloud and ticketing, ticketing we saw no expected changes.

**Comment by CITguy** [comment]
Let's move this to JIRA for prioritization and continued discussion.

**Comment by anur2213** [comment]
Related Jira story:
https://jira.rax.io/browse/FRMW-445
