### ISSUE TITLE
Add `maybeNA` filter

### ISSUE THREAD

**Issue by CITguy** [rackerlabs/encore-ui#972]
JIRA: https://jira.rax.io/browse/UXENCORE-197

Rather than displaying a blank string or no value in the UI, when a value is blank, empty, or undefined, display "N/A" instead. I believe this would be achievable via a `maybeNA` angular filter that will output "N/A" if any of the following conditions are true:

* a json object is empty (`{}`)
* an array is empty (`[]`)
* a string is empty (`''`, `'  '`, etc.)
* the value is `undefined`
* etc.

In all other cases, the value will be displayed as usual.

**Comment by sundip** [comment]
Would the name `displayNA` make more sense?

**Comment by nancyAfox** [comment]
@glynnis This looks like issue that we were just discussing.

**Comment by CITguy** [comment]
@sundip, `displayNA` gives the notion that it will always display "N/A". The filter should only display "N/A"  in the case of no data, so it's not always but `maybe`.

**Comment by jj4th** [comment]
If it's a filter, how about ```emptyNA```

**Comment by kyleondata** [comment]
Should this also take into account NaN ?

**Comment by CITguy** [comment]
@kyleondata yes

**Comment by anur2213** [comment]
Associated Jira story: https://jira.rax.io/browse/FRMW-525
