### ISSUE TITLE
Rework modal design for more intuitive wizard support

### ISSUE THREAD

**Issue by TheNando** [rackerlabs/encore-ui#974]
The current rxModalAction handles multiple state modals (aka, "Wizards") very clumsily. The way the 'state' methods are injected into scope also creates issues when unit testing attached controllers when making use of the setState at the rootscope of the controller. We should rework how a multi page modal is implemented. I would personally like a multi-template based system rather than a dynamic component based one like we have now.

**Comment by glynnis** [comment]
@TheNando @CITguy Still relevant? Not sure if this issue was created before multi-screen modals, or whether multi-screen modals address this.

**Comment by CITguy** [comment]
Probably still relevant, but I've not had much experience developing multi-modals, so I'll leave it to @TheNando for the final say.

**Comment by glynnis** [comment]
Pinging @TheNando

**Comment by anur2213** [comment]
Associated Jira story: https://jira.rax.io/browse/FRMW-524
