### ISSUE TITLE
rxForm method aliases, and eventual deprecation.

### ISSUE THREAD

**Issue by Droogans** [rackerlabs/encore-ui#975]
rxForm has already begun a migration. Checkboxes, dropdowns, and radio buttons have all been split up from the once massive rxForm. This is a Good Thing. However, in the process, a lateral change was made. `rxForm.checkbox.unselect` was moved to `rxCheckbox.deselect`.

Here is a plan to move away from a soon to be deprecated `unselect` to the new `deselect` methods.

### Encore 1.x 
- [x] Alias `rxForm.checkbox.unselect` to point to `rxCheckbox.deselect`. Leave the inconsistent API.
- [x] Mark `rxForm.checkbox.unselect` as deprecated, add `rxForm.checkbox.deselect` alongside it.

### Encore 2.0
- [ ] Delete `rxForm.checkbox.unselect`.

Repeat this process for anything marked `un-action`, unless it makes sense. Prefer the use of `de-action` instead.

**Comment by CITguy** [comment]
@Droogans, is this issue still valid?

**Comment by Droogans** [comment]
Still have to un-alias stuff. This was created when I discussed the issue with @parlarjb, he said make a plan of action to actually remove public functions for the rx-page-objects API, and that we'll get rid of the aliases at 2.0 (when it happens).

I still think test code API changes should be considered separately from developer API changes, but I should probably not be listened to as an authority on that kind of decision since I'm an SDET, not a dev.

**Comment by CITguy** [comment]
This should be moved to "Deprecation" epic on JIRA

**Comment by anur2213** [comment]
Related Jira story:
https://jira.rax.io/browse/FRMW-444
