### ISSUE TITLE
Include visual regression support.

### ISSUE THREAD

**Issue by Droogans** [rackerlabs/encore-ui#976]
Protractor 2.0 does not break users who have not upgraded. It only means those using Protractor 2.0 can do so when using rx-page-objects.

However, including visual regression tools as a first class citizen in rx-page-objects (likely under `encore.snap(this, $('.element'))` *will* break a user on protractor 1.x.

**Comment by anur2213** [comment]
Associated Jira story: https://jira.rax.io/browse/FRMW-519
