### ISSUE TITLE
Move all raw web element properties of page objects into a namespace.

### ISSUE THREAD

**Issue by Droogans** [rackerlabs/encore-ui#977]
In an effort to de-clutter page objects, move to something that looks less like this.

```js
module.exports = Page.create({

    lblAccountBalance: {
        get: function () {
            return element(by.binding('balance.currentBalance'));
        }
    },

    lblPastDue: {
        get: function () {
            return element(by.binding('balance.pastDue'));
        }
    },

    lnkReach: {
        get: function () {
            return element(by.css('rx-reach-billing-link a'));
        }
    }

});
```

And more like this.

```js
module.exports = Page.create({
    mappings: {
        get: function () {
            return {
                get lblAccountBalance() { return element(by.binding('balance.currentBalance')); },
                get lblPastDue() { return element(by.binding('balance.pastDue')); },
                get lnkReach() { return element(by.css('rx-reach-billing-link a')); }
            };
        }
    }
});
```

This make it more obvious to end users that these should not be manipulated directly. The list of web elements are more compact. Also, sorting the list of web elements needed to build a page object is very easy to do.

**Comment by Droogans** [comment]
This may not work well with components that come pre-built with web elements in them already, such as `rxModalAction` (it has already defined `this.rootElement`, `this.btnSubmit`, and others).

I'm looking into how to gracefully handle pre-defined web elements in a getter, but for now my first attempt hasn't panned out. I'm thinking in order to handle it, you'll have to ask for a `mappings` object explicitly, which I don't like.

**Comment by CITguy** [comment]
@Droogans, is this still valid considering the page object refactoring that you've done in #1103?

**Comment by Droogans** [comment]
This is no longer valid, and not because of #1103. I gave this an attempt but found it difficult to next getters into Astrolabe page objects. It prevented me from creating things like custom functionality in rxModalAction, which was a deal breaker, unfortunately.
