### ISSUE TITLE
Move utility functions to `rxMisc`

### ISSUE THREAD

**Issue by Droogans** [rackerlabs/encore-ui#978]
`rxForm` is a catch-all of sorts. There is a function that lives there in the page objects that converts the string output from Angular's currency filter and turns it into an integer for pennies that match the value of the currency string.

This is only in `rxForm` because `rxMisc` didn't exist at the time. Move it there.

### Encore 1.x 
- [x] Alias `rxForm.currencyToPennies` to point to `rxMisc.currencyToPennies`.
- [x] Alias `rxForm.slowClick` to point to `rxMisc.slowClick`.
- [x] Alias all `rxForm.*.generateAccessor` to point to `rx*.generateAccessor`
- [x] Mark `rxForm.currencyToPennies` as deprecated.
- [x] Mark `rxForm.slowClick` as deprecated.
- [x] Mark `rxFloatingHeader.*` as deprecated.

### Encore 2.0
- [ ] Delete `rxForm.currencyToPennies`.
- [ ] Delete `rxForm.slowClick`.
- [ ] Delete `rxForm.form`
- [ ] Delete `rxForm.*.generateAccessor`
- [ ] Delete `rxFloatingHeader.*`

**Comment by CITguy** [comment]
@Droogans, how much of this is still valid?

**Comment by Droogans** [comment]
Once the aliases go away we're set.

**Comment by anur2213** [comment]
Associated Jira story: https://jira.rax.io/browse/FRMW-518
