### ISSUE TITLE
Re-evaluate Tooltip Colors

### ISSUE THREAD

**Issue by CITguy** [rackerlabs/encore-ui#981]
Tooltip background matches table header. Needs more contrast.

![2c14edd6-00be-11e5-8604-029fd0988040](https://cloud.githubusercontent.com/assets/545605/7775613/32e447cc-007a-11e5-8483-0d6af1d76474.png)

**Comment by glynnis** [comment]
Adding this to https://jira.rax.io/browse/FRMW-339 so it can get rolled into the color refactor. Closing.
