### ISSUE TITLE
rxSelectFilter does not populate "All except ..." properly on initialization

### ISSUE THREAD

**Issue by cmartinez1499** [rackerlabs/encore-ui#984]
When initializing an rxSelectFilter through a controller and selecting all but one of the available options, the UI should display "All except [excluded item]", but instead displays "All except". This only happens during initialization.
![screen shot 2015-05-26 at 1 08 02 pm](https://cloud.githubusercontent.com/assets/1155834/7819755/6ffce3da-03a9-11e5-9e61-b1d8a309d5b9.png)
![screen shot 2015-05-26 at 1 07 48 pm](https://cloud.githubusercontent.com/assets/1155834/7819758/7354aeb4-03a9-11e5-932a-72cacbb05b8e.png)

**Comment by megalord** [comment]
Yeah, I noticed this as well the other day, but it isn't partial to the "All except" case.  When using dynamic options for the multi-select (e.g. using the options attribute instead of rxSelectOption), the label in the dropdown isn't rendered before the component grabs it for the preview text.
