### ISSUE TITLE
rxCollapse doesn't have see more or less option

### ISSUE THREAD

**Issue by ccarteronline** [rackerlabs/encore-ui#989]
A story in Billing: EOD-614 requires a button that toggles between items being shown or hidden. This is the same functionality of the rxCollapse. There should be another feature alongside the default to allow for the see more button to be present as the visual screenshot in EOD-614 billing shows
![68846444](https://cloud.githubusercontent.com/assets/4607236/7838402/59171c04-0452-11e5-9ce3-3f3a60986713.png)
![68843974](https://cloud.githubusercontent.com/assets/4607236/7838401/5915a900-0452-11e5-8373-96e07f743526.png)
![screen shot 2015-05-27 at 9 27 25 am](https://cloud.githubusercontent.com/assets/4607236/7838456/9f8140e8-0452-11e5-8293-e9d8979753f5.png)
![screen shot 2015-05-27 at 9 27 35 am](https://cloud.githubusercontent.com/assets/4607236/7838457/9f93891a-0452-11e5-9c51-d07b8be6c9b2.png)

**Comment by julianbonilla** [comment]
Seems like we're trying to add three additional features to this component based on the Billing screenshot.

1. Border vs Borderless
2. Position of the toggle (before/after title)
3. Show/hide content and animation above/below title

/cc @parlarjb @glynnis @ccarteronline

**Comment by glynnis** [comment]
@julianbonilla @ccarteronline For context: I think the idea that led to modifying rxCollapse was primarily that it's a similar action/user experience -- an accordion-like component that expands or hides content based on a click, but you all have a much better understanding of the back end than I do. If making a new component makes more sense (cleaner code, easier to update/maintain, etc.), let's proceed that way :+1:

**Comment by parlarjb** [comment]
Based on what I saw in Invision, I was thinking along the lines of the title. I had missed the whole border thing.

My thought for the title was this: We currently allow people to specify a one-time title. The Invision wireframes were showing "See More" and "See Less". I thought we could make the normal title now be optional. If the dev doesn't provide a title, then the component will instead use "See More" and "See Less". If they do provide a title, then we'll use that title instead.

With regards to the border, we can hopefully do that with optional CSS classes.

**Comment by julianbonilla** [comment]
After looking at #1022 and #1026 I think this should be a separate component.

Something like: http://jsbin.com/gemecibiri/edit?html,js,output

**Comment by CITguy** [comment]
Is this issue still valid considering that #1026 has been merged?

**Comment by glynnis** [comment]
@CITguy I think this just didn't get closed out with the merge. Closing now.
