### ISSUE TITLE
Run unit tests against PhantomJS and Chrome on Travis

### ISSUE THREAD

**Issue by parlarjb** [rackerlabs/encore-ui#992]
We should investigate running our unit tests against both PhantomJS and Chrome on Travis, as we already have `xvfb` running on Travis.

The reason for this is that there were some recent changes to Chrome that caused some of our code to fail, but we weren't catching it because those changes didn't make it to PhantomJS. Only by running `grunt test:debug` (which uses Chrome) were we able to see these failures.

Something like http://tobyho.com/2015/01/09/headless-browser-testing-xvfb/ should give a starting point for getting this working.

**Comment by CITguy** [comment]
Closing. Captured in JIRA https://jira.rax.io/browse/FRMW-85
